/*
 * File: app/view/menu/menuPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.KA.KAcreditAgainWinViewController', {
	extend : 'Ext.app.ViewController',
	alias : 'controller.KAcreditAgainWin',
	control: {},
	// 撤销征信
	onCreditRevokeClick : function() {
		var win = this.getView();
		var form = this.lookupReference('snCreditInfoForm').getForm();
		var creditCode = form.findField('creditCode').value;
		var taskId = form.findField('taskId').value;
		var processInstanceId = form.findField('processInstanceId').value;
		var comment = this.getView().down('#commentItemId').value;
		
		Ext.MessageBox.confirm('提示', '确定撤销征信?', function(btn) {
			if (btn != 'yes') {
				return;
			}
			if (!comment) {
				Ext.Msg.alert("提示", "请在流程备注中填写撤销征信原因！");
				return;
			}
			win.mask("请稍等，正在处理中...","x-mask-loading");
			// 删除操作
			Ext.Ajax.request({
				url : 'snCreditInfo/orderCreditCheck',
				params : {
					'businessKey' : creditCode,
					'taskId' : taskId,
					'processInstanceId' : processInstanceId,
					'node' : 'scOrderCreditRevoke',
					'comment' : comment,
				},
				async : false,
				success : function(response) {
					win.unmask();
					if(response.status==200 && response.statusText=='OK'){
						var responseText = JSON.parse(response.responseText);
						if (responseText.result=='failure' && responseText.errorMsg) {
							if (responseText.errorMsg) {
								Ext.Msg.alert("提示", responseText.errorMsg);
							} else {
								Ext.Msg.alert("提示", "系统错误，操作失败！");
							}
						} else {
							Ext.Msg.alert("提示",'提交成功',function(){
		     	    			var myActiveTaskGrid = Ext.ComponentQuery.query('#myActiveTaskGrid')[0];
		     	    			var myActiveTaskStore = myActiveTaskGrid.getStore();
		     	    			myActiveTaskStore.loadPage(1 ,{"start":0,"limit":20});
		     	    			var eastPanel = Ext.ComponentQuery.query("#eastPanelId")[0];
				    	        eastPanel.removeAll();
		     	    			win.close();
		     	    		});
						}
					}else{
                		Ext.Msg.alert("提示","系统错误,操作失败!");
                	}
				}
			});
		});
	},
	// 提交征信
	onCreditSubmitClick : function() {
		var win = this.getView();
		var form = this.lookupReference('snCreditInfoForm').getForm();
		var creditCode = form.findField('creditCode').value;
		var taskId = form.findField('taskId').value;
		var processInstanceId = form.findField('processInstanceId').value;
		var comment = this.getView().down('#commentItemId').value;
		
		Ext.MessageBox.confirm('提示', '确定提交征信?', function(btn) {
			if (btn != 'yes') {
				return;
			}
			win.mask("请稍等，正在处理中...","x-mask-loading");
			// 删除操作
			Ext.Ajax.request({
				url : 'snCreditInfo/orderCreditCheck',
				params : {
					'businessKey' : creditCode,
					'taskId' : taskId,
					'processInstanceId' : processInstanceId,
					'node' : 'scOrderCreditCheck',
					'comment' : comment,
				},
				async : false,
				success : function(response) {
					win.unmask();
					if(response.status==200 && response.statusText=='OK'){
						var responseText = JSON.parse(response.responseText);
						if (responseText.result=='failure' && responseText.errorMsg) {
							if (responseText.errorMsg) {
								Ext.Msg.alert("提示", responseText.errorMsg);
							} else {
								Ext.Msg.alert("提示", "系统错误，操作失败！");
							}
						} else {
							Ext.Msg.alert("提示",'提交成功',function(){
		     	    			var myActiveTaskGrid = Ext.ComponentQuery.query('#myActiveTaskGrid')[0];
		     	    			var myActiveTaskStore = myActiveTaskGrid.getStore();
		     	    			myActiveTaskStore.loadPage(1 ,{"start":0,"limit":20});
		     	    			var eastPanel = Ext.ComponentQuery.query("#eastPanelId")[0];
				    	        eastPanel.removeAll();
		     	    			win.close();
		     	    		});
						}
					}else{
                		Ext.Msg.alert("提示","系统错误,操作失败!");
                	}
				}
			});
		});
	},
});
