/*
 * File: app/view/menu/menuPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.KA.KAsubmitEditWinViewController', {
	extend : 'Ext.app.ViewController',
	alias : 'controller.KAsubmitEditWin',
	control: {},
	// 二网查询
	querySnCustomerList : function () {
		var win = Ext.create({
			xtype : 'snCustomerListWin',
			closeAction : 'destroy'
		});
		win.down('#selectSnCustomerOKBtn').on({
			click : 'onSnCustomerSelect'
		})
		win.show();
	},
	// 产品查询
	queryCarProductList : function () {
		var vin = this.getView().down('#vinItemId');
		var carEngineNo = this.getView().down('#carEngineNoItemId');
		var storageCode = this.getView().down('#storageCodeItemId');
		var slocCode = this.getView().down('#slocCodeItemId');
		var dispatchedDate = this.getView().down('#dispatchedDateItemId');
		
//		Ext.MessageBox.confirm('提示', '切换产品后原有的配车信息将自动清除，确定切换产品?', function(btn) {
//			if (btn != 'yes') {
//				return;
//			}
//			
//			// 清除配车信息
//			vin.setValue('');
//			carEngineNo.setValue('');
//			storageCode.setValue('');
//			slocCode.setValue('');
//			dispatchedDate.setValue('');
//			
			var win = Ext.create({
				xtype : 'carProductsWin',
				closeAction : 'destroy'
			});
			win.down('#selectContractCarId').on({
				click : 'onSnCustomerSalesOrderEditSelectCar'
			})
			win.show();
//		});
	},
	
	// 配车
	onAllocationCarClick : function () {
		var carProductCode = this.getView().down('#carProductCodeItemId');
		if (carProductCode.value) {
			var win = Ext.create({
				xtype : 'carStockWin',
				closeAction : 'destroy'
			});
			win.getViewModel().getStore('carStockStore').getProxy().extraParams = {
				productCode : carProductCode.value
			};
			win.down('#carStockWinProductItem').setValue(carProductCode.value);
			win.down('#selectContractCarId').on({
				click : 'onSnCustomerSelectCar'
			})
			win.show();
		} else {
			Ext.Msg.alert("提示",'请先选择车辆产品！');
		}
	},
	
	// 取消配车
	onCancelAllocationCarClick : function () {
		var vin = this.getView().down('#vinItemId');
		var carEngineNo = this.getView().down('#carEngineNoItemId');
		var storageCode = this.getView().down('#storageCodeItemId');
		var slocCode = this.getView().down('#slocCodeItemId');
		var dispatchedDate = this.getView().down('#dispatchedDateItemId');
		
		Ext.MessageBox.confirm('提示', '确定取消配车?', function(btn) {
			if (btn != 'yes') {
				return;
			}
			
			// 清除配车信息
			vin.setValue('');
			carEngineNo.setValue('');
			storageCode.setValue('');
			slocCode.setValue('');
			dispatchedDate.setValue('');
			
		});
	},
	
	// 保存
	onSnCustomerSalesOrderSave : function () {
		var form = this.lookupReference('snCustomerSalesOrderForm').getForm();
		var grid = Ext.ComponentQuery.query("viewport KAsubmitBySalesOrderPanel #snCustomerSalesOrderGrid")[0];
		var store = grid.getStore();
		if (!form.isValid()) {
			return;
		}
		var win = this.getView();
		form.submit({
			success : function(form, action) {
				if (action.result.errorMsg) {
					Ext.Msg.alert("提示", action.result.errorMsg);
				} else {
					Ext.Msg.alert("提示", "保存成功！");
					store.reload();
					win.close();
				}
			},
			failure : function(form, action) {
				Ext.Msg.alert("提示", "系统错误，操作失败！");
			}
		})
	},
	
	// 充电桩方式改变
	onChargerMethodChange : function (como, newValue, oldValue){
		var chargerFee = this.lookupReference('chargerFeeRef');
		var actualPrice = this.lookupReference('actualPriceRef');
		var orderAmount = this.lookupReference('orderAmountRef');
    	if (newValue==1) { // 挂靠
    		chargerFee.setValue(3000);
    		chargerFee.readOnly = false;
    	} else {
    		chargerFee.setValue(0);
    		chargerFee.readOnly = true;
    	}
	},
	
	// 挂靠金额或者销售金额改变
	onMoneyChange : function (){
		var chargerFee = this.lookupReference('chargerFeeRef');
		var actualPrice = this.lookupReference('actualPriceRef');
		var orderAmount = this.lookupReference('orderAmountRef');
		var chargerFeeVal = chargerFee.value ? parseFloat(chargerFee.value) : 0;
		var actualPriceVal = actualPrice.value ? parseFloat(actualPrice.value) : 0;
    	orderAmount.setValue(chargerFeeVal+actualPriceVal);
	},
	
	// 上传征信附件
	onUploadCreditClick:function(){
		var form = this.lookupReference('snCustomerSalesOrderForm');
    	var businessKey = form.getForm().getValues().code;
    	var businessType = "attachBizEntityType_EWZXCL";
    	var businessTypeName = "二网征信材料";
    	if (!businessKey) {
    		Ext.Msg.alert("提示", "请先保存订单！");
    		return;
    	}
    	var chargeWin = Ext.create({
			xtype:'UploadAttachmentWin',
			width : 800,
			height : '60%',
			businessKey:businessKey,
			businessType:businessType,
			businessTypeName:businessTypeName,
			closeAction : 'destroy'
		});
		var uploadAttachmentPanel = chargeWin.down('#uploadAttachmentPanelItemId');// 附件Panel
		uploadAttachmentPanel.setTitle('');
		chargeWin.show();
	},
	
	// 上传合同附件
	onUploadContractClick:function(){
		var form = this.lookupReference('snCustomerSalesOrderForm');
		var code = form.getForm().getValues().code;
		var contractNoOld = form.getForm().getValues().contractNoOld; // 老的合同编号
    	var businessKey = form.getForm().getValues().contractNo;
    	var businessType = "attachBizEntityType_EWHT";
    	var businessTypeName = "二网合同";
    	if (!code) {
    		Ext.Msg.alert("提示", "请先保存订单！");
    		return;
    	}
    	// TODO 订单编号改了怎么办
    	if (!businessKey) {
    		Ext.Msg.alert("提示", "合同编号为空，请先填写合同编号并保存后再进行合同附件操作！");
    		return;
    	}
    	var chargeWin = Ext.create({
			xtype:'UploadAttachmentWin',
			width : 800,
			height : '60%',
			businessKey:businessKey,
			businessType:businessType,
			businessTypeName:businessTypeName,
			closeAction : 'destroy'
		});
		var uploadAttachmentPanel = chargeWin.down('#uploadAttachmentPanelItemId');// 附件Panel
		uploadAttachmentPanel.setTitle('');
		chargeWin.show();
	},
	
	// 上传六件套附件
	onUploadLJTClick:function(){
		var form = this.lookupReference('snCustomerSalesOrderForm');
    	var businessKey = form.getForm().getValues().code;
    	var businessType = "attachBizEntityType_EWLJT";
    	var businessTypeName = "二网车辆六件套";
    	if (!businessKey) {
    		Ext.Msg.alert("提示", "请先保存订单！");
    		return;
    	}
    	var chargeWin = Ext.create({
			xtype:'UploadAttachmentWin',
			width : 800,
			height : '60%',
			businessKey:businessKey,
			businessType:businessType,
			businessTypeName:businessTypeName,
			closeAction : 'destroy'
		});
		var uploadAttachmentPanel = chargeWin.down('#uploadAttachmentPanelItemId');// 附件Panel
		uploadAttachmentPanel.setTitle('');
		chargeWin.show();
	},

});
