/*
 * File: app/view/role/RoleMangerPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.KA.KAsubmitPanelViewController', {
	extend : 'Ext.app.ViewController',
	alias : 'controller.KAsubmitPanel',
	control: {
	  "#": {
		  afterrender : 'hiddenBtnByRole'
	  }
	},
	hiddenBtnByRole:function (compent, eOpts) {
		var addBtnQK = this.getView().down('#addBtnQKItemId');
		var addBtnCXZ = this.getView().down('#addBtnCXZItemId');
		var modifyBtn = this.getView().down('#modifyBtnItemId');
//		var buyCarBtn = this.getView().down('#buyCarBtnItemId');
		
		// 删除操作
		Ext.Ajax.request({
			url : 'snCreditInfo/getCurUserRole',
			async : false,
			success : function(response) {
				if(response.status==200 && response.statusText=='OK'){
					var responseText = JSON.parse(response.responseText);
					if (responseText.isSnCustomerOrAdmin=='N') {
						addBtnQK.hide();
						addBtnCXZ.hide();
						modifyBtn.hide();
//						buyCarBtn.hide();
					}
				}
			}
		});
	},
	onQuerySalesOrder:function() {
		var queryForm = this.lookupReference('snCreditInfoSearchForm');
		var extraParams = queryForm.getForm().getValues();
	    var listGrid = this.lookupReference('snCreditInfoGridRef');
	    var dataStore = listGrid.getStore();
        dataStore.on("beforeload", function (dataStore, operation, eOpts) {
					 	Ext.apply(dataStore.proxy.extraParams, extraParams);
					});
        dataStore.loadPage(1,{"start":0,"limit":20});
        listGrid.getSelectionModel().deselectAll();
	},
	onExportSalesOrder:function() {
		
		var queryForm = this.lookupReference('snCreditInfoSearchForm');
		var extraParams = queryForm.getForm().getValues();
	    var params = 'status='+extraParams.status+'&cusName='+extraParams.cusName+'&vin='+extraParams.vin
	    				+'&creditSubmitDateStart='+extraParams.creditSubmitDateStart+'&creditSubmitDateEnd='+extraParams.creditSubmitDateEnd;
	    
	    window.location.href = 'snCreditInfo/exportSnCreditInfo?' + params;
	},
	onKAaddQK : function() {
		var win = Ext.create({
			xtype : 'KAsubmitaddWin',
			width : 1000,
			height : 500,
			closeAction : 'destroy',
		});
		win.down('#buyTypeItemId').setValue('1');
		win.setTitle('新建（全款购车）');
    	win.show();
	},
	onKAaddCXZ : function() {
		var win = Ext.create({
			xtype : 'KAsubmitaddWin',
			width : 1000,
			height : 500,
			closeAction : 'destroy',
		});
		win.down('#buyTypeItemId').setValue('2');
		win.setTitle('新建（畅享租）');
    	win.show();
	},
/*详情 on*/
	oncreditdetail: function() {
		var KAcreditdetail = Ext.create({
			xtype : 'KAsubmitEditWin',
			width : 1000,
			height : '80%',
			closeAction : 'destroy',
		});
		KAcreditdetail.show();
		
	},
/*流程 on*/
	onCredit : function() {
		var KAsubmitwin = Ext.create({
			xtype : 'KAcreditCheckWin',
			width : 1000,
			height : '500px',
			closeAction : 'destroy',
		});
		KAsubmitwin.show();
		
	},
	oncreditReview : function() {
		var KAsubmitwin = Ext.create({
			xtype : 'KAcreditReviewWin',
			width : 1000,
			height : '80%',
			closeAction : 'destroy',
		});
		KAsubmitwin.show();
		
	},
	/*流程 end*/
	onKAedit1 : function() {
		var KAsubmitwin = Ext.create({
			xtype : 'KAsubmitEditWin',
			width : 1000,
			height : '80%',
			closeAction : 'destroy',
		});
		KAsubmitwin.show();
		
	},
	onKAedit : function() {
		var snCreditInfoGrid = this.lookupReference('snCreditInfoGridRef');
    	var sel = snCreditInfoGrid.getSelectionModel().getSelection();
    	if (sel.length<=0) {
    		Ext.Msg.alert("提示",'请选择一条要修改的信息！');
    		return;
    	}
    	var data = sel[0].data;
    	var win = Ext.create({
			xtype : 'KAsubmitaddWin',
			width : 1000,
			height : 500,
			closeAction : 'destroy',
		});
    	
    	win.down('#idItemId').setValue(data.id);
    	win.down('#creditCodeItemId').setValue(data.creditCode);
//    	win.down('#snCustomerCodeItemId').setValue(data.snCustomerCode);
    	win.down('#snCustomerNameItemId').setValue(data.snCustomerName);
    	win.down('#carProductCodeItemId').setValue(data.carProductCode);
    	win.down('#carProductNameItemId').setValue(data.carProductName);
    	win.down('#cusNameItemId').setValue(data.cusName);
    	win.down('#cusIdTypeItemId').setValue(data.cusIdType);
    	win.down('#cusIdNumItemId').setValue(data.cusIdNum);
    	win.down('#birthdayItemId').setValue(data.birthday);
    	win.down('#nationalityItemId').setValue(data.nationality);
    	win.down('#cusNatureItemId').setValue(data.cusNature);
    	win.down('#remarkItemId').setValue(data.remark);
    	win.down('#buyTypeItemId').setValue(data.buyType);
    	
    	win.setTitle('修改');
    	win.show();

	},

	// 购车，提交订单
//	onBuyCar : function () {
//		var win = this.getView();
//		var snCreditInfoGrid = this.lookupReference('snCreditInfoGridRef');
//    	var sel = snCreditInfoGrid.getSelectionModel().getSelection();
//    	if (sel.length<=0) {
//    		Ext.Msg.alert("提示",'请选择一条信息！');
//    		return;
//    	}
//    	var data = sel[0].data;
//    	var creditCode = data.creditCode;
//    	if (!creditCode) {
//    		Ext.Msg.alert("提示",'没有获取到征信编号，请重新尝试！');
//    		return;
//    	}
//    	
//    	Ext.MessageBox.confirm('提示', '确定购买，提交订单?', function(btn) {
//			if (btn != 'yes') {
//				return;
//			}
//			win.mask("请稍等，正在处理中...","x-mask-loading");
//			// 删除操作
//			Ext.Ajax.request({
//				url : 'snCreditInfo/buyCar',
//				params : {
//					'creditCode' : creditCode,
//				},
//				async : false,
//				success : function(response) {
//					win.unmask();
//					if(response.status==200 && response.statusText=='OK'){
//						var responseText = JSON.parse(response.responseText);
//						if (responseText.result=='failure' && responseText.errorMsg) {
//							if (responseText.errorMsg) {
//								Ext.Msg.alert("提示", responseText.errorMsg);
//							} else {
//								Ext.Msg.alert("提示", "系统错误，操作失败！");
//							}
//						} else {
//							Ext.Msg.alert("提示",'提交成功',function(){
//		     	    			var myActiveTaskGrid = Ext.ComponentQuery.query('#myActiveTaskGrid')[0];
//		     	    			var myActiveTaskStore = myActiveTaskGrid.getStore();
//		     	    			myActiveTaskStore.loadPage(1 ,{"start":0,"limit":20});
//		     	    			var eastPanel = Ext.ComponentQuery.query("#eastPanelId")[0];
//				    	        eastPanel.removeAll();
//		     	    			win.close();
//		     	    		});
//						}
//					}else{
//                		Ext.Msg.alert("提示","系统错误,操作失败!");
//                	}
//				}
//			});
//		});
//	},
});