/*
 * File: app/view/menu/menuPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.salesOrder.SixPieceSuitWinViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.sixPieceSuitWin',
    saveSvnAddress:function(){
    	var saleOrderNoText = this.lookupReference('saleOrderNoRef');
    	var oemInfoSvnPathText = this.lookupReference('oemInfoSvnPathRef');
    	var svnAddressText = Ext.ComponentQuery.query('#svnAddressItem')[0];
    	if(null!=oemInfoSvnPathText.getValue()){
    		Ext.Ajax.request({
    			url : 'salesOrder/saveSvn',
    			params : {
    				'saleOrderNo':saleOrderNoText.getValue(),
    				'svnAddress':oemInfoSvnPathText.getValue()
    			},
                method: 'POST',	
    			success : function(data) {
    				if(data.responseText=='success'){
    					Ext.Msg.alert("提示", '保存成功！');
    					svnAddressText.setValue(oemInfoSvnPathText.getValue());
    				}
    			}
    		});
    	}
    }
});
