/*
 * File: app/model/Person.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.model.CallCarRequirement', {
    extend: 'Evcorp.model.Base',

    requires: [
        'Ext.data.field.Field',
        'Evcorp.model.Base'
    ],

    fields: [
        {
        	name:'index',
        },     
        {
            name: 'code'
        },
        {
            name: 'productName'
        },
        {
            name: 'stockQuantity'
        },
        {
            name: 'assignedQuantity'
        },
        {
            name: 'unassignedQuantity'
        },
        {
            name: 'notSubmitted'
        },
        {
            name: 'notPaid'
        },
        {
            name: 'notDelivery'
        },
        {
        	name: 'inTransit'
        },
        {
        	name: 'lackNum'
        }
    ]
});