/*
 * File: app/model/Person.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.model.CallCarDemandEfficiencyReport', {
    extend: 'Evcorp.model.Base',

    requires: [
        'Ext.data.field.Field',
        'Evcorp.model.Base'
    ],

    fields: [
        {
            name: 'code'
        },
        {
            name: 'venderName'
        },
        {
            name: 'creator'
        },
        {
            name: 'submitDate'
        },
        {
            name: 'taskName'
        },
        {
            name: 'storeDuration'
        },
        {
            name: 'csoDuration'
        },
        {
            name: 'financeDuration'
        },
        {
        	name: 'cooDuration'
        },
        {
        	name: 'ceoDuration'
        },
        {
        	name: 'tellerDuration'
        },
        {
        	name: 'submitApplyDuration'
        },
        {
        	name:'deliveryDuration'
        },
        {
        	name:'arriveDuration'
        },
        {
        	name:'totalDuration'
        },
        {
        	name:'storeWaitDuration'
        },
        {
        	name:'csoWaitDuration'
        },
        {
        	name:'financeWaitDuration'
        },
        {
        	name:'cooWaitDuration'
        },
        {
        	name:'ceoWaitDuration'
        },
        {
        	name:'tellerWaitDuration'
        },
        {
        	name:'submitApplyWaitDuration'
        },
        {
        	name:'deliveryWaitDuration'
        },
        {
        	name:'arriveWaitDuration'
        },
        {
        	name:'orderQuantity'
        },
        {
        	name:'orderAmount'
        }
        ]
});