/*
 * File: app/model/Role.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.model.ContractCarOrder', {
    extend: 'Evcorp.model.Base',

    requires: [
        'Ext.data.field.Field'
    ],
    identifier: 'negative',
    fields: [
        {
            name:'id'
        },
        {
            name:'orderNo'
        },
        {
            name:'source'
        },
        {
            name: 'status'
        },
        {
        	name:'orderCount'
        },
        {
            name: 'customerCode'
        },
        {
            name: 'customerName'
        },
        {
        	name:'customerPhone'
        },
        {
            name:'customerCid'
        },
        {
            name:'customerSex'
        },
        {
            name:'customerUserType'
        },
        {
        	name:'email'
        },
        {
        	name:'maritalStatus'
        },
        {
            name:'otherContacts'
        },
        {
            name:'education'
        },
        {
            name: 'familyNumber'
        },
        {
            name: 'address'
        },
        {
        	name:'residentialAddress'
        },
        {
            name:'residentialPhone'
        },
        {
            name:'residentialZipCode'
        },
        {
        	name:'recommendationCode'
        },
        {
        	name:'recommendationName'
        },
        {
            name:'contractCarCode'
        },
        {
            name:'contractCarName'
        },
        {
            name: 'contractCarDisplayName'
        },
        {
            name: 'carProductCode'
        },
        {
        	name:'carProductName'
        },
        {
            name:'carBrandCode'
        },
        {
            name:'carBrandName'
        },
        {
        	name:'carSeriesCode'
        },
        {
        	name:'carSeriesName'
        },
        {
        	name:'carModelCode'
        },
        {
        	name:'carModelName'
        },
        {
        	name:'carColorCode'
        },
        {
        	name:'carColorName'
        },
        {
        	name:'carInteriorCode'
        },
        {
        	name:'carInteriorName'
        },
        {
        	name:'financialPackageCode'
        },
        {
        	name:'financialPackageName'
        },
        {
        	name:'firstPay'
        },
        {
        	name:'deposit'
        },
        {
        	name:'monthlyRent'
        },
        {
        	name:'leaseTerm'
        },
        {
        	name:'expirePrice'
        },
        {
        	name:'monthlyManagementFee'
        },
        {
        	name:'intentionPayment'
        },
        {
        	name:'executeSales'
        },
        {
        	name:'contractSales'
        },
        {
        	name:'remark'
        },
        {
        	name:'creditSubmitDate'
        },
        {
        	name:'creditAccessDate'
        },
        {
        	name:'allocationCompleteDate'
        },
        {
        	name:'suppleAgreeCompleteDate'
        },
        {
        	name:'payDepositDate'
        },
        {
        	name:'commInsuranceDealDate'
        },
        {
        	name:'managerApprovalDate'
        },
        {
        	name:'replayPlanImportDate'
        },
        {
        	name:'deliveryDate'
        },
        {
        	name:'olPreSaleOrderStartDate'
        }
    ],
    proxy: {
        type: 'direct',
        api: {
            read: contractCarOrderContro.findContractCarOrderList,
//            create: contractCarOrderContro.createContractCarOrder,
//            update: contractCarOrderContro.updateContractCarOrder
        },
        reader: {
            type: 'json',
            rootProperty: 'records',
            totalProperty: 'total'
        }
    }
});