/*
 * File: app/model/Person.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.model.SalesOrderProcessSummary', {
    extend: 'Evcorp.model.Base',

    requires: [
        'Ext.data.field.Field'
    ],
    identifier: 'negative',

    fields: [
        {
            name: 'name'
        },
        {
            name: 'code'
        },
        {
            name: 'modelName'
        },
        {
            name: 'cusName'
        },
        {
            name: 'processStartTime'
        },
        {
            name: 'currentProcess'
        },
        {
            name: 'node1'
        },
        {
            name: 'node2'
        },
        {
        	name: 'node3'
        },
        {
            name: 'node4'
        },
        {
            name: 'node5'
        },
        {
        	name: 'node6'
        },
        {
            name: 'node7'
        },
        {
            name: 'node8'
        },
        {
        	name: 'node9'
        },
        {
            name: 'node10'
        },
        {
            name: 'node11'
        },
        {
        	name: 'node12'
        },
        {
        	name: 'node13'
        },
        {
            name: 'node14'
        },
        {
            name: 'node15'
        },
        {
        	name: 'node16'
        },
        {
            name: 'node17'
        },
        {
            name: 'node18'
        },
        {
        	name: 'node19'
        }
    ]
});