/*
 * File: app/model/Person.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.model.SnCreditInfo', {
    extend: 'Evcorp.model.Base',

    requires: [
        'Ext.data.field.Field'
    ],
    identifier: 'negative',

    fields: [
        {
        	name:'id',
        },     
        {
            name: 'creditCode'
        },
        {
            name: 'carProductCode'
        },
        {
            name: 'carProductName'
        },
        {
        	name: 'snCustomerCode'
        },
        {
        	name: 'snCustomerName'
        },
        {
        	name: 'cusName'
        },
        {
            name: 'cusIdType'
        },
        {
            name: 'cusIdNum'
        },
        {
        	name:'cusNature'
        },
        {
        	name:'birthday'
        },
        {
        	name:'nationality'
        },
        {
        	name:'buyType'
        },
        {
        	name:'getCarPrice'
        },
        {
        	name:'bonusAmount'
        },
        {
        	name:'creditStatus'
        },
        {
        	name:'creditSubmitPerson'
        },
        {
        	name:'creditAuditor'
        },
        {
        	name:'isCreditAudited'
        },
        {
        	name:'creditSubmitDate'
        },
        {
        	name:'estimateCreditFinishDate'
        },
        {
        	name:'creditAuditDate'
        },
        {
        	name:'remark'
        },
        {
        	name:'processInstanceId'
        },
        {
        	name:'carStockCount'
        },
        {
        	name:'creditSubmitDateStart'
        },
        {
        	name:'creditSubmitDateEnd'
        },
    ],
    proxy: {
        type: 'direct',
        api: {
            read: snCreditInfoContro.findSnCreditInfoList,
//            create: contractCarOrderContro.createContractCarOrder,
//            update: contractCarOrderContro.updateContractCarOrder
        },
        reader: {
            type: 'json',
            rootProperty: 'records',
            totalProperty: 'total'
        }
    }
});