/*
 * File: app/view/CustomerWindowViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.common.AttachmentUploadWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.attachmentUploadWindowC',
	control : {
		'#' : {
			afterrender : 'onViewShow',
		}
	},
	onViewShow:function(){
    	var form = this.getView().down('form');
    	var businessType = form.getForm().getValues().bizEntityType;
    	var typeStore = this.getView().getViewModel().getStore('attachmentTypeStore');
    	typeStore.load({params:{type:businessType}});
	},
    onAttachmentUploadClick : function() {
		var attachmentForm = this.lookupReference('attachmentForm');
//		var description = attachmentForm.getForm().getValues().description;
//		var bizEntityType = attachmentForm.getForm().getValues().attachBizTypeCode;
//    	var bizEntityCode = attachmentForm.getForm().getValues().bizEntityCode;
//    	var attachBizType = attachmentForm.getForm().getValues().attachBizType;
		var gridStore = Ext.ComponentQuery.query('#attachmentGridId')[0]
		.getStore();
		var isValid=attachmentForm.getForm().isValid();
    	var win = this.getView();
    	if(isValid){
    		attachmentForm.submit({
//    			params : {
//    				'bizEntityType' : bizEntityType,
//    				'bizEntityCode' : bizEntityCode,
//    				'attachBizType' : attachBizType,
//    				'description' : description
//    			},
    			waitMsg : '附件正在上传，请耐心等待....',
    			success : function(form, action) {
    				Ext.Msg.alert('提示','附件上传成功',function(){
    					gridStore.reload();
    					win.close();
    				});
    			},
    			failure : function(form, action) {
    				Ext.Msg.alert('提示',action.result.info);
    			}

    		});
    	}
	}
});


