/*
 * File: app/view/menu/menuPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.common.CarProductListWinViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.carProductsWin',
    onChoiceClick:function(){
    		  var grid = this.lookupReference('carProductGrid');
    		  var win = this.getView();
     		  var seletedGird = grid.getSelectionModel().getSelection();
    		  var propertyText = Ext.ComponentQuery.query('#carProductItemId')[0];
    		  propertyText.setValue(seletedGird[0].get('name'));
    		  var propertyText = Ext.ComponentQuery.query('#carProductCode')[0];
    		  propertyText.setValue(seletedGird[0].get('code'));
    		  
    		  var propertyText = Ext.ComponentQuery.query('#leaseTerm')[0];
    		  propertyText.setValue(seletedGird[0].get('leaseTerm'));
    		  var propertyText = Ext.ComponentQuery.query('#deposit')[0];
    		  propertyText.setValue(seletedGird[0].get('deposit'));
    		  var propertyText = Ext.ComponentQuery.query('#monthlyManagementFee')[0];
    		  propertyText.setValue(seletedGird[0].get('monthlyManagementFee'));
    		  var propertyText = Ext.ComponentQuery.query('#monthlyRent')[0];
    		  propertyText.setValue(seletedGird[0].get('monthlyRent'));
    		  var propertyText = Ext.ComponentQuery.query('#expirePrice')[0];
    		  propertyText.setValue(seletedGird[0].get('expirePrice'));
    		  var propertyText = Ext.ComponentQuery.query('#liftTheFare')[0];
    		  propertyText.setValue(seletedGird[0].get('liftTheFare'));
    		  var propertyText = Ext.ComponentQuery.query('#outOfRangFee')[0];
    		  propertyText.setValue(seletedGird[0].get('outOfRangFee'));
    		  win.close();
    		
    	  }
    ,
    onQueryClick:function(){
    	var carSearch = this.lookupReference('carProductField');
    	var carProductGrid = this.lookupReference('carProductsGrid');
    	var extraParams = {
    			name : carSearch.getValue()
    			};
    	var carProductStore = carProductGrid.getStore();
    	carProductStore.on("beforeload", function(carProductStore,
				operation, eOpts) {
			Ext.apply(carProductStore.proxy.extraParams,
					extraParams);
		});
    	carProductStore.loadPage(1, {
			"start" : 0,
			"limit" : 20
		});
    	
    },
    onContractCarInfoSelectCar:function(){
		  var grid = this.lookupReference('carProductsGrid');
		  var win = this.getView();
 		  var seletedGird = grid.getSelectionModel().getSelection();
 			if (seletedGird.length == 0) {
 				Ext.Msg.alert("提示", '请选择一条记录');
 				return;
 			} else{
 				var productCode=seletedGird[0].data.code;
 				var productName=seletedGird[0].data.name;
 				var brandCode=seletedGird[0].data.carBrandCode;
 				var brandName=seletedGird[0].data.brandName;
 				var seriesCode=seletedGird[0].data.carSeriesCode;
 				var seriesName=seletedGird[0].data.seriesName;
 				var modelCode=seletedGird[0].data.carModelCode;
 				var modelName=seletedGird[0].data.modelName;
 				var productCodeText=Ext.getCmp('contracCarWinProductCode');
 				var productNameText=Ext.getCmp('contracCarWinProductName');
 				var brandCodeText=Ext.getCmp('contracCarWinBrandCode');
 				var brandNameText=Ext.getCmp('contracCarWinBrandName');
 				var seriesCodeText=Ext.getCmp('contracCarWinSeriesCode');
 				var seriesNameText=Ext.getCmp('contracCarWinSeriesName');
 				var modelCodeText=Ext.getCmp('contracCarWinModelCode');
 				var modelNameText=Ext.getCmp('contracCarWinModelName');
 				productCodeText.setValue(productCode);
 				productNameText.setValue(productName);
 				brandCodeText.setValue(brandCode);
 				brandNameText.setValue(brandName);
 				seriesCodeText.setValue(seriesCode);
 				seriesNameText.setValue(seriesName);
 				modelCodeText.setValue(modelCode);
 				modelNameText.setValue(modelName);
 			}
 			win.close();
    },
    onContractCarMGTSelectCar:function(){
    	var grid = this.lookupReference('carProductsGrid');
		  var win = this.getView();
		  var seletedGird = grid.getSelectionModel().getSelection();
			if (seletedGird.length == 0) {
				Ext.Msg.alert("提示", '请选择一条记录');
				return;
			} else{
				var productCode=seletedGird[0].data.code;
				var productName=seletedGird[0].data.name;
				  var productNameText = Ext.ComponentQuery.query('#contractCarMGTProductName')[0];
				  productNameText.setValue(productName);
				  var productCodeText = Ext.ComponentQuery.query('#contractCarMGTProductCode')[0];
				  productCodeText.setValue(productCode);
			}
			win.close();
    },
    onCarStockSelectCar:function(){
    	var grid = this.lookupReference('carProductsGrid');
		  var win = this.getView();
		  var seletedGird = grid.getSelectionModel().getSelection();
			if (seletedGird.length == 0) {
				Ext.Msg.alert("提示", '请选择一条记录');
				return;
			} else{
				var productCode=seletedGird[0].data.code;
				var productName=seletedGird[0].data.name;
				var carProductCodeText = Ext.ComponentQuery.query("stockInListWin #carProductCodeItemId")[0];
				carProductCodeText.setValue(productCode);
				var carProductNameText = Ext.ComponentQuery.query("stockInListWin #carProductNameItemId")[0];
				carProductNameText.setValue(productName);
			}
			win.close();
    },
    onSalesOrderSelectCar:function(){
    	var grid = this.lookupReference('carProductsGrid');
		  var win = this.getView();
		  var seletedGird = grid.getSelectionModel().getSelection();
			if (seletedGird.length == 0) {
				Ext.Msg.alert("提示", '请选择一条记录');
				return;
			} else{
				var productCode=seletedGird[0].data.code;
				var productName=seletedGird[0].data.name;
				var directivePrice=seletedGird[0].data.directivePrice;
				  var productNameText = Ext.ComponentQuery.query('#salesOrderProductName')[0];
				  productNameText.setValue(productName);
				  var productCodeText = Ext.ComponentQuery.query('#salesOrderProductCode')[0];
				  productCodeText.setValue(productCode);
				  var directivePriceText = Ext.ComponentQuery.query('#salesOrderDirectivePriceItem')[0]; //销售指导价
				  directivePriceText.setValue(directivePrice);
			}
			win.close();
    },
    onSnCustomerSalesOrderSelectCar:function(){
    	var grid = this.lookupReference('carProductsGrid');
		  var win = this.getView();
		  var seletedGird = grid.getSelectionModel().getSelection();
			if (seletedGird.length == 0) {
				Ext.Msg.alert("提示", '请选择一条记录');
				return;
			} else{
				var productCode=seletedGird[0].data.code;
				var productName=seletedGird[0].data.name;
				var productCodeText = Ext.ComponentQuery.query('KAsubmitaddWin #carProductCodeItemId')[0];
				productCodeText.setValue(productCode);
				var productNameText = Ext.ComponentQuery.query('KAsubmitaddWin #productNameItemId')[0];
				productNameText.setValue(productName);
			}
			win.close();
  },
  onSnCustomerSalesOrderEditSelectCar:function(){
	  	var grid = this.lookupReference('carProductsGrid');
		var win = this.getView();
		var seletedGird = grid.getSelectionModel().getSelection();
		if (seletedGird.length == 0) {
			Ext.Msg.alert("提示", '请选择一条记录');
			return;
		} else {
			
			var productCode = seletedGird[0].data.code;
			var productCodeText = Ext.ComponentQuery.query('KAsubmitEditWin #carProductCodeItemId')[0];
			if (productCodeText.value && productCodeText.value!=productCode) {
				Ext.MessageBox.confirm('提示', '切换产品后原有的配车信息将自动清除，确定切换产品?', function(btn) {
					if (btn != 'yes') {
						return;
					}
					
					// 清除配车信息
					var vin = Ext.ComponentQuery.query('KAsubmitEditWin #vinItemId')[0];
					var carEngineNo = Ext.ComponentQuery.query('KAsubmitEditWin #carEngineNoItemId')[0];
					var storageCode = Ext.ComponentQuery.query('KAsubmitEditWin #storageCodeItemId')[0];
					var slocCode = Ext.ComponentQuery.query('KAsubmitEditWin #slocCodeItemId')[0];
					var dispatchedDate = Ext.ComponentQuery.query('KAsubmitEditWin #dispatchedDateItemId')[0];
					vin.setValue('');
					carEngineNo.setValue('');
					storageCode.setValue('');
					slocCode.setValue('');
					dispatchedDate.setValue('');
					
					// 写入产品信息
					var productName = seletedGird[0].data.name;
					var directivePrice = seletedGird[0].data.directivePrice;
					productCodeText.setValue(productCode);
					var productNameText = Ext.ComponentQuery.query('KAsubmitEditWin #productNameItemId')[0];
					productNameText.setValue(productName);
					var directivePriceText = Ext.ComponentQuery.query('KAsubmitEditWin #directivePriceItemId')[0];
					directivePriceText.setValue(directivePrice);
					
					win.close();
				});
			} else {
				// 写入产品信息
				var productName = seletedGird[0].data.name;
				var directivePrice = seletedGird[0].data.directivePrice;
				productCodeText.setValue(productCode);
				var productNameText = Ext.ComponentQuery.query('KAsubmitEditWin #productNameItemId')[0];
				productNameText.setValue(productName);
				var directivePriceText = Ext.ComponentQuery.query('KAsubmitEditWin #directivePriceItemId')[0];
				directivePriceText.setValue(directivePrice);
				
				win.close();
			}
		}
	},
	
	onSnCreditInfoSelectCar:function(){
    	var grid = this.lookupReference('carProductsGrid');
		  var win = this.getView();
		  var seletedGird = grid.getSelectionModel().getSelection();
			if (seletedGird.length == 0) {
				Ext.Msg.alert("提示", '请选择一条记录');
				return;
			} else{
				var productCode=seletedGird[0].data.code;
				var productName=seletedGird[0].data.name;
				var productCodeText = Ext.ComponentQuery.query('KAsubmitaddWin #carProductCodeItemId')[0];
				productCodeText.setValue(productCode);
				var productNameText = Ext.ComponentQuery.query('KAsubmitaddWin #carProductNameItemId')[0];
				productNameText.setValue(productName);
			}
			win.close();
  },
});
