/*
 * File: app/view/menu/menuPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.common.CarStockWinViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.carStockWin',
    onChoiceClick:function(){
    		  var grid = this.lookupReference('carProductGrid');
    		  var win = this.getView();
     		  var seletedGird = grid.getSelectionModel().getSelection();
    		  var propertyText = Ext.ComponentQuery.query('#carProductItemId')[0];
    		  propertyText.setValue(seletedGird[0].get('name'));
    		  var propertyText = Ext.ComponentQuery.query('#carProductCode')[0];
    		  propertyText.setValue(seletedGird[0].get('code'));
    		  
    		  var propertyText = Ext.ComponentQuery.query('#leaseTerm')[0];
    		  propertyText.setValue(seletedGird[0].get('leaseTerm'));
    		  var propertyText = Ext.ComponentQuery.query('#deposit')[0];
    		  propertyText.setValue(seletedGird[0].get('deposit'));
    		  var propertyText = Ext.ComponentQuery.query('#monthlyManagementFee')[0];
    		  propertyText.setValue(seletedGird[0].get('monthlyManagementFee'));
    		  var propertyText = Ext.ComponentQuery.query('#monthlyRent')[0];
    		  propertyText.setValue(seletedGird[0].get('monthlyRent'));
    		  var propertyText = Ext.ComponentQuery.query('#expirePrice')[0];
    		  propertyText.setValue(seletedGird[0].get('expirePrice'));
    		  var propertyText = Ext.ComponentQuery.query('#liftTheFare')[0];
    		  propertyText.setValue(seletedGird[0].get('liftTheFare'));
    		  var propertyText = Ext.ComponentQuery.query('#outOfRangFee')[0];
    		  propertyText.setValue(seletedGird[0].get('outOfRangFee'));
    		  win.close();
    		
    	  }
    ,
    onQueryClick:function(){
    	var vinRef = this.lookupReference('vinRef');
    	var carProductField = this.lookupReference('carProductField');
    	var carStocksGridRef = this.lookupReference('carStocksGridRef');
    	var extraParams = {
    			productCode:carProductField.getValue(),
    			vin : vinRef.getValue()
    			};
    	var carStockStore = carStocksGridRef.getStore();
    	carStockStore.on("beforeload", function(carProductStore,
				operation, eOpts) {
			Ext.apply(carStockStore.proxy.extraParams,
					extraParams);
		});
    	carStockStore.loadPage(1, {
			"start" : 0,
			"limit" : 20
		});
    	
    },
    onContractCarInfoSelectCar:function(){
		  var grid = this.lookupReference('carProductsGrid');
		  var win = this.getView();
 		  var seletedGird = grid.getSelectionModel().getSelection();
 			if (seletedGird.length == 0) {
 				Ext.Msg.alert("提示", '请选择一条记录');
 				return;
 			} else{
 				var productCode=seletedGird[0].data.code;
 				var productName=seletedGird[0].data.name;
 				var brandCode=seletedGird[0].data.carBrandCode;
 				var brandName=seletedGird[0].data.brandName;
 				var seriesCode=seletedGird[0].data.carSeriesCode;
 				var seriesName=seletedGird[0].data.seriesName;
 				var modelCode=seletedGird[0].data.carModelCode;
 				var modelName=seletedGird[0].data.modelName;
 				var productCodeText=Ext.getCmp('contracCarWinProductCode');
 				var productNameText=Ext.getCmp('contracCarWinProductName');
 				var brandCodeText=Ext.getCmp('contracCarWinBrandCode');
 				var brandNameText=Ext.getCmp('contracCarWinBrandName');
 				var seriesCodeText=Ext.getCmp('contracCarWinSeriesCode');
 				var seriesNameText=Ext.getCmp('contracCarWinSeriesName');
 				var modelCodeText=Ext.getCmp('contracCarWinModelCode');
 				var modelNameText=Ext.getCmp('contracCarWinModelName');
 				productCodeText.setValue(productCode);
 				productNameText.setValue(productName);
 				brandCodeText.setValue(brandCode);
 				brandNameText.setValue(brandName);
 				seriesCodeText.setValue(seriesCode);
 				seriesNameText.setValue(seriesName);
 				modelCodeText.setValue(modelCode);
 				modelNameText.setValue(modelName);
 			}
 			win.close();
    },
    onContractCarMGTSelectCar:function(){
    	var grid = this.lookupReference('carProductsGrid');
		  var win = this.getView();
		  var seletedGird = grid.getSelectionModel().getSelection();
			if (seletedGird.length == 0) {
				Ext.Msg.alert("提示", '请选择一条记录');
				return;
			} else{
				var productCode=seletedGird[0].data.code;
				var productName=seletedGird[0].data.name;
				  var productNameText = Ext.ComponentQuery.query('#contractCarMGTProductName')[0];
				  productNameText.setValue(productName);
				  var productCodeText = Ext.ComponentQuery.query('#contractCarMGTProductCode')[0];
				  productCodeText.setValue(productCode);
			}
			win.close();
    },
    onCarStockSelectCar:function(){
    	var grid = this.lookupReference('carProductsGrid');
		  var win = this.getView();
		  var seletedGird = grid.getSelectionModel().getSelection();
			if (seletedGird.length == 0) {
				Ext.Msg.alert("提示", '请选择一条记录');
				return;
			} else{
				var productCode=seletedGird[0].data.code;
				var carProductCodeText = Ext.ComponentQuery.query("stockInListWin #carProductCodeItemId")[0];
				carProductCodeText.setValue(productCode);
			}
			win.close();
    },
    onSalesOrderPcClick:function(){
    	var grid = this.lookupReference('carStocksGridRef');
		  var win = this.getView();
		  var seletedGird = grid.getSelectionModel().getSelection();
			if (seletedGird.length == 0) {
				Ext.Msg.alert("提示", '请选择一条记录');
				return;
			}else{
				var salesOrderGrid = Ext.ComponentQuery.query('#salesOrderGridId')[0];
				var salesOrderStore=null;
				if(null!=salesOrderGrid){
					salesOrderStore=salesOrderGrid.getStore();
				}
				
				var carStockWinSaleOrderNoText = this.lookupReference('carStockWinSaleOrderNoRef');
				var vinText = Ext.ComponentQuery.query('#salesOrderVinItem')[0];
				var dispatchedDateText = Ext.ComponentQuery.query('#sdDispatchedDateItem')[0];
				var storageCodeText = Ext.ComponentQuery.query('#sdStorageCodeItem')[0];
				var slocCodeText = Ext.ComponentQuery.query('#sdSlocCodeItem')[0];
				var carStockId=seletedGird[0].data.carStockId;
				Ext.Ajax.request({
    				url : 'salesOrder/saveDispatched',
    				params : {
    					'carStockId' : carStockId,
    					'saleOrderNo':carStockWinSaleOrderNoText.getValue()
    				},
    	            method: 'POST',	
    				success : function(data) {
    					if(data.responseText=='success'){
    						Ext.Msg.alert("提示", '配车成功！');
    						var vin=seletedGird[0].data.vin;
    						var stock=seletedGird[0].data.stock;
    						var stockPositionNo=seletedGird[0].data.stockPositionNo;
    						vinText.setValue(vin);
    						storageCodeText.setValue(stock);
    						slocCodeText.setValue(stockPositionNo);
    						dispatchedDateText.setValue(new Date());
    						if(salesOrderStore!=null){
    							salesOrderStore.reload();
    						}
    						win.close();
    					}
    				}
    			});
			}
    },
    onSnCustomerSelectCar:function(){
    	var grid = this.lookupReference('carStocksGridRef');
		  var win = this.getView();
		  var seletedGird = grid.getSelectionModel().getSelection();
			if (seletedGird.length == 0) {
				Ext.Msg.alert("提示", '请选择一条记录');
				return;
			} else{
				var vin=seletedGird[0].data.vin;
				var carEngineNo=seletedGird[0].data.carEngineNo;
				var storageCode=seletedGird[0].data.stock;
				var slocCode=seletedGird[0].data.stockPositionNo;
				var vinText = Ext.ComponentQuery.query('KAsubmitEditWin #vinItemId')[0];
				vinText.setValue(vin);
				var carEngineNoText = Ext.ComponentQuery.query('KAsubmitEditWin #carEngineNoItemId')[0];
				carEngineNoText.setValue(carEngineNo);
				var storageCodeText = Ext.ComponentQuery.query('KAsubmitEditWin #storageCodeItemId')[0];
				storageCodeText.setValue(storageCode);
				var slocCodeText = Ext.ComponentQuery.query('KAsubmitEditWin #slocCodeItemId')[0];
				slocCodeText.setValue(slocCode);
				var dispatchedDateText = Ext.ComponentQuery.query('KAsubmitEditWin #dispatchedDateItemId')[0];
				dispatchedDateText.setValue('');
			}
			win.close();
    },
});
