/*
 * File: app/view/role/UserMangerPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.user.UserMangerPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.usermangerpanel',

    requires: [
        'Evcorp.view.user.UserMangerPanelViewModel',
        'Evcorp.view.user.UserMangerPanelViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox'
    ],
    
    controller:'usermangerpanelContr',
    viewModel: {
        type: 'usermangerpanel'
    },
    itemId:'userManager',
    referenceHolder: true,
    closable: true,
    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'gridpanel',
            viewConfig: {
                enableTextSelection: true
             },
            bind:'{usesrs}',
            reference: 'auUserGrid',
            flex: 1,
            title: '列表',
            columns: [
	              {
	                  xtype: 'gridcolumn',
	                  dataIndex: 'id',
	                  hidden:true
	              },
	              {
	                  xtype: 'gridcolumn',
	                  dataIndex: 'version',
	                  text:'版本',
	                  hidden:true
	              },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'username',
                    width: '20%',
                    text: '用户名'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'realname',
                    width: '20%',
                    text: '姓名'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'email',
                    width: '20%',
                    text: 'Email'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'mobile',
                    width: '20%',
                    text: '手机'
                },
                /*{
                    xtype: 'gridcolumn',
                    text: '密码',
                    dataIndex: 'password'
                    
                },*/
                {
                    xtype: 'booleancolumn',
                    text: '是否可用',
                    dataIndex: 'valid',
                    width: '20%',
                    trueText: '是',
                    falseText: '否'
                   
                },
                {
                    xtype: 'gridcolumn',
                    text: '创建时间',
                    width: '30%',
                    dataIndex: 'createdate'
                /*    renderer:function(value){ 
                    	if(value==null){
                    		return "";
                    	}else{
                    		return	Ext.Date.format(new Date(value), 'Y-m-d H:i:s')
                    	}
                    }*/
                },
                {
                    xtype: 'gridcolumn',
                    text: '最后登录时间',
                    dataIndex: 'lastLoginTime',
                    hidden:true
                }
            ],
            viewConfig: {
                enableTextSelection: true
             },
            /*viewConfig:{
					listeners:{
							refresh:function(){
								var rec=this.store.getAt(0);
								if(rec){
									this.select(rec);
								}
							}
					}
				},*/
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '添加',
                            icon:'images/role_add.png',
                            handler: 'onAddClick'
                        },
                        
                        {
                            xtype: 'button',
                            text: '刷新',
                            icon:'images/refresh.png',
                            handler: 'onRefreshClick'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '用户名',
                            labelWidth: 50,
                            width: 130,
                            name:'name'
                        },
                        {
                            xtype: 'button',
                            text: '查询',
                            iconCls: 'common-icon-serach',
                            handler: 'onQueryClick'
                        }
                    ]
                },
                {
			        xtype: 'pagingtoolbar',
			        dock: 'bottom',
			        bind: {
				        store: '{usesrs}'
				    },
			        displayInfo : true,
					displayMsg:'显示 {0} - {1}条记录，总共 {2}条记录',
					emptyMsg:'暂无数据',
					beforePageText:'页数',
					afterPageText:'总共{0}页',
					firstText:'第一页',
					prevText:'上一页',
					nextText:'下一页',
					lastText:'最后一页',
					width:'100%',
					emptyMsg : '没有记录'
			    }
            ]
        },
        {
            xtype: 'form',
            flex: 1,
            layout: 'auto',
            bodyPadding: 10,
            reference: 'auUserForm',
            api: {
               submit: auUserContro.updateUser
		    },
		    paramsAsHash: true,
		    animCollapse: false,
            collapseDirection: 'left',
            collapsed: false,
            collapsible: true,
            titleCollapse: false,
            title: '详细信息',
            items: [
                {
                    xtype: 'hidden',
                    fieldLabel: 'id',
                    name:'id',
                    bind:'{auUserGrid.selection.id}'
                },
                {
                    xtype: 'hidden',
                    fieldLabel: '版本号',
                    name:'version',
                    bind:'{auUserGrid.selection.version}'
                },
                {
                   xtype:'textfield',
                   fieldLabel: '用户名',
                   name:'username',
                   bind:'{auUserGrid.selection.username}',
                   allowBlank:false
                },
                {
                    xtype: 'textfield',
                    fieldLabel: '姓名',
                    name:'realname',
                    bind:'{auUserGrid.selection.realname}',
                    allowBlank:false
                },
                {
                    xtype: 'textfield',
                    fieldLabel: '密码',
                    inputType: 'password',
                    name:'password',
                    bind:'{auUserGrid.selection.password}',
                    allowBlank:false
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Email',
                    name:'email',
                    bind:'{auUserGrid.selection.email}'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: '手机',
                    name:'mobile',
                    bind:'{auUserGrid.selection.mobile}'
                },
                {
                	xtype: 'checkbox',
                    fieldLabel: '是否可用',
                    name:'valid',
                    checked:true,
                    bind:'{auUserGrid.selection.valid}',
                    inputValue:'true'
                },
                {
                    xtype: 'hidden',
                    fieldLabel: '创建时间',
                    name:'createDate',
                    bind:'{auUserGrid.selection.createDate}'
                },
                {
                    xtype: 'hidden',
                    fieldLabel: '最后登录时间',
                    name:'lastLoginTime',
                    bind:'{auUserGrid.selection.lastlogintime}'
                }
                
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: '保存',
                            icon:'images/save.png',
                            handler: 'onModifyClick'
                        },
                        {
                        	xtype: 'button',
                        	text: '修改用户角色',
                        	icon:'images/update.png',
                        	handler: 'onModifyUserRoleClick'
                        }
                    ]
                }
            ]
        }
    ]

});