/*
 * File: app/view/role/RoleMangerPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.orderList.OrderListPanel',
		{
			extend : 'Ext.panel.Panel',
			alias : 'widget.orderlistpanel',
			requires : [ 'Evcorp.view.orderList.OrderListPanelViewController',
					'Evcorp.view.orderList.OrderListPanelViewModel',
					'Ext.grid.plugin.CellEditing',
					'Ext.grid.Panel', 'Ext.tab.Panel',
					'Ext.grid.column.Column', 'Ext.grid.View',
					'Ext.toolbar.Toolbar', 'Ext.button.Button',
					'Ext.toolbar.Fill', 'Ext.form.Panel',
					'Ext.grid.column.Check',
					'Ext.form.field.ComboBox', 'Ext.form.DateField' ],

			controller : 'orderlistpanel',
			viewModel : {
				type : 'orderlistpanel'
			},
			referenceHolder : true,
			itemId : 'orderListPanel',
			closable : true,
			layout : {
				type : 'border',
				align : 'stretch'
			},
			border : false,
			items : [ {
				xtype : 'container',
				flex : 1,
				region:'center',
				layout : {
					type : 'vbox',
					align : 'stretch'
				},
				buttonAlign:'center',
				items : [ 				          
				          {
					xtype : 'form',
					heigth : 100,
					bodyPadding : 10,
					reference : 'contractCarOrderQueryForm',
					layout : {
						type : 'hbox',
						align : 'stretch'
					},
					buttonAlign:'center',
					items : [ {
						xtype : 'container',
						defaults : {
//							width : 300,
//							labelWidth:70,
							margin:'5 10'
						},
						items : [ {
							xtype : 'textfield',
							name : 'customerName',
							reference : 'customerNameRef',
							fieldLabel : '姓名',
							width:200,
							labelWidth:70,
						},{
							xtype : 'textfield',
							name : 'customerPhone',
							fieldLabel : '手机号码',
							width:200,
							labelWidth:70,
							
						},]
					}, {
						xtype : 'container',
						defaults : {
							width : 200,
							labelWidth:70,
							margin:'5 10'
						},
						items : [ {
							xtype : 'textfield',
							name : 'recommendationName',
							fieldLabel : '来源'
						},{
							xtype : 'combobox',
							fieldLabel : '订单状态',
							name : 'status',
							itemId : 'statusSearchItemId',
							labelWidth : 70,
							width : 200,
							valueField : "code",
							displayField : "nameCn",
							queryModel : 'local',
							bind : {
								store : '{contractCarOrderStatusStore}',
							},
							forceSelection : true,
							editable : false,
							allowBlank : false,
						},  ]
					},
					{

						xtype : 'container',
						defaults : {
							width : 200,
							labelWidth:70,
							margin:'5 10'
						},
						items : [ {
							xtype : 'textfield',
							name : 'customerName',
							reference : 'customerNameRef',
							fieldLabel : '订单编号'
						},{
							xtype : 'combobox',
							fieldLabel : '执行销售',
							name : 'executeSales',
							itemId : 'executeSalesSearchItemId',
							labelWidth : 70,
							width : 200,
							valueField : "id",
							displayField : "username",
							queryModel : 'local',
							forceSelection : true,
							editable : false,
							allowBlank : false,
							store : Ext.create('Ext.data.Store', {
												autoLoad : true,
												fields : [ 'id', 'username' ],
												proxy : {
													type: 'direct',
													directFn : auUserContro.findUsersByRole,
									        		extraParams: {
									        			roleCode : 'sales'
									        		}
												}
											}),
						} ]
					
					},
					{


						xtype : 'container',
						defaults : {
							width : 200,
							labelWidth:70,
							margin:'5 10'
						},
						items : [ {
							xtype : 'datefield',
							name : 'customerName',
							reference : 'customerNameRef',
							fieldLabel : '创建时间'
						},{
							xtype : 'textfield',
							fieldLabel : 'VIN',
							name : 'executeSales',
							itemId : 'executeSalesSearchItemId',
							labelWidth : 70,
							width : 200,
							valueField : "id",
							displayField : "username",
							queryModel : 'local',
							forceSelection : true,
							editable : false,
							allowBlank : false,
						} ]
					
					
					},
					{


						xtype : 'container',
						defaults : {
							width : 200,
							labelWidth:70,
							margin:'5 10'
						},
						items : [ {
							xtype : 'textfield',
							name : 'customerName',
							reference : 'customerNameRef',
							fieldLabel : '产品名称'
						},
						]
					
					
					},
					],
					dockedItems : [ {
						xtype : 'toolbar',
						flex : 1,
						dock : 'bottom',
						buttonAlign:'left',
						items : [ 
						{
							xtype : 'button',
							text : '查询',
							iconCls : 'common-icon-serach',
							handler : 'onContractCarOrderQueryClick'
						},{
			            	xtype: 'button',
			                text: '重置查询条件',
			                scale:'small',
			                iconCls: 'common-icon-serach',
			                handler:'onResetQuery',
			            } , {
							xtype : 'button',
							text : '新建订单',
							iconCls : 'common-icon-add',
							handler : 'onContractCarOrderAddClick'
						},{
							xtype : 'tbfill'
						}]
					} ]
				}, {
					flex : 1,
					// title : "<div align='center'>合约车订单</div>",
					border : false,
                    viewConfig: { enableTextSelection: true },
					xtype : 'gridpanel',
					width : '100%',
					itemId: 'contractCarOrderGrid',
					reference: 'contractCarOrderGrid',
					bind : '{contractCarOrderListStore}',
					listeners:{
						select:'onContractCarOrderGridSelect'
					},
					autoScroll : true,
					columns : [ {
						dataIndex: 'id',
						hidden:true
					}, {
						dataIndex : 'contractCarCode',
						hidden:true
					}, {
						dataIndex : 'contractCarDisplayName',
						hidden:true
					},{
						dataIndex: 'contractSales',
						hidden:true
					},{
						dataIndex: 'olPreSaleOrderNo',
						hidden:true
					},{
						dataIndex: 'leaseTerm',
						hidden:true
					},{
						dataIndex: 'deposit',
						hidden:true
					},{
						dataIndex: 'monthlyManagementFee',
						hidden:true
					},{
						dataIndex: 'monthlyRent',
						hidden:true
					},{
						dataIndex: 'expirePrice',
						hidden:true
					},{
						dataIndex: 'liftTheFare',
						hidden:true
					},{
						dataIndex: 'outOfRangFee',
						hidden:true
					},{
						dataIndex: 'customerUserType',
						hidden:true
					},{
						text : '订单编号',
						width:190,
						dataIndex : 'orderNo',
						align : 'center'
					}, {
						text : '客户编号',
						width:100,
						dataIndex : 'customerCode',
						align : 'center'
					}, {
						text : '姓名',
						width:100,
						dataIndex : 'customerName',
						align : 'center'
					}, {
						text : '联系电话',
						width:110,
						dataIndex : 'customerPhone',
						align : 'center',
					}, {
						text : '身份证号',
						width:156,
						dataIndex : 'customerCid',
						align : 'center'
					}, {
						text : '产品名称',
						width:400,
						dataIndex : 'contractCarName',
						align : 'center'
					}, {
						text : 'VIN',
						width:200,
						dataIndex : 'customerPhone',
						align : 'center'
					}, {
						text : '执行销售',
						width:80,
						dataIndex : 'executeSales',
						align : 'center',
						renderer: function (val){
                        	if(val != null && val != ''){
                        		var gridStore = this.up('panel').down('#executeSalesSearchItemId').getStore();
//                        		var gridStore = this.up('panel').up().up().down('#executeSales').getStore();
                        		return gridStore.findRecord('id', val).data.username;
                            }else{
                            	return '';
                            }
                        }

					}, {
						text : '创建日期',
						width:100,
						dataIndex : 'createDate',
						align : 'center',
						renderer: function (val){
							if (val) {
								return Ext.Date.format(new Date(val), 'Y-m-d');
							} else {
								return "";
							}
						}

					}, {
						text : '合同签订日期',
						width:120,
						dataIndex : 'olPreSaleOrderSignDate',
						align : 'center',
						renderer: function (val){
							if (val) {
								return Ext.Date.format(new Date(val), 'Y-m-d');
							} else {
								return "";
							}
						}
					}, {
						text : '是否通过征信',
						width:110,
						dataIndex : 'creditAccessDate',
						align : 'center',
						renderer: function (val){
							if (val) {
								return '是';
							} else {
								return '否';
							}
                        }
					}, {
						text : '数量',
						dataIndex : 'orderCount',
						align : 'center'
					}, {
						text : '渠道',
						dataIndex : 'recommendationName',
						align : 'center'
					}, {
						text : '订单状态',
						width:130,
						dataIndex : 'status',
						align : 'center',
						renderer: function (val){
                        	if(val != null && val != ''){
                        		var gridStore = this.up('panel').down('#statusSearchItemId').getStore();
//                        		var gridStore = this.up('panel').up().up().down('#status').getStore();
                        		return gridStore.findRecord('code', val).data.nameCn;
                            }else{
                            	return '';
                            }
                        }
					}, ],
					dockedItems: [ {
      			        xtype: 'pagingtoolbar',
      			        dock: 'bottom',
      			        bind: {
      				        store: '{contractCarOrderListStore}'
      				    },
      			        displayInfo : true,
      					displayMsg:'显示 {0} - {1}条记录，总共 {2}条记录',
      					emptyMsg:'暂无数据',
      					beforePageText:'页数',
      					afterPageText:'总共{0}页',
      					firstText:'第一页',
      					prevText:'上一页',
      					nextText:'下一页',
      					lastText:'最后一页',
      					width:'100%',
      					emptyMsg : '没有记录'
      			    } ]
				} ]
			}, 
			{
				region : 'east',
				xtype:'panel',
				title : '<div align="center">合约车订单修改</div>',
				border : true,
				flex : 1.5,
				collapseDirection : 'left',
				collapsed : false,
				collapsible : true,
				autoScroll : true,
				items : [
				         {
								buttonAlign:'center',
								xtype:'form',
								width:'100%',
								border : false,
								padding:15,
								reference : 'contractCarOrderDetailForm',
								itemId : 'contractCarOrderDetailForm',
								api: {
									submit: 'contractCarOrderContro.saveOrUpdateContractCarOrder'
								},
								
								items : [

										{
											flex : 1,
											xtype : 'fieldset',
											align : 'left',
											collapsed : false,
											collapsible : true,
											autoScroll : true,
											reference : 'contractCarOrderDetailFieldset',
											layout : 'vbox',
											collapseDirection : 'top',
											title : "订单",
											items : [
													{
														xtype : 'container',
														layout : 'hbox',
														margin : '0 0',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},

														items : [
																{
																	xtype : 'hidden',
																	fieldLabel : 'id',
																	name : 'id',
																	bind : '{contractCarOrderGrid.selection.id}'
																},
																{
																	xtype : 'textfield',
																	fieldLabel : '编号',
																	name : 'orderNo',
																	labelWidth : 70,
																	width : 200,
																	readOnly : true,
																	bind : '{contractCarOrderGrid.selection.orderNo}',
																	margin : '0 0 0 20'
																},
																{
																	xtype : 'combobox',
																	fieldLabel : '执行销售',
																	name : 'executeSales',
																	labelWidth : 70,
																	width : 200,
																	margin : '0 0 0 20',
																	valueField : "id",
																	displayField : "username",
																	queryModel : 'local',
																	bind : '{contractCarOrderGrid.selection.executeSales}',
																	forceSelection : true,
																	editable : false,
																	allowBlank : false,
																	store : Ext.create('Ext.data.Store', {
																						autoLoad : true,
																						fields : [ 'id', 'username' ],
																						proxy : {
																							type: 'direct',
																							directFn : auUserContro.findUsersByRole,
																			        		extraParams: {
																			        			roleCode : 'sales'
																			        		}
																						}
																					}),
																}

														]
													},
													{
														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [
																{
																	xtype : 'textfield',
																	fieldLabel : '来源',
																	name : 'recommendationName',
																	labelWidth : 70,
																	width :200,
																	margin : '0 0 0 20',
																	readOnly : true,
																	bind : '{contractCarOrderGrid.selection.recommendationName}',
																},
																{
																	xtype : 'combobox',
																	fieldLabel : '签约销售',
																	name : 'contractSales',
																	labelWidth : 70,
																	width : 200,
																	margin : '0 0 0 20',
																	valueField : "id",
																	displayField : "username",
																	mode : 'local',
																	bind : '{contractCarOrderGrid.selection.contractSales}',
																	forceSelection : true,
																	editable : false,
																	store : Ext.create('Ext.data.Store', {
																				autoLoad : true,
																				fields : [ 'id', 'username' ],
																				proxy : {
																					type: 'direct',
																					directFn : auUserContro.findUsersByRole,
																	        		extraParams: {
																	        			roleCode : 'sales'
																	        		}
																				}
																			}),
																} ]
													},
													{
														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [ {
															xtype : 'textfield',
															fieldLabel : '租赁合同编号',
															name : 'olPreSaleOrderNo',
															reference : 'olPreSaleOrderNoRef',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															bind : '{contractCarOrderGrid.selection.olPreSaleOrderNo}',
														},
														{
															xtype : 'combobox',
															fieldLabel : '订单状态',
															name : 'status',
															itemId : "status",
															reference : 'statusRef',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															valueField : "code",
															displayField : "nameCn",
															queryModel : 'local',
															bind : {
																store : '{contractCarOrderStatusStore}',
																value : '{contractCarOrderGrid.selection.status}',
															},
															forceSelection : true,
															editable : false,
															allowBlank : false,
														} ]
													},{
														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [ {
															xtype : 'datefield',
															fieldLabel : '租赁合同签订日期',
															name : 'olPreSaleOrderSignDate',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															bind : '{contractCarOrderGrid.selection.olPreSaleOrderSignDate}',
															format: 'Y-m-d',
														},{
															xtype:'datefield',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															fieldLabel:'租赁合同生效日期 ',
															name:'olPreSaleOrderStartDate',
															bind : '{contractCarOrderGrid.selection.olPreSaleOrderStartDate}',
															format:'Y-m-d'
														}]
													},{
														xtype:'container',
														layout:'hbox',
														margin:'5 0',
														defaults:{
															flex:1,
															labelAlign:'left',
														},
														items:[{
															xtype:'displayfield',
															labelWidth : 70,
															width : 200,
															fieldLabel:'征信提交日期',
															name:'creditSubmitDate',
															bind : '{contractCarOrderGrid.selection.creditSubmitDate}',
//															format: 'Y-m-d',
															margin : '0 0 0 20',
														},{
															xtype:'datefield',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															fieldLabel:'征信审核通过日期',
															name:'creditAccessDate',
															bind : '{contractCarOrderGrid.selection.creditAccessDate}',
															format:'Y-m-d'
														}]
													},{
														xtype:'container',
														layout:'hbox',
														margin:'5 0',
														defaults:{
															flex:1,
															labelAlign:'left',
														},
														items:[{
															xtype:'displayfield',
															labelWidth : 70,
															width : 200,
															
															fieldLabel:'调拨完成日期',
															name:'allocationCompleteDate',
															bind : '{contractCarOrderGrid.selection.allocationCompleteDate}',
//															format: 'Y-m-d',
															margin : '0 0 0 20',
														},{
															xtype:'displayfield',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															fieldLabel:'补充协议签订完成日期',
															name:'suppleAgreeCompleteDate',
															bind : '{contractCarOrderGrid.selection.suppleAgreeCompleteDate}',
//															format:'Y-m-d'
														}]
													},{

														xtype:'container',
														layout:'hbox',
														margin:'5 0',
														defaults:{
															flex:1,
															labelAlign:'left',
														},
														items:[{
															xtype:'displayfield',
															width:200,
															labelWidth:70,
															margin : '0 0 0 20',
															fieldLabel:'支付抵押金及手续费日期',
															name:'payDepositDate',
															bind : '{contractCarOrderGrid.selection.payDepositDate}',
//															format: 'Y-m-d',
														},{
															xtype:'displayfield',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															fieldLabel:'商保购买完成日期',
															name:'commInsuranceDealDate',
															bind : '{contractCarOrderGrid.selection.commInsuranceDealDate}',
//															format:'Y-m-d'
														}]
													
													},{
														xtype:'container',
														layout:'hbox',
														margin:'5 0',
														defaults:{
															flex:1,
															labelAlign:'left',
														},
														items:[{
															xtype:'displayfield',
															labelWidth : 70,
															width : 200,
															fieldLabel:'店长审批日期',
															name:'managerApprovalDate',
															bind : '{contractCarOrderGrid.selection.managerApprovalDate}',
//															format: 'Y-m-d',
															margin : '0 0 0 20',
														},{
															xtype:'displayfield',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															fieldLabel:'还款计划导入日期 ',
															name:'replayPlanImportDate',
															bind : '{contractCarOrderGrid.selection.replayPlanImportDate}',
//															format:'Y-m-d'
														}]
													
													
													},{

														xtype:'container',
														layout:'hbox',
														margin:'5 0',
														defaults:{
															flex:1,
															labelAlign:'left',
														},
														items:[{
															xtype:'datefield',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															fieldLabel:'交车日期',
															name:'deliveryDate',
															bind : '{contractCarOrderGrid.selection.deliveryDate}',
															format: 'Y-m-d',
															margin:'0 20'
														}]
													},{
														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [ {
															xtype : 'numberfield',
															decimalPrecision:2,
//															isMoney:true,
															fieldLabel : '订金(元)',
															name : 'dingJinFee',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															bind : '{contractCarOrderGrid.selection.dingJinFee}',
														},
														{
															xtype : 'numberfield',
															decimalPrecision:2,
//															isMoney:true,
															fieldLabel : '装潢费用(元)',
															name : 'decorationFee',
															labelWidth : 70,
															width : 200,
															margin : '0 0 0 20',
															bind : '{contractCarOrderGrid.selection.decorationFee}',
														}
//											          {
//															xtype : 'numberfield',
//															decimalPrecision:2,
//															isMoney:true,
//															fieldLabel : '保险费(元)',
//															name : 'insuranceFee',
//															labelWidth : 70,
//															width : 200,
//															bind : '{contractCarOrderGrid.selection.insuranceFee}',
//														},
														 ]
													},{
														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [ {
															xtype : 'numberfield',
															decimalPrecision:2,
//															isMoney:true,
															fieldLabel : '应收首付款总金额(元)',
															name : 'totalAmountReceivableForFirstPayment',
															labelWidth : 70,
															width : 200,
															margin : '0 20',
															bind : '{contractCarOrderGrid.selection.totalAmountReceivableForFirstPayment}',
															format: 'Y-m-d',
														},
														 ]
													},
													{
														margin : '10 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [ {
															xtype : 'textfield',
															fieldLabel : '备注',
															name : 'remark',
															labelWidth : 70,
															width : 410,
															margin : '0 20',
															bind : '{contractCarOrderGrid.selection.remark}',
														} ]
													} ]
										},
										{
											flex : 1,
											xtype : 'fieldset',
											align : 'left',
											autoScroll : true,
											reference : 'customerFieldset',
											layout : 'vbox',
											bodyPadding : 10,
											collapseDirection : 'top',
											collapsed : false,
											collapsible : true,
											title : "客户信息",
											items : [
													{
														xtype : 'container',
														layout : 'hbox',
														margin : '5 0',

														defaults : {
															flex : 1,
															labelAlign : "left",
														},

														items : [
																{
																	xtype : 'textfield',
																	name : 'customerCode',
																	itemId : 'cusCode',
																	bind : '{contractCarOrderGrid.selection.customerCode}',
																	hidden : true,
																	allowBlank : false,

																},
																{
																	xtype : 'textfield',
																	fieldLabel : '姓名',
																	name : 'customerName',
																	itemId : 'cusName',
																	reference : 'customerNameRef',
																	readOnly : true,
																	bind : '{contractCarOrderGrid.selection.customerName}',
																	labelWidth : 70,
																	width : 170,
																	margin : '0 20',
																	allowBlank : false,
																},
																{
																	xtype : 'textfield',
																	fieldLabel : '手机号码',
																	readOnly : true,
																	name : 'customerPhone',
																	reference : 'phone',
																	itemId : 'phone',
																	bind : '{contractCarOrderGrid.selection.customerPhone}',
																	labelWidth : 70,
																	width : 170,
																	allowBlank : false,
																},
																{
																	xtype : 'button',
																	text : '查找',
																	cls:'nu-btn-nobg',
																	iconCls: 'common-icon-serach',
																	margin : '0 0 0 10',
																	listeners : {
																		click : 'onAddClick'
																	}
																} ]
													},
													{
														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [
																{
																	xtype : 'combobox',
																	fieldLabel : '客户类型',
																	name : 'userType',
																	itemId : "userType",
																	valueField : "code",
																	displayField : "nameCn",
																	queryModel : 'local',
																	bind : '{contractCarOrderGrid.selection.customerUserType}',
																	forceSelection : true,
																	editable : false,
																	readOnly : true,
																	allowBlank : false,
																	labelWidth : 70,
																	width : 170,
																	margin : '0 20',
									             					store : Ext.create('Ext.data.Store',{
									             						autoLoad:true,
																		fields : [ 'code', 'nameCn' ],
																		proxy : {
																			type : 'direct',
																			directFn : chooseOptionContro.getChooseOptionWithBlank,
																			extraParams : {
																				type : 'cusUserType'
																			}
																		}
																	})
																},
																{
																	xtype : 'textfield',
																	fieldLabel : '联系人:',
																	readOnly : true,
																	name : 'otherContacts',
																	itemId : 'otherContacts',
																	bind : '{contractCarOrderGrid.selection.otherContacts}',
																	labelWidth : 70,
																	width : 170,
																}

														]
													},{

														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [
																{
																	xtype : 'combobox',
																	fieldLabel : '性别',
																	name : 'customerSex',
																	itemId : "gender",
																	labelWidth : 70,
																	width : 170,
																	valueField : "code",
																	displayField : "nameCn",
																	queryModel : 'local',
																	bind : '{contractCarOrderGrid.selection.customerSex}',
																	forceSelection : true,
																	editable : false,
																	readOnly : true,
																	store : Ext.create('Ext.data.Store', {
																						autoLoad : true,
																						fields : [ 'code', 'nameCn' ],
																						proxy : {
																							type : 'direct',
																							directFn : chooseOptionContro.getChooseOptionWithBlank,
																							extraParams : {
																								type : 'sexType'
																							}
																						}
																					}),
																	margin : '0 20'
																},
																{
																	xtype : 'textfield',
																	fieldLabel : '身份证号码',
																	name : 'customerCid',
																	readOnly : true,
																	itemId : 'customerCid',
																	bind : '{contractCarOrderGrid.selection.customerCid}',
																	labelWidth : 70,
																	width : 170,
																	allowBlank : false,
																}

														]
													},
													{
														margin : '5 0',
														xtype : 'container',
														readOnly : true,
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [
																{
																	xtype : 'textfield',
																	fieldLabel : '邮箱',
																	name : 'email',
																	itemId : 'email',
																	readOnly : true,
																	bind : '{contractCarOrderGrid.selection.email}',
																	labelWidth : 70,
																	width : 170,
																	margin : '0 20'
																// height:30,

																},
																{
																	xtype : 'textfield',
																	fieldLabel : '学历',
																	readOnly : true,
																	labelWidth : 70,
																	width : 170,
																	name : 'education',
																	itemId : 'education',
																	bind : '{contractCarOrderGrid.selection.education}',
																	//margin : '0 20'
																// height:30,

																}

														]
													},
													{
														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [
																{

																	xtype : 'combobox',
																	fieldLabel : '婚姻状况',
																	name : 'maritalStatus',
																	itemId : "maritalStatus",
																	labelWidth : 70,
																	width : 170,
																	valueField : "code",
																	displayField : "nameCn",
																	queryModel : 'local',
																	bind : '{contractCarOrderGrid.selection.maritalStatus}',
																	forceSelection : true,
																	editable : false,
																	readOnly : true,
																	store : Ext
																			.create(
																					'Ext.data.Store',
																					{
																						autoLoad : true,
																						fields : [
																								'code',
																								'nameCn' ],
																						proxy : {
																							type : 'direct',
																							directFn : chooseOptionContro.getChooseOptionWithSelect,
																							extraParams : {
																								type : 'marryType'
																							}
																						}
																					}),
																	margin : '0 20'
																},
																{
																	xtype : 'textfield',
																	fieldLabel : '家庭人数',
																	name : 'familyNumber',
																	itemId : 'familyNumber',
																	readOnly : true,
																	bind : '{contractCarOrderGrid.selection.familyNumber}',
																	labelWidth : 70,
																	width : 170,
																}

														]
													},
													{
														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [
																{
																	xtype : 'textfield',
																	fieldLabel : '住宅邮编',
																	readOnly : true,
																	name : 'residentialZipCode',
																	itemId : 'residentialZipCode',
																	bind : '{contractCarOrderGrid.selection.residentialZipCode}',
																	labelWidth : 70,
																	width : 170,
																	margin : '0 20'
																// height:30,

																},
																{
																	xtype : 'textfield',
																	fieldLabel : '住宅电话',
																	name : 'telphone',
																	readOnly : true,
																	itemId : 'telphone',
																	bind : '{contractCarOrderGrid.selection.residentialPhone}',
																	labelWidth : 70,
																	width : 170,
																}

														]
													},{
														margin : '5 20',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [ {
															xtype : 'textfield',
															fieldLabel : '住宅地址',
															name : 'residentialAddress',
															readOnly : true,
															itemId : 'residentialAddress',
															bind : '{contractCarOrderGrid.selection.residentialAddress}',
															labelWidth : 70,
															width : 370,
															}
														]
													},{
														margin : '5 20',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [ {
															xtype : 'textfield',
															readOnly : true,
															fieldLabel : '联系人地址:',
															name : 'address',
															itemId : 'address',
															bind : '{contractCarOrderGrid.selection.address}',
															labelWidth : 70,
															width : 370,
															allowBlank : false,
														// height:30,
														}
														]
													}

											]
										},
										{
											flex : 1,
											xtype : 'fieldset',
											align : 'left',
											autoScroll : true,
											reference : 'carProductFieldset',
											layout : 'vbox',
											collapsed : false,
											collapsible : true,
											collapseDirection : 'top',
											title : "产品信息",
											items : [
													{
														xtype : 'container',
														layout : 'vbox',
														margin : '5 0',
														defaults : {
															flex : 1,
														},
														items : [
																{
																	xtype : 'container',
																	layout : 'hbox',
																	items : [
																			{
																				xtype : 'textfield',
																				itemId : 'carProductCode',
																				name : 'contractCarCode',
																				reference: 'contractCarCodeRef',
																				bind : '{contractCarOrderGrid.selection.contractCarCode}',
																				allowBlank : false,
																				hidden : true,
																			},
																			{
																				xtype : 'textfield',
																				fieldLabel : '产品名称',
																				margin : '0 10 0 20',
																				itemId : 'carProductItemId',
																				name : 'contractCarName',
																				bind : '{contractCarOrderGrid.selection.contractCarName}',
																				width : 411,
																				labelWidth : 70,
																				allowBlank : false,
																				readOnly : true,
																				buttonText : '选择'
																			},
																			{
																				xtype : 'button',
																				//margin : '0 10',
																				text : "查询",
																				cls:'nu-btn-nobg',
																				iconCls: 'common-icon-serach',
																				listeners : {
																					click : 'onBddClick'
																				}

																			}]
																},
																{
																	xtype : 'container',
																	layout : 'hbox',
																	margin : '10 0',
																	defaults : {
																		flex : 1,
																		labelAlign : "left",
																	},
																	items : [ {
																		xtype : 'numberfield',
																		decimalPrecision:0,
																		fieldLabel : '期限（年）',
																		width : 200,
																		labelWidth : 70,
																		margin : '0 20',
																		readOnly : true,
																		itemId : 'leaseTerm',
																		name : 'leaseTerm',
																		bind : '{contractCarOrderGrid.selection.leaseTerm}',
																	},
																	{
																		xtype : 'numberfield',
																		decimalPrecision:0,
																		fieldLabel : '数量',
																		width : 200,
																		labelWidth : 70,
																		itemId : 'orderCount',
																		name : 'orderCount',
																		bind : '{contractCarOrderGrid.selection.orderCount}',
																		regex : /^[1-9]\d*$/,
																	} ]
																},
																{
																	xtype : 'container',
																	layout : 'hbox',
																	margin : '10 0',
																	defaults : {
																		flex : 1,
																		labelAlign : "left",
																	},
																	items : [
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '保证金（元）',
																				width : 200,
																				labelWidth : 70,
																				margin : '0 20',
																				readOnly : true,
																				itemId : 'deposit',
																				name : 'deposit',
																				bind : '{contractCarOrderGrid.selection.deposit}',

																			},
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '期满购买价格（元）',
																				width : 200,
																				labelWidth : 70,
																				readOnly : true,
																				itemId : 'expirePrice',
																				name : 'expirePrice',
																				bind : '{contractCarOrderGrid.selection.expirePrice}',

																			}
																			]
																},
																{
																	xtype : 'container',
																	layout : 'hbox',
																	margin : '10 0',
																	defaults : {
																		flex : 1,
																		labelAlign : "left",
																	},
																	items : [
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '月租费（元）',
																				width : 200,
																				labelWidth : 70,
																				margin : '0 20',
																				readOnly : true,
																				itemId : 'monthlyRent',
																				name : 'monthlyRent',
																				bind : '{contractCarOrderGrid.selection.monthlyRent}',
																			},
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '超出里程费用（元/公里）',
																				width : 200,
																				labelWidth : 70,
																				readOnly : true,
																				itemId : 'outOfRangFee',
																				name : 'outOfRangFee',
																				bind : '{contractCarOrderGrid.selection.outOfRangFee}',
																			} ]
																},
																{
																	xtype : 'container',
																	layout : 'hbox',
																	margin : '10 0',
																	defaults : {
																		flex : 1,
																		labelAlign : "left",
																	},
																	items : [
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '提车服务费（元）',
																				width : 200,
																				labelWidth : 70,
																				margin : '0 20',
																				readOnly : true,
																				itemId : 'liftTheFare',
																				name : 'liftTheFare',
																				bind : '{contractCarOrderGrid.selection.liftTheFare}',
																			},
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '保险费用及充电桩使用服务费（元）',
																				width : 200,
																				labelWidth : 70,
																				readOnly : true,
																				reference : 'monthlyManagementFeeRef',
																				itemId : 'monthlyManagementFee',
																				name : 'monthlyManagementFee',
																				bind : '{contractCarOrderGrid.selection.monthlyManagementFee}',
																			}
																			]
																},
																{
																	xtype : 'container',
																	layout : 'hbox',
																	margin : '10 0',
																	defaults : {
																		flex : 1,
																		labelAlign : "left",
																	},
																	items : [
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '充电桩费用（元）',
																				width : 200,
																				labelWidth : 70,
																				margin : '0 20',
																				readOnly : true,
																				reference : 'chargeFeeRef',
																				itemId : 'chargeFee',
																				name : 'chargeFee',
																				bind : '{contractCarOrderGrid.selection.chargeFee}',
																			},
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '充电桩费用（元）',
																				width : 200,
																				labelWidth : 70,
																				margin : '0 20',
																				readOnly : true,
																				hidden : true,
																				reference : 'financialPackageCodeRef',
																				itemId : 'financialPackageCode',
																				name : 'financialPackageCode',
																				bind : '{contractCarOrderGrid.selection.financialPackageCode}',
																			},
																			 ]
																},
														]
													}, ]
										},
						        ],
						        dockedItems: [ {
	        	                    xtype: 'toolbar',
	        	                    dock: 'bottom',
	        	                    padding:'10 0 0 0',
	        	                    border:true,
	        	                    layout: {
	        	                        type: 'hbox'
	        	                    },
	        	                    items: [
	        	                         {xtype:'tbfill'},
	       								 {
	     									xtype:'button',
	     									text:'取消',
	     									cls:'btn-danger',
	     									icon:'images/notline.png',
	     									margin:'0 20',
	     									itemId:'cancelContractCarProcessBtn',
	     									reference:'cancelContractCarProcessBtnRef',
	     									handler : 'onCancelClick'
	     								},
	     								 {
	     									xtype:'button',
	     									text:'保存',
	     									cls:'btn-primary',
	     									icon:'images/save.png',
	     									handler : 'onModifyContractCarOrderClick'
	     								},{
	     									xtype:'button',
	     									text:'启动流程',
	     									cls:'btn-success',
	     									iconCls : 'common-icon-go',
	     									//icon:'images/online.png',
	     									handler : 'onStartWorkflowClick'
	     								},
	     								{xtype:'tbfill'}
	     								]
	        	                }
	        	            ],
						        
							},
				         {
							xtype : 'tabpanel',
							//layout : 'fit',
							//padding:'0 15 20 15',
							activeTab : 0,
						    resizeTabs:true, 
						    tabPosition:'top',
						    deferredRender:false,
							border : false,
							//plain : true, // True表示tab候选栏上没有背景图片（默认为false）
							enableTabScroll : true, // 选项卡过多时，允许滚动
							reference : 'olPreSaleOrderFieldset',
							items : [ {
								xtype : 'panel',
								title : '车辆及保险信息',
								layout : {
									type : 'vbox',
									align : 'stretch'
								},
								items : [ {
									xtype : 'gridpanel',
									reference : 'contractCarOrderDetailGrid',
									itemId:'contractCarOrderDetailItem',
									bind : '{contractCarOrderDetailListStore}',
									border : false,
									flex:1,
									autoScroll : true,
									//layout:'fit',
//									viewConfig : {
//										emptyText : '暂无车辆及保险信息！',
//										enableTextSelection : true
//									},
//									selModel: {
//										selType:'checkboxmodel',
//										mode : 'SIMPLE'
//									},
									plugins:[
						                Ext.create('Ext.grid.plugin.CellEditing',{
						                	clicksToEdit:1
						                })
						            ],
									// height : 300,
									columns : [ {
										xtype: 'actioncolumn',
						                width: 50,
						                sortable: false,
						                menuDisabled: true,
						                text : '操作',
						                align : "center",
						                items: [{
						                    icon: 'images/upload.png',
						                    tooltip: '上传车辆及保险信息附件',
						                    handler: 'onUploadCarBXClick'
						                }]
									}, {
										dataIndex : 'id',
										hidden : true,
									},{
										dataIndex : 'contractCarOrderId',
										hidden : true,
									},{
										dataIndex : 'olPreSaleOrderNo',
										hidden : true,
									},{
										dataIndex : 'carProductDisplayName',
										hidden : true,
									},{
										text : '名称',
										dataIndex : 'carProductName',
									},{
										text : '补充协议编号',
										width: 150,
										dataIndex : 'suppleAgreementNo',
										align : 'center'
									},{
										text : '车辆资产ID',
										width: 170,
										dataIndex : 'carInfoId',
										align : 'center',
										hidden : true,
									},{
										text : '车辆资产编号',
										width: 170,
										dataIndex : 'carInfoCode',
										align : 'center'
									}, {
										text : '车架号',
										dataIndex : 'carFrameNo',
										align : 'center',
									}, {
										text : '发动机号',
										dataIndex : 'carEngineNo',
										align : 'center'
									}, {
										text : '车牌号码',
										dataIndex : 'carLicensePlate',
										align : 'center'
									}, {
										text : '行驶证号',
										dataIndex : 'carDriveLicenseNo',
										align : 'center'
									}, {
										text : '初始公里程数（KM）',
										dataIndex : 'initMileage',
										align : 'center',
										regex : /^[0-9]+(\.[0-9]{2})?$/,
										editor:{
											xtype:'numberfield',
//											allowBlank: false,
											name:'initMileage'
										}
									}, {
										text : '交强险保险公司',
										dataIndex : 'insuranceCompany',
										align : 'center',
										editor : {
											xtype : 'combobox',
											valueField : 'code',
											displayField : 'nameCn',
											readOnly: true,
											editable : false,
//											allowBlank : false,
											bind : {
												store : '{insuranceCompanyStore}'
											}
										},
										renderer:'insuranceCompanyEditor'
									},{
										text : '交强险保单ID',
										dataIndex : 'strongInsuranceId',
										align : 'center',
										hidden : true,
									}, {
										text : '交强险保单号',
										dataIndex : 'strongInsuranceNo',
										align : 'center'
									}, {
										text : '交强险起始日期',
										dataIndex : 'strongInsuranceStartDate',
										align : 'center',
										editor:{
											xtype: 'datefield',
											format : 'Y-m-d',
//											allowBlank: false,
											readOnly: true,
											editable : false,
											name:'strongInsuranceStartDate'
										},
										renderer:function(value){ 
					                    	if(value==null){
					                    		return "";
					                    	}else{
					                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
					                    	}
					                    }
									}, {
										text : '交强险终止日期',
										dataIndex : 'strongInsuranceEndDate',
										align : 'center',
										editor:{
											xtype: 'datefield',
											format : 'Y-m-d',
//											allowBlank: false,
											readOnly: true,
											editable : false,
											name:'strongInsuranceEndDate'
										},
										renderer:function(value){ 
					                    	if(value==null){
					                    		return "";
					                    	}else{
					                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
					                    	}
					                    }
									}, {
										text : '商业险保险公司',
										dataIndex : 'commercialInsuranceCompany',
										align : 'center',
										editor : {
											xtype : 'combobox',
											valueField : 'code',
											displayField : 'nameCn',
											readOnly: true,
											editable : false,
//											allowBlank : false,
											bind : {
												store : '{insuranceCompanyStore}'
											}
										},
										renderer:'insuranceCompanyEditor'
									}, {
										text : '商业险保单ID',
										dataIndex : 'commercialInsuranceId',
										align : 'center',
										hidden : true,
									}, {
										text : '商业险保险年份',
										dataIndex : 'commercialInsuranceYear',
										align : 'center',
										editor : {
											xtype : 'combobox',
											valueField : 'code',
											displayField : 'nameCn',
											readOnly: true,
											editable : false,
//											allowBlank : false,
											bind : {
												store : '{contractInsuranceYearStore}'
											}
										},
									}, {
										text : '商业险保单号',
										dataIndex : 'commercialInsuranceNo',
										align : 'center',
										editor:{
					                		xtype:'textfield',
					                		readOnly: true,
											editable : false,
					                		name:'commercialInsuranceNo'
					                	},
									}, {
										text : '商业险起始日期',
										dataIndex : 'commercialInsuranceStartDate',
										align : 'center',
										editor:{
											xtype: 'datefield',
											format : 'Y-m-d',
											readOnly: true,
											editable : false,
//											allowBlank: false,
											name:'commercialInsuranceStartDate'
										},
										renderer:function(value){ 
					                    	if(value==null){
					                    		return "";
					                    	}else{
					                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
					                    	}
					                    }
									}, {
										text : '商业险终止日期',
										dataIndex : 'commercialInsuranceEndDate',
										align : 'center',
										editor:{
											xtype: 'datefield',
											format : 'Y-m-d',
											readOnly: true,
											editable : false,
//											allowBlank: false,
											name:'commercialInsuranceEndDate'
										},
										renderer:function(value){ 
					                    	if(value==null){
					                    		return "";
					                    	}else{
					                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
					                    	}
					                    }
									}, {
										text : 'GPS设备编号',
										dataIndex : 'gpsDeviceNo',
										align : 'center'
									},
									],
									tbar : [ {
										xtype : 'button',
										text : '新建',
										iconCls : 'common-icon-pencil-add',
										listeners : {
											click : 'onAddContractCarOrderDetailClick'
										}
									}, {
										xtype : 'button',
										text : '保存配车及保险信息',
										iconCls : 'common-icon-save',
										listeners : {
											click : 'onSaveContractCarOrderDetailClick'
										}
									
									}, {
										xtype : 'button',
										text : '配车',
										iconCls : 'common-icon-car',
										listeners : {
											click : 'onAllocationCarClick'
										}
									
									}, {
										xtype : 'button',
										text : '取消配车',
										iconCls : 'common-icon-cancel',
										listeners : {
											click : 'onCancelAllocationCarClick'
										}
									
									}, {
										xtype : 'button',
										text : '购买车辆商业保险',
										iconCls : 'nu-shield-car',
										listeners : {
											click : 'onBuycommercialInsuranceClick'
										}
									
									} ],

								}, 
								]

							},{
								xtype : 'panel',
								title : '合同信息',
								//layout : 'vbox',
								border : false,
								tbar : [ 
//								{
//									xtype : 'button',
//									text : '新增',
//									iconCls : 'common-icon-add',
//									listeners : {
//										click : 'onAddContractCarBCYXtClick'
//									}
//								}, 
								{
									xtype : 'button',
									text : '保存',
									iconCls : 'common-icon-save',
									listeners : {
										click : 'onSaveContractCarBCYXtClick'
									}
								
								},
								{
									xtype : 'button',
									text : '租赁合同附件',
									listeners : {
										click : 'onUploadContractAttachemetClick'
									}
								
								},
								{
									xtype : 'button',
									text : '租赁合同下载',
									iconCls : 'pdf',
									listeners : {
										click : 'onDownContractClick'
									}
								
								}],
								items : [ {
									xtype : 'panel',
									layout : {
										type : 'vbox',
										align : 'stretch'
									},
									border : false,
									margin : "10px 0 0 0",
									items : [ {
										xtype : 'gridpanel',
										reference : 'contractCarSuppleAgreementGrid',
										bind : '{contractCarSuppleAgreementListStore}',
										margin : "0 0 10px 10px",
										autoScroll : 'true',
										viewConfig : {
											emptyText : '暂无补充协议信息！',
											enableTextSelection : true
										},
							            plugins:[
							                Ext.create('Ext.grid.plugin.CellEditing',{
							                	clicksToEdit:1
							                })
							            ],
										columns : [ {
											xtype: 'actioncolumn',
							                width: 70,
							                sortable: false,
							                menuDisabled: true,
							                text : '操作',
							                align : "center",
							                items: [{
							                    icon: 'images/upload.png',
							                    tooltip: '上传补充协议',
							                    handler: 'onUploadBCXYClick'
							                }, 
							                {
							                    icon: 'images/printer.png',
							                    tooltip: '打印补充协议',
							                    handler: 'onPrintBCXYClick'
							                }
							                ]
										},{
											dataIndex : 'id',
											hidden : true,
										},{
											dataIndex : 'contractCarOrderId',
											hidden : true,
										},{
											dataIndex : 'olPreSaleOrderNo',
											hidden : true,
										},{
											text : '补充协议编号',
											dataIndex:'suppleAgreementNo',
											align : 'center',
										}, {
											text : '签订日期',
											dataIndex:'signDate',
											align : 'center',
											editor:{
												xtype:'datefield',
												format : 'Y-m-d',
												allowBlank: false,
												name:'signDate'
											},
											renderer:function(value){ 
						                    	if(value==null){
						                    		return "";
						                    	}else{
						                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
						                    	}
						                    }
										}, {
											text : '开始日期',
											dataIndex:'startDate',
											align : 'center',
											editor:{
												xtype:'datefield',
												format : 'Y-m-d',
												allowBlank: false,
												name:'startDate'
											},
											renderer:function(value){ 
						                    	if(value==null){
						                    		return "";
						                    	}else{
						                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
						                    	}
						                    }
										}, {
											text : '结束日期',
											dataIndex:'endDate',
											align : 'center',
											editor:{
												xtype:'datefield',
												format : 'Y-m-d',
												allowBlank: false,
												name:'endDate'
											},
											renderer:function(value){ 
						                    	if(value==null){
						                    		return "";
						                    	}else{
						                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
						                    	}
						                    }
										}, {
											xtype : 'gridcolumn',
											text : '银行卡信息',
											dataIndex : 'bankCardInfoId',
											align : 'center',
											hidden: false,
											width:260,
											editor:{
												xtype: 'combobox',
						                		valueField: 'id',
						                		displayField: 'bankAccountInfo',
						                		editable : false,
						                		allowBlank: false,
						                		queryMode: 'local',
						                		listeners:{
//													beforequery:'initBankCardInfoCombo',
												},
						                        bind : {
						                        	store : '{bankCardInfoStore}',
						                        },
						                	},
						                	renderer: 'bankCardInfoEditor',
										}, {
											text : '车架号',
											dataIndex : 'carFrameNo',
											align : 'center',
										}, {
											text : '车牌号码',
											dataIndex : 'carLicensePlate',
											align : 'center',
										},
										]
									}, 
									]

								} ]
							},{
								//layout : 'fit',
								xtype : 'panel',
								title : '支付信息',
								layout : {
									type : 'vbox',
									align : 'stretch'
								},
								items : [ {
//									layout : 'hbox',
									xtype : 'gridpanel',
									border : false,
									margin : '5px 0',
									reference : 'contractCarOrderPayLogGrid',
									itemId : 'contractCarOrderPayLogGrid',
									bind : '{contractCarOrderPayLogListStore}',
//									viewConfig : {
//										emptyText : '暂无支付信息！',
//										enableTextSelection : true
//									},
//						    		selModel: {
//										selType:'checkboxmodel',
//										mode : 'SIMPLE'
//									},
						            plugins:[
						                Ext.create('Ext.grid.plugin.CellEditing',{
						                	clicksToEdit:1
						                })
						            ],
									columns : [
											{
												dataIndex : 'id',
												hidden : true,
											},
											{
												dataIndex : 'contractCarOrderId',
												hidden : true,
											},
											{
												text : '支付凭据单号',
												dataIndex : 'payNo',
												align : 'center',
												name:'payNo',
												editor:{
							                		xtype:'textfield',
							                		allowBlank: false,
							                		/*listeners:{
							                			blur: 'onNumBlur'
							                		},*/
							                		name:'payNo'
							                	}
											},
											{
												xtype : 'gridcolumn',
												text : '支付类型',
												dataIndex : 'payType',
												align : 'center',
												name:'payType',
												hidden: false,
												editor:{
													xtype: 'combobox',
							                		valueField: 'code',
							                		displayField: 'nameCn',
							                		editable : false,
							                		allowBlank: false,
							                        bind : {
							                        	store : '{orderPayTypeStore}',
							                        },
							                	},
							                	renderer: 'orderPayTypeEditor',
											},
											{
												text : '支付方式',
												dataIndex : 'payChannel',
												align : 'center',
												name:'payChannel',
						                		editor:{
													xtype: 'combobox',
							                		valueField: 'code',
							                		displayField: 'nameCn',
							                		editable : false,
							                		allowBlank: false,
							                		bind : {
							                        	store : '{orderPayChannelStore}',
							                        },
							                	},
							                	renderer: 'orderPayChannelEditor',
											},
											{
												text : '金额',
												dataIndex : 'payAmount',
												align : 'center',
												name:'payAmount',
//												formatter: 'usMoney',
												regex : /^[0-9]+(\.[0-9]{2})?$/,
												editor:{
							                		xtype:'numberfield',
							                		allowBlank: false,
							                		name:'payAmount'
							                	}
											},
											{
												text : '支付日期',
												dataIndex : 'payTime',
												align : 'center',
												name:'payTime',
												editor:{
													xtype: 'datefield',
													format : 'Y-m-d',
							                		allowBlank: false,
							                		name:'payTime'
							                	},
												renderer:function(value){ 
							                    	if(value==null){
							                    		return "";
							                    	}else{
							                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
							                    	}
							                    }
											},
											{
												text : '备注',
												dataIndex : 'remark',
												align : 'center',
												name:'remark',
												editor:{
							                		xtype:'textfield',
							                		name:'remark'
							                	}
											},
											{
												xtype: 'actioncolumn',
								                width: 150,
								                sortable: false,
								                menuDisabled: true,
								                text : '操作',
								                align : "center",
								                items: [{
								                    iconCls: 'common-icon-save mr10',
								                    tooltip: '保存',
//								                    scope: this,
								                    //cls:'pl10 pr10',
								                    handler: 'onContractCarOrderPaySaveClick'
								                }, {
								                	iconCls: 'trash-red mr10 ',
								                    tooltip: '删除',
								                   // cls:'pl10 pr10',
								                    handler: 'onContractCarOrderPayRemoveClick'
								                }, {
								                	iconCls: 'common-icon-upload',
								                	 tooltip: '上传支付信息附件',
								                	 handler: 'onUploadContractCarOrderPayClick'
								                }]
											},
											
											 ],
									tbar : [ {
										xtype : 'button',
										text : '新建',
										iconCls : 'common-icon-pencil-add',
										listeners : {
											click : 'onPayAddClick'
										}
									} ],
								}, 
								]
							}, 
							{
								title : '征信材料',
								xtype : "panel",
								//layout : 'auto',
								border : false,
								// buttonAlign:'left',
								items : [ {

									xtype : 'panel',
									layout : {
										type : 'vbox',
										align : 'stretch'
									},
									border : false,
									margin : "10px 0 0 0",
									items : [
									{
										xtype : 'panel',
										//title:'   ',
										layout : 'auto',
										cls:'p20',
										border : true,
										html : '<div class="red">※ 以下材料均要提供<strong>拍照版本</strong>或<strong>彩色扫描件</strong>（如果拍照件一定要拍清楚，拍不清楚的请用彩色扫描件）</div>'
												+ "<div class='halfBox tip-box'>"
												+ "<p>1.身份证（正反面）<span class='steelblue'>（必须提供）</span></p>"
												+ "<p>2.户口本 <span class='steelblue'>（必须提供）</span></p>"
												+ "<p>3.驾照及驾照副页 <span class='steelblue'>（必须提供）</span></p>"
												+ "<p>4.结婚证，或离婚证 <span class='steelblue'>（必须提供）</span></p>"
												+ "<p>5.配偶身份证（正反面） <span class='steelblue'>（必须提供）</span></p>"
												+ "<p>6.社保号码 <span class='steelblue'>（必须提供）</span></p>"
												+ "<p>7.汽车租赁申请表 <span class='steelblue'>（必须提供，务必填写完整）</span></p>"
												+ "</div>"
												+ "<div style='display:none;'>"
												+ "<p>1.企业营业执照，组织机构代码证，税务登记证 <span class='steelblue'>（必须提供）</span></p>"
												+ "<p>2.法人代表身份证（正反面）（必须提供）</p>"
												+ "<p>3.驾驶员驾照及驾照副页（必须提供）</p>"
												+ "<p>4.汽车租赁申请表 <span class='steelblue'>（必须提供，务必填写完整）</span></p>"
												+ "</div>"
												+ "<div class='halfBox tip-box'>"
												+ "<p>1.企业营业执照，组织机构代码证，税务登记证 <span class='steelblue'>（必须提供）</span></p>"
												+ "<p>2.法人代表身份证（正反面）<span class='steelblue'>（必须提供）</span></p>"
												+ "<p>3.驾驶员驾照及驾照副页 <span class='steelblue'>（必须提供）</span></p>"
												+ "<p>4.汽车租赁申请表 <span class='steelblue'>（必须提供，务必填写完整）</span></p>"
												+ "</div>",
									},        
									{
										xtype:'uploadAttachmentPanel',
							        	reference:'uploadZXCLAttachmentPanel',
							        	itemId:'uploadZXCLAttachmentPanelItemId',
							        }
									]
						        } ],

							},
							{
								title : '还款计划',
								xtype : "panel",
								//layout : 'auto',
								border:false,
								padding:10,
								// buttonAlign:'left',
								items : [ {
						        	xtype: 'form',
						        	reference: 'replaymentPlanForm',
						            api:{
						            	submit:contractCarOrderContro.importReplaymentPlan
						            },
						            paramsAsHash: true,
						        	dockedItems: [ {
			        	                    xtype: 'toolbar',
			        	                    dock: 'top',
			        	                    border: 0,
			        	                    layout: {
			        	                        type: 'hbox'
			        	                    },
			        	                    items: [ {
			        	                            xtype: 'fileuploadfield',
			        	                            buttonConfig: {
			        	                               // iconCls: 'common_icon_export_excel'
			        	                            },
			        	                            name: 'fileUpload',
			        	                            reference: 'fileUploadRef',
	//						        	                            buttonOnly: true,
	//						        	                            hideLabel: true,
	//						        	                            fieldLabel: '导入还款计划',
			        	   							width: 350,
//			        	   							allowBlank:false,
			        	                            buttonText: '选择',
			        	                        }, {
		            	                            xtype: 'button',
		            	                            iconCls: 'common-icon-import',
		            	                            text: '导入还款计划',
		            	                            handler:'onImportReplaymentPlanClick'
		            	                        }, {
		            	                            xtype: 'button',
		            	                            iconCls: 'common_icon_export_excel',
		            	                            text: '下载还款计划导入模板',
		            	                            handler:'onDownReplaymentPlanClick'
		            	                        },
			        	                    ]
			        	                }
			        	            ]
								},{
									xtype : 'gridpanel',
									reference : 'ccsaReplaymentPlanGrid',
									bind : '{contractCarSuppleAgreementListStore}',
									listeners:{
										select:'onCcsaReplaymentPlanGridSelect'
									},
									margin : "0 0 10px 10px",
									autoScroll : 'true',
									viewConfig : {
										emptyText : '暂无补充协议信息！',
										enableTextSelection : true
									},
						            plugins:[
						                Ext.create('Ext.grid.plugin.CellEditing',{
						                	clicksToEdit:1
						                })
						            ],
									columns : [ {
										dataIndex : 'id',
										hidden : true,
									}, {
										dataIndex : 'contractCarOrderId',
										hidden : true,
									}, {
										text : '补充协议编号',
										dataIndex:'suppleAgreementNo',
										align : 'center',
									}, {
										xtype : 'gridcolumn',
										text : '银行卡信息',
										dataIndex : 'bankCardInfoId',
										align : 'center',
										hidden: false,
										editor:{
											xtype: 'combobox',
					                		valueField: 'id',
					                		displayField: 'bankAccountInfo',
					                		editable : false,
					                		allowBlank: false,
					                		readOnly: true,
					                		queryMode: 'local',
//					                		listeners:{
//												beforequery:'initBankCardInfoCombo',
//											},
					                        bind : {
					                        	store : '{bankCardInfoStore}',
					                        },
					                	},
					                	renderer: 'bankCardInfoEditor',
									}, {
										text : '车架号',
										dataIndex : 'carFrameNo',
										align : 'center',
									}, {
										text : '车牌号码',
										dataIndex : 'carLicensePlate',
										align : 'center',
									} ]
								},{
									xtype : 'gridpanel',
									autoScroll : 'true',
									buttonAlign : 'left',
									reference : 'replaymentPlanGrid',
									bind : '{replaymentPlanListStore}',
									viewConfig : {
										emptyText : '暂无信息！',
										enableTextSelection : true
									},
									columns : [ {
										dataIndex: 'numberOfPeriods',
										text : '期数',
										align : 'center', flex:3,
									}, {
										dataIndex: 'startDate',
										text : '租金开始日期',
										align : 'center', flex:2,
									}, {
										dataIndex: 'endDate', flex:2,
										text : '租金结束日期',
										align : 'center', flex:2,
									}, {
										xtype: "numbercolumn",
										format: '0,0.00',
										dataIndex: 'monthlyAmount', flex:2,
										text : '月供金额',
										align : 'center', flex:2,
									}, {
										dataIndex: 'deductionPlanDate',
										text : '扣款计划', flex:2,
										align : 'center',
									} ],
//									dockedItems: [ {
//				      			        xtype: 'pagingtoolbar',
//				      			        dock: 'bottom',
//				      			        bind: {
//				      				        store: '{replaymentPlanListStore}'
//				      				    },
//				      			        displayInfo : true,
//				      					displayMsg:'显示 {0} - {1}条记录，总共 {2}条记录',
//				      					emptyMsg:'暂无数据',
//				      					beforePageText:'页数',
//				      					afterPageText:'总共{0}页',
//				      					firstText:'第一页',
//				      					prevText:'上一页',
//				      					nextText:'下一页',
//				      					lastText:'最后一页',
//				      					width:'100%',
//				      					emptyMsg : '没有记录'
//				      			    } ]
								} ]
							}

							]
						}
				         ]
			},
			]

		});


