/*
 * File: app/view/role/RoleMangerPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */
Ext
		.define(
				'Evcorp.view.orderList.OrderListDetails',
				{
					extend : 'Ext.panel.Panel',
					alias : 'widget.orderlistdetails',
					requires : [
							'Evcorp.view.orderList.OrderListDetailsViewController',
							'Evcorp.view.orderList.OrderListDetailsViewModel',
							'Ext.grid.Panel', 'Ext.tab.Panel',
							'Ext.grid.column.Column', 'Ext.grid.View',
							'Ext.toolbar.Toolbar', 'Ext.button.Button',
							'Ext.toolbar.Fill', 'Ext.form.Panel',
							'Ext.form.field.ComboBox', 'Ext.form.DateField' ],
					controller : 'OrderListDetails',
					viewModel : {
						type : 'OrderListDetails'
					},
					referenceHolder : true,
					itemId : 'OrderListDetails',
					// closable : true,
					// xtype:'panel',
					layout : 'auto',
					items : [ {
						xtype : 'form',
						reference:'taskDetailForm',
						padding:'20',
						border:false,
						autoScroll : true,
						items : [

									{
										flex : 1,
										xtype : 'fieldset',
										align : 'left',
										collapsed : false,
										collapsible : true,
										autoScroll : true,
										reference : 'contractCarOrderDetailFieldset',
										layout : 'vbox',
										collapseDirection : 'top',
										title : "订单",
										margin:10,
										items : [
												{
													xtype : 'container',
													layout : 'hbox',
													margin : '5 0',

													defaults : {
														flex : 1,
														labelAlign : "left",
													},

													items : [
															{
																xtype : 'hidden',
																fieldLabel : 'id',
																name : 'id'
															},
															{
																xtype : 'textfield',
																fieldLabel : '编号',
																name : 'orderNo',
																labelWidth : 84,
																width : 200,
																readOnly : true,
																margin : '0 20'
															},
															{
																xtype:'hidden',
																name:'taskId'
															},{
																xtype:'hidden',
																name:'processInstanceId'
															},
															{
																xtype : 'combobox',
																fieldLabel : '执行销售',
																name : 'executeSales',
																labelWidth : 110,
																width : 220,
																valueField : "id",
																displayField : "username",
																queryModel : 'local',
																forceSelection : true,
																editable : false,
																allowBlank : false,
																readOnly : true,
																store : Ext.create('Ext.data.Store', {
																	autoLoad : true,
																	fields : [ 'id', 'username' ],
																	proxy : {
																		type: 'direct',
																		directFn : auUserContro.findUsersByRole,
														        		extraParams: {
														        			roleCode : 'sales'
														        		}
																	}
																}),
															}
													]
												},
												{
													margin : '5 0',
													xtype : 'container',
													layout : 'hbox',
													defaults : {
														flex : 1,
														labelAlign : "left",
													},
													items : [
															{
																xtype : 'textfield',
																fieldLabel : '来源',
																name : 'recommendationName',
																labelWidth : 84,
																width : 200,
																margin : '0 20',
																readOnly : true
															},
															{
																xtype : 'combobox',
																fieldLabel : '签约销售',
																name : 'contractSales',
																labelWidth : 110,
																width : 220,
																valueField : "id",
																displayField : "username",
																mode : 'local',
																forceSelection : true,
																editable : false,
																readOnly : true,
																store : Ext
																		.create(
																				'Ext.data.Store',
																				{
																					autoLoad : true,
																					fields : [
																							'id',
																							'username' ],
																					proxy : {
																						type : 'direct',
																						directFn : olOrderManagerContro.getUserList
																					}
																				}),
															} ]
												},
												{
													margin : '5 0',
													xtype : 'container',
													layout : 'hbox',
													defaults : {
														flex : 1,
														labelAlign : "left",
													},
													items : [ {
														xtype : 'textfield',
															fieldLabel : '租赁合同编号',
															name : 'olPreSaleOrderNo',
															reference : 'olPreSaleOrderNoRef',
															labelWidth : 84,
														width : 200,
														readOnly : true,
															margin : '0 20',
													},
													{
														xtype : 'combobox',
														fieldLabel : '订单状态',
														name : 'status',
														itemId : "status",
														labelWidth : 110,
														width : 220,
														valueField : "code",
														displayField : "nameCn",
														queryModel : 'local',
														forceSelection : true,
														editable : false,
														allowBlank : false,
														readOnly : true,
														store : Ext.create('Ext.data.Store', {
																	autoLoad : true,
																	fields : [ 'code', 'nameCn' ],
																	proxy : {
																		type : 'direct',
																		directFn : chooseOptionContro.getChooseOption,
																		extraParams : {
																			type : 'contractCarOrderStatus'
																		}
																	}
																}),
													} ]
												},{
													margin : '5 0',
													xtype : 'container',
													layout : 'hbox',
													defaults : {
														flex : 1,
														labelAlign : "left",
													},
													items : [ {
															xtype : 'datefield',
															fieldLabel : '租赁合同签订日期',
															name : 'olPreSaleOrderSignDate',
															labelWidth : 84,
														width : 200,
															margin : '0 20',
															format: 'Y-m-d',
															readOnly : true
														},{
															xtype:'datefield',
															labelWidth : 110,
														width : 220,
															fieldLabel:'租赁合同生效日期 ',
															name:'olPreSaleOrderStartDate',
															format:'Y-m-d',
															readOnly : true,
													} ]
												},{
													xtype:'container',
													layout:'hbox',
													margin:'10 0',
													defaults:{
														flex:1,
														labelAlign:'left',
													},
													items:[{
															xtype:'datefield',
															labelWidth:84,
															width:200,
															fieldLabel:'征信提交日期',
															name:'creditSubmitDate',
															format: 'Y-m-d',
																readOnly : true,
															margin:'0 20'
														},{
															xtype:'datefield',
															labelWidth:110,
																width:220,
															fieldLabel:'征信审核通过日期',
															name:'creditAccessDate',
																readOnly : true,
															format:'Y-m-d'
													}]
												},{
													xtype:'container',
													layout:'hbox',
													defaults:{
														flex:1,
														labelAlign:'left',
													},
														items:[{
															xtype:'datefield',
															labelWidth : 80,
															width : 200,
															fieldLabel:'调拨完成日期',
															name:'allocationCompleteDate',
//															format: 'Y-m-d',
readOnly : true,
															margin:'0 20'
														},{
															xtype:'datefield',
															labelWidth : 110,
															width : 220,
															fieldLabel:'补充协议签订完成日期',
															name:'suppleAgreeCompleteDate',
															readOnly : true,
//															format:'Y-m-d'
														}]
												},{

													xtype:'container',
													layout:'hbox',
													defaults:{
														flex:1,
														labelAlign:'left',
													},
														items:[{
															xtype:'datefield',
														width:200,
															labelWidth:84,
															fieldLabel:'支付抵押金及手续费日期',
															name:'payDepositDate',
															format: 'Y-m-d',
														readOnly : true,
															margin:'0 20'
														},{
															xtype:'datefield',
															labelWidth : 110,
															width : 220,
															fieldLabel:'商保购买完成日期',
															name:'commInsuranceDealDate',
															readOnly : true,
															format:'Y-m-d'
														}]
												
												},{
													xtype:'container',
													layout:'hbox',
													defaults:{
														flex:1,
														labelAlign:'left',
													},
														items:[{
															xtype:'datefield',
															labelWidth : 84,
															width : 200,
															fieldLabel:'店长审批日期',
															name:'managerApprovalDate',
															readOnly : true,
															format: 'Y-m-d',
															margin:'0 20'
														},{
															xtype:'datefield',
															labelWidth : 110,
															width : 220,
															fieldLabel:'还款计划导入日期 ',
															name:'replayPlanImportDate',
															readOnly : true,
															format:'Y-m-d'
														}]
												
												
												},{

													xtype:'container',
													layout:'hbox',
													defaults:{
														flex:1,
														labelAlign:'left',
													},
														items:[{
															xtype:'datefield',
															labelWidth : 84,
															width : 200,
															fieldLabel:'交车日期',
															name:'deliveryDate',
															format: 'Y-m-d',
															readOnly : true,
															margin:'0 20'
														}]
													},{
														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [ {
															xtype : 'numberfield',
															decimalPrecision:2,
//															isMoney:true,
															fieldLabel : '保险费(元)',
															name : 'insuranceFee',
															labelWidth : 84,
															width : 200,
															margin : '0 20',
															readOnly : true,
														},
														{
															xtype : 'numberfield',
															decimalPrecision:2,
//															isMoney:true,
															fieldLabel : '订金(元)',
															name : 'dingJinFee',
															reference : 'dingJinFeeRef',
															labelWidth : 110,
															width : 220,
															readOnly : true,
														} ]
													},{
														margin : '5 0',
														xtype : 'container',
														layout : 'hbox',
														defaults : {
															flex : 1,
															labelAlign : "left",
														},
														items : [ {
															xtype : 'numberfield',
															decimalPrecision:2,
//															isMoney:true,
															fieldLabel : '应收首付款总金额(元)',
															name : 'totalAmountReceivableForFirstPayment',
															labelWidth : 84,
															width : 200,
															margin : '0 20',
															format: 'Y-m-d',
															readOnly : true,
														},
														{
															xtype : 'numberfield',
															decimalPrecision:2,
//															isMoney:true,
															fieldLabel : '装潢费用(元)',
															name : 'decorationFee',
															labelWidth : 110,
															width : 220,
															readOnly : true,
														} ]
													},
													{
														margin : '5 0',
													xtype : 'container',
													layout : 'hbox',
													defaults : {
														flex : 1,
														labelAlign : "left",
													},
													items : [ {
														xtype : 'textfield',
														fieldLabel : '备注',
														name : 'remark',
															labelWidth : 80,
															width : 410,
															margin : '0 20',
															readOnly : true,
													} ]
												} ]
									},
									{
										flex : 1,
										xtype : 'fieldset',
										align : 'left',
										autoScroll : true,
										reference : 'customerFieldset',
										layout : 'vbox',
										bodyPadding : 10,
										collapseDirection : 'top',
										collapsed : false,
										collapsible : true,
										title : "客户信息",
										margin:10,
										items : [
												{
													xtype : 'container',
													layout : 'hbox',
													margin : '5 0',

													defaults : {
														flex : 1,
														labelAlign : "left",
													},

													items : [
															{
																xtype : 'textfield',
																name : 'customerCode',
																itemId : 'cusCode',
																hidden : true,
																allowBlank : false,

															},
															{
																xtype : 'textfield',
																fieldLabel : '姓名',
																name : 'customerName',
																itemId : 'cusName',
																reference : 'customerNameRef',
																readOnly : true,
																labelWidth : 80,
																width : 180,
																margin : '0 20',
																allowBlank : false,
															},
															{
																xtype : 'textfield',
																fieldLabel : '手机号码',
																readOnly : true,
																name : 'customerPhone',
																reference : 'phone',
																itemId : 'phone',
																labelWidth : 80,
																width : 180,
																allowBlank : false,
															} ]
												},
												{
													margin : '5 0',
													xtype : 'container',
													layout : 'hbox',
													defaults : {
														flex : 1,
														labelAlign : "left",
													},
													items : [
															{

																xtype : 'combobox',
																fieldLabel : '客户类型',
																name : 'customerType',
																itemId : "gender",
																labelWidth : 80,
																width : 180,
																forceSelection : true,
																readOnly : true,
																editable : false,
																margin : '0 20'
															},
															{
																xtype : 'textfield',
																fieldLabel : '联系人:',
																readOnly : true,
																name : 'otherContacts',
																itemId : 'otherContacts',
																labelWidth : 80,
																width : 180,
															}

													]
												},{

													margin : '5 0',
													xtype : 'container',
													layout : 'hbox',
													defaults : {
														flex : 1,
														labelAlign : "left",
													},
													items : [
															{

																xtype : 'combobox',
																fieldLabel : '性别',
																name : 'customerSex',
																itemId : "gender",
																labelWidth : 80,
																width : 180,
																valueField : "code",
																displayField : "nameCn",
																queryModel : 'local',
																forceSelection : true,
																editable : false,
																readOnly : true,
																store : Ext
																		.create(
																				'Ext.data.Store',
																				{
																					autoLoad : true,
																					fields : [
																							'code',
																							'nameCn' ],
																					proxy : {
																						type : 'direct',
																						directFn : chooseOptionContro.getChooseOptionWithBlank,
																						extraParams : {
																							type : 'sexType'
																						}
																					}
																				}),
																margin : '0 20'
															},
															{
																xtype : 'textfield',
																fieldLabel : '身份证号码',
																name : 'customerCid',
																readOnly : true,
																itemId : 'customerCid',
																labelWidth : 80,
																width : 180,
																allowBlank : false,
															}

													]
												},
												{
													margin : '5 0',
													xtype : 'container',
													readOnly : true,
													layout : 'hbox',
													defaults : {
														flex : 1,
														labelAlign : "left",
													},
													items : [
															{
																xtype : 'textfield',
																fieldLabel : '邮箱',
																name : 'email',
																itemId : 'email',
																readOnly : true,
																labelWidth : 80,
																width : 180,
																margin : '0 20'
															// height:30,

															},
															{
																margin : '5 0',
																xtype : 'container',
																layout : 'hbox',
																defaults : {
																	flex : 1,
																	labelAlign : "left",
																},
																items : [ {
																	xtype : 'textfield',
																	readOnly : true,
																	fieldLabel : '联系人地址:',
																	name : 'address',
																	itemId : 'address',
																	labelWidth : 80,
																	width : 180,
																	allowBlank : false,
																// height:30,

																}

																]
															}

													]
												},
												{
													margin : '5 0',
													xtype : 'container',
													layout : 'hbox',
													defaults : {
														flex : 1,
														labelAlign : "left",
													},
													items : [
															{

																xtype : 'combobox',
																fieldLabel : '婚姻状况',
																name : 'maritalStatus',
																itemId : "maritalStatus",
																labelWidth : 80,
																width : 180,
																valueField : "code",
																displayField : "nameCn",
																queryModel : 'local',
																forceSelection : true,
																editable : false,
																readOnly : true,
																store : Ext
																		.create(
																				'Ext.data.Store',
																				{
																					autoLoad : true,
																					fields : [
																							'code',
																							'nameCn' ],
																					proxy : {
																						type : 'direct',
																						directFn : chooseOptionContro.getChooseOptionWithSelect,
																						extraParams : {
																							type : 'marryType'
																						}
																					}
																				}),
																margin : '0 20'
															},
															{
																xtype : 'textfield',
																fieldLabel : '家庭人数',
																name : 'familyNumber',
																itemId : 'familyNumber',
																readOnly : true,
																labelWidth : 80,
																width : 180,
															}

													]
												},
												{
													margin : '5 0',
													xtype : 'container',
													layout : 'hbox',
													defaults : {
														flex : 1,
														labelAlign : "left",
													},
													items : [
															{
																xtype : 'textfield',
																fieldLabel : '学历',
																readOnly : true,
																labelWidth : 80,
																width : 180,
																name : 'education',
																itemId : 'education',
																margin : '0 20'
															// height:30,

															},
															{
																xtype : 'textfield',
																fieldLabel : '住宅地址',
																name : 'residentialAddress',
																readOnly : true,
																itemId : 'residentialAddress',
																labelWidth : 80,
																width : 180,
															}

													]
												},
												{
													margin : '5 0',
													xtype : 'container',
													layout : 'hbox',
													defaults : {
														flex : 1,
														labelAlign : "left",
													},
													items : [
															{
																xtype : 'textfield',
																fieldLabel : '住宅邮编',
																readOnly : true,
																name : 'residentialZipCode',
																itemId : 'residentialZipCode',
																labelWidth : 80,
																width : 180,
																margin : '0 20'
															// height:30,

															},
															{
																xtype : 'textfield',
																fieldLabel : '住宅电话',
																name : 'telphone',
																readOnly : true,
																itemId : 'telphone',
																labelWidth : 80,
																width : 180,
															}

													]
												}

										]
									},
									{
										flex : 1,
										xtype : 'fieldset',
										align : 'left',
										autoScroll : true,
										reference : 'carProductFieldset',
										layout : 'vbox',
										bodyPadding : 10,
										collapsed : false,
										collapsible : true,
										collapseDirection : 'top',
										title : "产品信息",
										margin:10,
										items : [
												{
													xtype : 'container',
													layout : 'vbox',
													margin : '5 0',
													defaults : {
														flex : 1,
														labelAlign : "left",
														margin : '0 0 0 20'
													},
													items : [
															{
																xtype : 'container',
																layout : 'hbox',
																margin : '10 0',
																defaults : {
																	flex : 1,
																	labelAlign : "left",
																},
																items : [
																		{
																			xtype : 'textfield',
																			itemId : 'carProductCode',
																			name : 'carProductCode',
																			allowBlank : false,
																			hidden : true,
																		},{
																			xtype : 'textfield',
																			itemId : 'contractCarCode',
																			name : 'contractCarCode',
																			reference : 'contractCarCodeRef',
																			allowBlank : false,
																			hidden : true,
																		},
																		{
																			xtype : 'textfield',
																			fieldLabel : '产品名称',
																			itemId : 'carProductItemId',
																			name : 'contractCarName',
																			width : 670,
																			labelWidth : 120,
																			margin : '0 20',
																			allowBlank : false,
																			readOnly : true,
																		},
																		]
															},
															{
																xtype : 'container',
																layout : 'hbox',
																margin : '10 0',
																defaults : {
																	flex : 1,
																	labelAlign : "left",
																},
																	items : [ {
																		xtype : 'numberfield',
																		decimalPrecision:0,
																		fieldLabel : '期限（年）',
																		width : 250,
																		labelWidth : 120,
																		margin : '0 20',
																		readOnly : true,
																		itemId : 'leaseTerm',
																		name : 'leaseTerm',
																	},
																	{
																		xtype : 'numberfield',
																		decimalPrecision:0,
																		fieldLabel : '数量',
																		width : 400,
																		labelWidth : 230,
																		itemId : 'orderCount',
																		name : 'orderCount',
																		regex : /^[1-9]\d*$/,
																		readOnly : true,
																	} ]
															},
																{
																	xtype : 'container',
																	layout : 'hbox',
																	margin : '10 0',
																	defaults : {
																		flex : 1,
																		labelAlign : "left",
																	},
																	items : [
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '保证金（元）',
																				width : 250,
																			labelWidth : 120,
																			margin : '0 20',
																				readOnly : true,
																				itemId : 'deposit',
																				name : 'deposit',

																			},
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '期满购买价格（元）',
																				width : 400,
																			labelWidth : 230,
																				readOnly : true,
																				itemId : 'expirePrice',
																				name : 'expirePrice',

																			}
																			]
																},
																{
																	xtype : 'container',
																	layout : 'hbox',
																	margin : '10 0',
																	defaults : {
																		flex : 1,
																		labelAlign : "left",
																	},
																	items : [
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '月租费（元）',
																				width : 250,
																			labelWidth : 120,
																			margin : '0 20',
																				readOnly : true,
																				itemId : 'monthlyRent',
																				name : 'monthlyRent',
																			},
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '超出里程费用（元/公里）',
																				width : 400,
																			labelWidth : 230,
																				readOnly : true,
																				itemId : 'outOfRangFee',
																				name : 'outOfRangFee',
																			} ]
																},
																{
																	xtype : 'container',
																	layout : 'hbox',
																	margin : '10 0',
																	defaults : {
																		flex : 1,
																		labelAlign : "left",
																	},
																	items : [
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '提车服务费（元）',
																				width : 250,
																			labelWidth : 120,
																				margin : '0 20',
																				readOnly : true,
																				itemId : 'liftTheFare',
																				name : 'liftTheFare',
																			},
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '保险费用及充电桩使用服务费（元）',
																				width : 400,
																			labelWidth : 230,
																				readOnly : true,
																				reference : 'monthlyManagementFeeRef',
																				itemId : 'monthlyManagementFee',
																				name : 'monthlyManagementFee',
																			}
																			]
																},
																{
																	xtype : 'container',
																	layout : 'hbox',
																	margin : '10 0',
																	defaults : {
																		flex : 1,
																		labelAlign : "left",
																	},
																	items : [
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '充电桩费用（元）',
																			width : 250,
																			labelWidth : 120,
																				margin : '0 20',
																				readOnly : true,
																				reference : 'chargeFeeRef',
																				itemId : 'chargeFee',
																				name : 'chargeFee',
																			},
																			{
																				xtype : 'numberfield',
																				decimalPrecision:2,
//																				isMoney:true,
																				fieldLabel : '充电桩费用（元）',
																				width : 400,
																			labelWidth : 230,
																				margin : '0 20',
																				readOnly : true,
																				hidden : true,
																				reference : 'financialPackageCodeRef',
																				itemId : 'financialPackageCode',
																				name : 'financialPackageCode',
																			},
																			 ]
																},
														]

												// ///asdsad
												}, ]
									},

									{
										xtype : 'tabpanel',
										//layout : 'fit',
										activeTab : 0,
										//plain : true, // True表示tab候选栏上没有背景图片（默认为false）
										enableTabScroll : true, // 选项卡过多时，允许滚动
										reference : 'orderDetailTab',
										items : [ {
											xtype : 'panel',
											title : '车辆及保险信息',
											reference:'carDetailPanel',
											layout : {
												type : 'vbox',
												align : 'stretch'
											},
											items : [ {
												xtype : 'gridpanel',
												reference : 'contractCarOrderDetailGrid',
												itemId:'contractCarOrderDetailItem',
												bind : '{contractCarOrderDetailListStore}',
												border : false,
												viewConfig : {
													emptyText : '暂无车辆及保险信息！',
													enableTextSelection : true
												},
												columns : [ {
													xtype: 'actioncolumn',
									                width: 50,
									                sortable: false,
									                menuDisabled: true,
									                text : '操作',
									                align : "center",
									                items: [{
									                	text: '附件',
									                    icon: 'images/upload.png',
									                    tooltip: '查看车辆及保险信息附件',
									                    handler: 'onUploadCarBXClick'
									                }]
												}, {
													dataIndex : 'id',
													hidden : true,
												},{
													dataIndex : 'contractCarOrderId',
													hidden : true,
												},{
													dataIndex : 'olPreSaleOrderNo',
													hidden : true,
												},{
													dataIndex : 'carProductDisplayName',
													hidden : true,
												},{
													text : '名称',
													dataIndex : 'carProductName',
												},{
													text : '补充协议编号',
													dataIndex : 'suppleAgreementNo',
													align : 'center'
												}, {
													text : '车架号',
													dataIndex : 'carFrameNo',
													align : 'center',
												}, {
													text : '发动机号',
													dataIndex : 'carEngineNo',
													align : 'center'
												}, {
													text : '车牌号码',
													dataIndex : 'carLicensePlate',
													align : 'center'
												}, {
													text : '行驶证号',
													dataIndex : 'carDriveLicenseNo',
													align : 'center'
												}, {
													text : '初始公里程数',
													dataIndex : 'initMileage',
													align : 'center',
													regex : /^[0-9]+(\.[0-9]{2})?$/,
												}, {
													text : '保险公司',
													dataIndex : 'insuranceCompany',
													align : 'center',
													renderer:'insuranceCompanyEditor'
												}, {
													text : '交强险起始日期',
													dataIndex : 'strongInsuranceStartDate',
													align : 'center',
													renderer:function(value){ 
								                    	if(value==null){
								                    		return "";
								                    	}else{
								                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
								                    	}
								                    }
												}, {
													text : '交强险终止日期',
													dataIndex : 'strongInsuranceEndDate',
													align : 'center',
													renderer:function(value){ 
								                    	if(value==null){
								                    		return "";
								                    	}else{
								                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
								                    	}
								                    }
												}, {
													text : '商业险起始日期',
													dataIndex : 'commercialInsuranceStartDate',
													align : 'center',
													renderer:function(value){ 
								                    	if(value==null){
								                    		return "";
								                    	}else{
								                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
								                    	}
								                    }
												}, {
													text : '商业险终止日期',
													dataIndex : 'commercialInsuranceEndDate',
													align : 'center',
													renderer:function(value){ 
								                    	if(value==null){
								                    		return "";
								                    	}else{
								                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
								                    	}
								                    }
												}, {
													text : 'GPS设备编号',
													dataIndex : 'gpsDeviceNo',
													align : 'center'
												},

												],
											} ]

										},{
											xtype : 'panel',
											title : '合同信息',
											//layout : 'vbox',
											border : false,
											tbar : [ 
												//{
												//	xtype : 'button',
												//	text : '新增',
												//	iconCls : 'common-icon-add',
												//	listeners : {
												//		click : 'onAddContractCarBCYXtClick'
												//	}
												//}, 
//												{
//													xtype : 'button',
//													text : '保存',
//													iconCls : 'common-icon-save',
//													listeners : {
//														click : 'onSaveContractCarBCYXtClick'
//													}
//												},
												{
													xtype : 'button',
													text : '租赁合同附件',
													listeners : {
														click : 'onUploadContractAttachemetClick'
													}
												},
												{
													xtype : 'button',
													text : '租赁合同下载',
													iconCls : 'pdf',
													listeners : {
														click : 'onDownContractClick'
													}
												}
											],
											items : [ {
												xtype : 'panel',
												layout : {
													type : 'vbox',
													align : 'stretch'
												},
												border : false,
												margin : "10px 0 0 0",
												items : [ {
													xtype : 'gridpanel',
													reference : 'contractCarSuppleAgreementGrid',
													bind : '{contractCarSuppleAgreementListStore}',
													margin : "0 0 10px 10px",
													autoScroll : 'true',
													viewConfig : {
														emptyText : '暂无补充协议信息！',
														enableTextSelection : true
													},
										            plugins:[
										                Ext.create('Ext.grid.plugin.CellEditing',{
										                	clicksToEdit:1
										                })
										            ],
													columns : [ {
														xtype: 'actioncolumn',
										                width: 80,
										                sortable: false,
										                menuDisabled: true,
										                text : '操作',
										                align : "center",
										                items: [{
										                    icon: 'images/upload.png',
										                    tooltip: '查看补充协议附件',
										                    handler: 'onUploadBCXYClick'
										                }, 
										                {
										                    icon: 'images/printer.png',
										                    tooltip: '打印补充协议',
										                    handler: 'onPrintBCXYClick'
										                }
										                ]
													},{
														dataIndex : 'id',
														hidden : true,
													},{
														dataIndex : 'contractCarOrderId',
														hidden : true,
													},{
														dataIndex : 'olPreSaleOrderNo',
														hidden : true,
													},{
														text : '补充协议编号',
														dataIndex:'suppleAgreementNo',
														align : 'center',
													}, {
														text : '签订日期',
														dataIndex:'signDate',
														align : 'center',
														renderer:function(value){ 
									                    	if(value==null){
									                    		return "";
									                    	}else{
									                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
									                    	}
									                    }
													}, {
														text : '开始日期',
														dataIndex:'startDate',
														align : 'center',
														renderer:function(value){ 
									                    	if(value==null){
									                    		return "";
									                    	}else{
									                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
									                    	}
									                    }
													}, {
														text : '结束日期',
														dataIndex:'endDate',
														align : 'center',
														renderer:function(value){ 
									                    	if(value==null){
									                    		return "";
									                    	}else{
									                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
									                    	}
									                    }
													}, {
														text : '银行卡户名',
														dataIndex : 'bankAccountName',
														align : 'center',
													}, {
														text : '银行卡帐号',
														dataIndex : 'bankAccountNo',
														align : 'center',
													}, {
														text : '银行卡开户行',
														dataIndex : 'bankOpenPlace',
														align : 'center',
													}, {
														text : '车架号',
														dataIndex : 'carFrameNo',
														align : 'center',
													}, {
														text : '车牌号码',
														dataIndex : 'carLicensePlate',
														align : 'center',
													} ]
												},
												{
											        xtype: 'gridpanel',
											        width:'100%',
													reference:'contractattachmentGrid',
											        bind:'{contractattachmentStore}',
											        columns: [
											                 	{dataIndex:'id',hidden:true}, 
											                 	{ text: '单据类型',  dataIndex: 'bizEntityTypeName'},
											                 	{ dataIndex:'bizEntityType',hidden:true},
											                    { text: '单据编码',  dataIndex: 'bizEntityCode'},
											                    { text: '附件名称',dataIndex:'linkName',
											                    	renderer:function(value,cellmeta,record){
											                    		if(value!=null&&value!=''){
											                    			return "<a href='"+record.data.resourceAccessUrl+"' target='_blank'>"+value+"</a>";
											                    		}
											                    	}},
											                    { text: '附件类型', dataIndex:'attachBizType',
											                    	renderer:function(value){
											                    		if(value != null){
											    	                		var gridStore = this.up('#OrderListDetails').getViewModel().getStore('contractattachmentTypeStore');
											    	                		return gridStore.findRecord('code', value).data.nameCn;
											    	                	}
											                    	}
											                    },
											                    {text:'上传时间',dataIndex:'createDate',
											                    	renderer: function(value) {
																		if(value == null) {
																			return "";
																		} else {
																			return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
																		}
																	}
											                    },
											                    {text:'备注',dataIndex:'description'},
									                ],
												}
												]
											} ]
										},{
											//layout : 'fit',
											xtype : 'panel',
											title : '支付信息',
											reference:'payinfo',
											items : [ {
												layout : 'hbox',
												xtype : 'gridpanel',
												border : false,
												margin : '5px 0',
												reference : 'contractCarOrderPayLogGrid',
												itemId : 'contractCarOrderPayLogGrid',
												bind : '{contractCarOrderPayLogListStore}',
												viewConfig : {
													emptyText : '暂无支付信息！',
													enableTextSelection : true
												},
												columns : [{
															xtype: 'actioncolumn',
											                width: 80,
											                sortable: false,
											                menuDisabled: true,
											                text : '操作',
											                align : "center",
											                items: [
											                {
											                	iconCls: 'common-icon-upload',
											                	 tooltip: '查看支付信息附件',
											                	 handler: 'onUploadContractCarOrderPayClick'
											                }]
														},
														{
															dataIndex : 'id',
															hidden : true,
														},
														{
															dataIndex : 'contractCarOrderId',
															hidden : true,
														},
														{
															text : '编号',
															dataIndex : 'payNo',
															align : 'center',
															name:'payNo',
														},
														{
															xtype : 'gridcolumn',
															text : '支付类型',
															dataIndex : 'payType',
															align : 'center',
															name:'payType',
															hidden: false,
										                	renderer: 'orderPayTypeEditor',
														},
														{
															text : '支付方式',
															dataIndex : 'payChannel',
															align : 'center',
															name:'payChannel',
										                	renderer: 'orderPayChannelEditor',
														},
														{
															text : '金额',
															dataIndex : 'payAmount',
															align : 'center',
															name:'payAmount',
//															formatter: 'usMoney',
															regex : /^[0-9]+(\.[0-9]{2})?$/,
														},
														{
															text : '支付日期',
															dataIndex : 'payTime',
															align : 'center',
															name:'payTime',
															renderer:function(value){ 
										                    	if(value==null){
										                    		return "";
										                    	}else{
										                    		return	Ext.Date.format(new Date(value), 'Y-m-d')
										                    	}
										                    }
														},
														{
															text : '备注',
															dataIndex : 'remark',
															align : 'center',
															name:'remark',
														},
														 ],
											},
											]
										}, 
										{
											title : '征信材料',
											xtype : "panel",
											//layout : 'auto',
											border : false,
											// buttonAlign:'left',
											items : [ {
												xtype : 'panel',
												layout : {
													type : 'vbox',
													align : 'stretch'
												},
												border : false,
												margin : "10px 0 0 0",
												items : [ 
												{
											        xtype: 'gridpanel',
											        width:'100%',
													reference:'creditattachmentGrid',
											        bind:'{creditattachmentStore}',
											        columns: [
											                 	{dataIndex:'id',hidden:true}, 
											                 	{ text: '单据类型',  dataIndex: 'bizEntityTypeName'},
											                 	{ dataIndex:'bizEntityType',hidden:true},
											                    { text: '单据编码',  dataIndex: 'bizEntityCode'},
											                    { text: '附件名称',dataIndex:'linkName',
											                    	renderer:function(value,cellmeta,record){
											                    		if(value!=null&&value!=''){
											                    			return "<a href='"+record.data.resourceAccessUrl+"' target='_blank'>"+value+"</a>";
											                    		}
											                    	}},
											                    { text: '附件类型', dataIndex:'attachBizType',
											                    	renderer:function(value){
											                    		if(value != null){
											    	                		var gridStore = this.up('#OrderListDetails').getViewModel().getStore('creditattachmentTypeStore');
											    	                		return gridStore.findRecord('code', value).data.nameCn;
											    	                	}
											                    	}
											                    },
											                    {text:'上传时间',dataIndex:'createDate',
											                    	renderer: function(value) {
																		if(value == null) {
																			return "";
																		} else {
																			return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
																		}
																	}
											                    },
											                    {text:'备注',dataIndex:'description'},
									                ],
												}
												]
									        } ],

										},
										{
											title : '还款计划',
											xtype : "panel",
											border:false,
											padding:10,
											items : [{
												xtype : 'gridpanel',
												autoScroll : 'true',
												buttonAlign : 'left',
												reference : 'replaymentPlanGrid',
												bind : '{replaymentPlanListStore}',
												viewConfig : {
													emptyText : '暂无信息！',
													enableTextSelection : true
												},
												columns : [ {
													dataIndex: 'numberOfPeriods',
													text : '期数',
													align : 'center', flex:3,
												}, {
													dataIndex: 'startDate',
													text : '租金开始日期',
													align : 'center', flex:2,
												}, {
													dataIndex: 'endDate', flex:2,
													text : '租金结束日期',
													align : 'center', flex:2,
												}, {
													dataIndex: 'monthlyAmount', flex:2,
													text : '月供金额',
													align : 'center', flex:2,
												}, {
													dataIndex: 'deductionPlanDate',
													text : '扣款计划', flex:2,
													align : 'center',
												} ],
											} ]
										}

										]
									},
					        ],
					} ]

				})