/*
 * File: app/view/menu/menuPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.orderList.OrderListAttachmentWinViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.orderlistattachmentwin',
    
    onAttachmentBizEntityTypeSelWithAll: function(me,record){
    	//var type = "brand_"+ record;
    	var type = record;
    	var extraParams = {type : type};
    	var attachBizTypeCobo = this.lookupReference('attachBizTypeCobo');
    	var attachBizTypeCoboStore = attachBizTypeCobo.getStore();
    	
    	attachBizTypeCoboStore.on("beforeload", function (attachBizTypeCoboStore, operation, eOpts) {
			 Ext.apply(attachBizTypeCoboStore.proxy.extraParams, extraParams);
		});
    	attachBizTypeCoboStore.load();
    },
});
