/*
 * File: app/store/Persons.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.store.Persons', {
    extend: 'Ext.data.Store',

    requires: [
        'Evcorp.model.Person'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Persons',
            model: 'Evcorp.model.Person',
            data: [
                {
                    realName: 'autem',
                    wechatOpenId: 123456,
                    nickName: 'et',
                    sex: '男',
                    city: '上海',
                    country: '上海',
                    province: '上海',
                    headimgurl: 'molestiae',
                    subscribeTime: '1/15/2014',
                    mobileNumber: '13545131270',
                    carModel: 'E50',
                    carBrand: '荣威',
                    licensePlateNumber: '沪A88888',
                    carYear: 1,
                    driveYear: 4,
                    createTime: '4/11/2009',
                    createBy: 'dolorum',
                    lastestUpdateTime: 530,
                    lastestUpdateBy: 'quaerat'
                },
                {
                    realName: 'aut',
                    wechatOpenId: 89654123,
                    nickName: 'consequatur',
                    sex: '女',
                    city: '上海',
                    country: '上海',
                    province: '上海',
                    headimgurl: 'odit',
                    subscribeTime: '11/20/2014',
                    mobileNumber: '13545131270',
                    carModel: 'E50',
                    carBrand: '荣威',
                    licensePlateNumber: '沪A88888',
                    carYear: 9,
                    driveYear: 6,
                    createTime: '2/25/2009',
                    createBy: 'ut',
                    lastestUpdateTime: 55,
                    lastestUpdateBy: 'aut'
                }
            ]
        }, cfg)]);
    }
});