/*
 * File: app/view/menu/menuPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.menu.MenuPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.menupanelviewcontr',

    control: {
    	'#': {
        	afterrender: 'onMenuAfterrender'
        }
    },

    menuAssemble: function(jsonParam, component, menuPanel) {
        Ext.each(jsonParam,function(obj,index){
            var subPanel = Ext.create('Ext.Panel',{
                title:obj.text,
                icon:obj.icon,
                border:0,
                border: false,
                layout :'fit',
                border: 0,
                items:[{
                    xtype:'menu',
                    border: 0,
                    border: false,
                    border:0,
                    border: false,
                    floating: false
                }]
            });
          
            //遍历第一层children,创建menuItem
            if(obj.children){
                Ext.each(obj.children,function(obj1,index1){
                    var menuItem = Ext.create('Ext.menu.Item',{
                        text:obj1.text,
                        icon:obj1.icon,
                        margin:'0 25'
                    });
                    
                    menuItem.on('click',function(){
		                  if(obj1.children.length!=0){
		                         var workSpace = Ext.create('Ext.tab.Panel',{
				                        param:obj1.children,
				                        width:600,
				                        height:400,
				                        defaults :{
				                            bodyPadding: 10
				                        },
				                        items:[
				                            {
				                                title:'子功能列表',
				                                itemId:'list'
				                            }
				                        ]
		                        });
		                    this.up('panel').up('viewport').getController().workSpaceAssemble(workSpace.param,workSpace,component);
		                }else{
		                	var path = obj1.path;
		                	var text = obj1.text;
		                	this.up('panel').up('panel').up('panel').getController().newWorkSpace(component,path,text);
		                	//this.up('panel').up('panel').getController().newWorkSpace(component,path,text);
		                	//this.up('panel').up('panel').getController().newWorkSpace(component,path,text);
		                	//this.newWorkSpace(component,path,text);
		                }
                    });
                    subPanel.down('menu').add(menuItem);
                });
            }
            menuPanel.add(subPanel);
        });
       // component.down('#menuPanel').add(menuPanel);
    },
    
    newWorkSpace:function(component,path,text){
        var className = 'Evcorp.view.'+path;
        var contentPanel = component;
        var flag;
        var functionTab = Ext.create(className,{
        	title:text
        });
        Ext.each(contentPanel.items.items,function(obj3,index3){
            if(obj3.itemId == functionTab.itemId){
            	contentPanel.setActiveTab(obj3);
                flag = 1;
            }
        });
        if(flag!=1){
        	contentPanel.add(functionTab);
        	contentPanel.setActiveTab(functionTab);
        }
    },
    
    workSpaceAssemble: function(workSpaceParam, workSpace, component) {
        var viewCard = Ext.create('Ext.view.View',{
            store:'UsersStore',
            tpl:new Ext.XTemplate(
                '<tpl for=".">',
                '<div style="margin: 10px 10px;float:left;width:140px;height:80px;background:#6CA6CD" class="thumb-wrap" >',
                      '<span>{text}</span>',
                    '</div>',
                '</tpl>'
            ),
            itemSelector:'div.thumb-wrap'

        });
        viewCard.store.loadData(workSpaceParam);
    workSpace.down('#list').add(viewCard);
          component.down('#contentPanel').add(workSpace);
    

    viewCard.on('itemclick',function(view,record,item,index){
        if(record.data.children){
            var subViewCard = Ext.create('Ext.view.View',{
                store:'UsersStore',
                tpl:new Ext.XTemplate(
                '<tpl for=".">',
                '<div style="margin: 10px 10px;float:left;width:140px;height:80px;background:#6CA6CD" class="thumb-wrap" >',
                      '<span>{text}</span>',
                    '</div>',
                '</tpl>'
                ),
                itemSelector:'div.thumb-wrap'
            });
            subViewCard.store.loadData(record.data.children);
            workSpace.down('#list').removeAll();
            workSpace.down('#list').add(subViewCard);

        }else{
            var flag;
            var functionTab = Ext.create('Ext.Panel',{
                html:'<span>这是'+record.data.text+'的工作区</span>',
                title:record.data.text,
                itemId:index
            });
            Ext.each(workSpace.items.items,function(obj3,index3){
                if(obj3.itemId == functionTab.itemId){
                    workSpace.setActiveTab(obj3);
                    flag = 1;
                }

            });
            if(flag!=1){
            workSpace.add(functionTab);
            workSpace.setActiveTab(functionTab);
            }
        }
    });
},
    
    onMenuAfterrender: function(component, eOpts) {
    	var tabPanel = Ext.ComponentQuery.query("viewport tabpanel")[0];
   	    var menuPanel = this.getView();
   	    sysFunction.findMenus(function(result,status){
	 	    this.Evcorp.view.menu.MenuPanelViewController.prototype.menuAssemble(result.children,tabPanel,menuPanel);
   	    });
   }

});
