/*
 * File: app/view/role/RoleMangerPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.callcar.callCarMoney', {
	extend : 'Ext.panel.Panel',
	alias : 'widget.callCarMoney',
	requires : [ 
		        'Evcorp.view.callcar.callCarMoneyViewController',
				'Evcorp.view.callcar.callCarMoneyViewModel',
				'Ext.grid.Panel', 'Ext.tab.Panel', 'Ext.grid.column.Column',
				'Ext.grid.View', 'Ext.toolbar.Toolbar', 'Ext.button.Button',
				'Ext.toolbar.Fill', 'Ext.form.Panel', 'Ext.form.field.ComboBox',
				'Ext.form.DateField'
				],

	controller : 'callCarMoney',
	viewModel : {
		type : 'callCarMoney'
	},
	itemId:'callCarMoney',
	closable: true,
	referenceHolder: true,
	autoScroll: true,
	height: "100%",
	items: [{
		xtype: 'gridpanel',
		bind:'{callCarDemandReportStore}',
		viewConfig: { enableTextSelection: true },
		reference:'reportGrid',
		forceFit:true,
		features: [{
            ftype: 'summary'
        }],
		columns: [{
			text: '供应商',
			dataIndex: 'venderName',
			align: 'center',
			width:220,
			summaryType:'count',
			summaryRenderer:function(value, summaryData, dataIndex){
				return '合计:';
			}
		}, {
			text: 'Call车专员',
			dataIndex: 'creator',
			align: 'center'
		}, {
			text: '车辆数',
			dataIndex: 'totalQuantity',
			align: 'center',
			summaryType:'sum'
		}, {
			text: '已提交审批未付款',
			dataIndex: 'notPaidQuantity',
			align: 'center',
			summaryType:'sum'
		}, {
			text: '已付款未发货',
			dataIndex: 'notDeliveryQuantity',
			align: 'center',
			summaryType:'sum'
		}, {
			text: '车辆在途',
			dataIndex: 'inTransitQuantity',
			align: 'center',
			summaryType:'sum'
		}, {
			text: '已付款金额',
			dataIndex: 'paidAmount',
			align: 'center',
			summaryType:'sum',
			renderer:function(value){
				return '￥'+Ext.util.Format.number(value,'0,000');
			},
			summaryRenderer:function(value, summaryData, dataIndex){
				return '￥'+Ext.util.Format.number(value,'0,000');
			}
		}, {
			text: '未付款金额',
			dataIndex: 'notPaidAmount',
			align: 'center',
			summaryType:'sum',
			renderer:function(value){
				return '￥'+Ext.util.Format.number(value,'0,000');
			},
			summaryRenderer:function(value, summaryData, dataIndex){
				return '￥'+Ext.util.Format.number(value,'0,000');
			}
		}, {
			text: '总金额',
			dataIndex: 'totalAmount',
			align: 'center',
			summaryType:'sum',
			renderer:function(value){
				return '￥'+Ext.util.Format.number(value,'0,000');
			},
			summaryRenderer:function(value, summaryData, dataIndex){
				return '￥'+Ext.util.Format.number(value,'0,000');
			}
		}, 
		],
		/*dockedItems: [{
        	 xtype: 'toolbar',
        	 dock: 'top',
        	 items: [
        	         {
        	     		xtype: 'form',
        	     		layout: 'hbox',
        	     		reference:'searchForm',
        	     		border:false,
        	     		items: [{
        	     			xtype: 'datefield',
        	     			fieldLabel: '提交日期',
        	     			name: 'submitDateFrom',
        	     			labelWidth: 70,
        	     			width: 250,
        	     			editable:false,
        	     			format: 'Y-m-d',
        	     			margin: '10 20 10 0',
        	     			value : Ext.util.Format.date(new Date(), "Y-m-") + '01'
        	     		}, {
        	     			xtype: 'datefield',
        	     			fieldLabel: '至',
        	     			name: 'submitDateTo',
        	     			labelWidth: 40,
        	     			width: 220,
        	     			editable:false,
        	     			format: 'Y-m-d',
        	     			margin: '10 20 10 0',
        	     			value : Ext.util.Format.date(new Date(), "Y-m-d")
        	     		},
        	     		]
        	         },
        	         {
        	        	 xtype: 'button',
        	        	 text: '查询',
        	        	 iconCls: 'common-icon-serach',
        	        	 handler: 'onQueryClick'
        	         }
        	        ]
         }]*/
	}]
})