/*
 * File: app/view/role/RoleMangerPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.callcar.flowChartPanel', {
	extend : 'Ext.panel.Panel',
	alias : 'widget.flowChartPanel',
	requires : [ 
		        'Evcorp.view.callcar.flowChartPanelViewController',
				'Evcorp.view.callcar.flowChartPanelViewModel',
				'Ext.grid.Panel', 'Ext.tab.Panel', 'Ext.grid.column.Column',
				'Ext.grid.View', 'Ext.toolbar.Toolbar', 'Ext.button.Button',
				'Ext.toolbar.Fill', 'Ext.form.Panel', 'Ext.form.field.ComboBox',
				'Ext.form.DateField'
				],

	controller : 'flowChartPanel',
	viewModel : {
		type : 'flowChartPanel'
	},
	itemId : 'flowChartPanel',
	layout : {
		type : 'vbox',
		align : 'stretch'
	},
	autoScroll:true,
	width:"100%",
	items : [{
              /*callcar on*/
              xtype:'panel',
              autoScroll:false,
                bodyPadding:'10',
                border:false,
              flex:1,
              text:'CALL车执行单详情',
              items: [{
                  xtype:'form',
                  reference:'detailForm',
                  columnWidth: 1,
                  padding:0,
                  margin:0,
                  defaultType: 'textfield',
                  layout: 'vbox',
                  flex:1,
                  items :[{
                        xtype:'panel',
                        layout: 'hbox',
                        border:false,
                        margin : '20 0 10 0',
                        items :[
                                    {
                                        xtype : 'textfield',
                                        fieldLabel : '编号',
                                        name : 'code',
                                        labelWidth : 80,
                                        width : 280,
                                        margin : '0 20',
                                        editable : false
                                    },
                                    {
                                        xtype : 'textfield',
                                        fieldLabel : '厂家订单号',
                                        name : 'venderOrderNo',
                                        labelWidth : 100,
                                        width : 280,
                                        margin : '0 10',
                                        editable : false
                                    },
                                    {
                                        xtype : 'textfield',
                                        fieldLabel : '购车量',
                                        name : 'orderQuantity',
                                        labelWidth : 90,
                                        width : 280,
                                        margin : '0 10',
                                        editable : false
                                    }
                                ]
                    },{
                        xtype:'panel',
                        layout: 'hbox',
                        margin : '10 0 20 0',
                        border:false,
                        
                        items :[
                                    {   
                                        xtype: 'panel',
                                        border:false,           
                                        width : 280,
                                        margin : '0 20',
                                        layout:'hbox',
                                        items: [{
                                                    xtype:'textfield',
                                                    width : 280,
                                                    labelWidth : 80,
                                                    fieldLabel: '生成日期',
                                                    name:'createDateString',
                                                    editable : false
                                                }]

                                    },
                                    {
                                        xtype : 'textfield',
                                        fieldLabel : '订单金额',
                                        name : 'orderAmount',
                                        labelWidth : 100,
                                        width : 280,
                                        margin : '0 10',
                                        editable : false
                                    },{
                                        xtype : 'textfield',
                                        fieldLabel : '创建人',
                                        name : 'createBy',
                                        labelWidth : 100,
                                        width : 280,
                                        margin : '0 10',
                                        editable : false
                                    }]
                    },{
                        xtype:'panel',
                        layout: 'hbox',
                        border:false,
                        columns: 3,
                        margin : '20 0 10 0',
                        items :[ {
                                     xtype:'panel',
                                     border:false,
                                     layout:{
                                         type:'hbox',
                                         align:'left'
                                     },
                                     items:[
                                             {
                                                 xtype : 'textfield',
                                                 fieldLabel : '供应商编号',
                                                 name : 'venderCode',
                                                 labelWidth : 80,
                                                 width:280,
                                                 margin : '0 0 0 20',
                                                 editable : false
                                             }
                                     ]
                                  },
                                  {
                                      xtype : 'textfield',
                                      fieldLabel : '供应商',
                                      name : 'venderName',
                                      labelWidth : 100,
                                      width:280,
                                      margin : '0 20',
                                      editable : false
                                  },
                                  {
                                    xtype:'hidden',
                                    name:'taskId'
                                },
                                {
                                  xtype:'hidden',
                                  name:'processInstanceId'
                                }
                              ] 
                     }
                    ]
              }]
        },
          
          {
        xtype: 'gridpanel',
        buttonAlign:'center',
        bind:'{detailGrid}',
        columns: [
                    { text: '产品代码', align:'center' , dataIndex: 'carProductCode'},
                    { text: '品牌',  dataIndex: 'carBrandCode', flex:2},
                    { text: '车系', dataIndex: 'carSeriesCode', flex:3},
                    { text: '车型',align:'center' , dataIndex: 'carModelCode', flex:2,hidden:true},
                    { text: '产品名称', align:'center' , dataIndex: 'name', flex:2},
                    { text: '颜色', align:'center' , dataIndex: 'carColorCode', flex:1,hidden:true},
                    { text: '采购数量',  dataIndex: 'quantity', flex:2},
                    { text: '采购单价',  dataIndex: 'unitPrice', flex:3},
                    { text: '车辆用途', dataIndex:'carUsage', flex:2,
                    	renderer:function(value){
                    		if(value != null){
    	                		var gridStore = this.up('panel').getViewModel().getStore('carUsageStore');
    	                		return gridStore.findRecord('code', value).data.nameCn;
    	                	}
                    	}}
                    ],
  }]

});