/*
 * File: app/view/menu/menuPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.callcar.UpdateDeliveryStatusWinViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.UpdateDeliveryStatusWin',
    onUploadClick:function(){
		var taskId = this.lookupReference('flowChartPanel').lookupReference('detailForm').getForm().getValues().taskId;
    	var processInstanceId = this.lookupReference('flowChartPanel').lookupReference('detailForm').getForm().getValues().processInstanceId;
		var form = this.lookupReference('commentForm');
		form.submit({
			params : {
				taskId : taskId,
				processInstanceId : processInstanceId
			},
			waitMsg : '附件正在上传，请耐心等待....',
			success : function(form, action) {
				Ext.Msg.alert('提示','附件上传成功');
			},
			failure : function(form, action) {
				Ext.Msg.alert('提示',action.result.info);
			}
		});
    },
    onSubmitClick:function(){
    	var taskId = this.lookupReference('flowChartPanel').lookupReference('detailForm').getForm().getValues().taskId;
    	var processInstanceId = this.lookupReference('flowChartPanel').lookupReference('detailForm').getForm().getValues().processInstanceId;
    	var businessKey = this.lookupReference('flowChartPanel').lookupReference('detailForm').getForm().getValues().code;
    	var form = this.lookupReference('commentForm');
    	var comment = form.getForm().getValues().comment;
    	var venderOrderNo = form.getForm().getValues().venderOrderNo;
    	var deliveryNo = form.getForm().getValues().deliveryNo;
    	var deliveryDate = form.getForm().getValues().deliveryDate;
    	var expectedArriveDate = form.getForm().getValues().expectedArriveDate;
    	var win = this.getView();
    	var isValid = form.getForm().isValid();
    	if(isValid){
    		win.mask("请稍等，正在处理中...","x-mask-loading");
    		Ext.Ajax.request({
    			url : 'callCar/updateDeliveryAgree',
    			params : {
    				taskId : taskId,
    				processInstanceId : processInstanceId,
    				businessKey : businessKey,
    				comment : comment,
    				venderOrderNo : venderOrderNo,
    				deliveryNo : deliveryNo,
    				deliveryDate : deliveryDate,
    				expectedArriveDate : expectedArriveDate
    			},
                method: 'POST',	
    			success : function(data) {
    				win.unmask();
    				if(data.responseText=='success'){
    					Ext.Msg.alert("提示",'提交成功',function(){
        	    			var myActiveTaskGrid = Ext.ComponentQuery.query('#myActiveTaskGrid')[0];
        	    			var myActiveTaskStore = myActiveTaskGrid.getStore();
        	    			myActiveTaskStore.loadPage(1 ,{"start":0,"limit":20});
        	    			var eastPanel = Ext.ComponentQuery.query("#eastPanelId")[0];
    		    	        eastPanel.removeAll();
        	    			win.close();
        	    		});
    				}else if(data.responseText=='notUploadFile'){
    					Ext.Msg.alert("提示",'请上传发货单！')
    				}
    			}
    		});
    	}else{
			Ext.Msg.alert('提示','表单中存在格式不正确的字段或者空字段');
		}
    }
   
});
