/*
 * File: app/view/person/ActivateCardWindowViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.task.TaskAssignWindowViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.taskAssignWindowc',
    doAssign:function(){
    	var myActiveTaskGrid = Ext.ComponentQuery.query("#myActiveTaskGrid")[0];
    	var myActiveTaskStore = myActiveTaskGrid.getStore();
    	var sel = myActiveTaskGrid.getSelectionModel().getSelection();
    	var taskIds = [];
    	var map = {};
		Ext.each(sel,function(item){
			taskIds.push(item.data.taskId);
			map[item.data.taskId] = item.data.processInstanceId;
		});
    	var combo = Ext.ComponentQuery.query('#assignComboId');
    	var message = Ext.ComponentQuery.query('#messageId')[0].value;
		var userId = combo[0].value;
		var win = this.getView();
		if(userId!=null&&userId!=''){
			Ext.Ajax.request({
				url : 'task/changeAssignee',
				params : {
					taskIds : taskIds,
					userId : userId,
					message : message,
					map : JSON.stringify(map)
				},
	            method: 'POST',	
				success : function(data) {
					myActiveTaskStore.loadPage(1 ,{"start":0,"limit":20});
					win.close();
				}
			});
		}
    }
});
