/*
 * File: app/view/role/RoleMangerPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.task.TaskPanel', {
	extend: 'Ext.panel.Panel',
	alias: 'widget.taskpanel',

	requires: [
		'Evcorp.view.task.TaskPanelViewController',
		'Evcorp.view.task.TaskPanelViewModel',
		'Ext.grid.Panel',
		'Ext.tab.Panel',
		'Ext.grid.column.Column',
		'Ext.grid.View',
		'Ext.toolbar.Toolbar',
		'Ext.button.Button',
		'Ext.toolbar.Fill',
		'Ext.form.Panel',
		'Ext.form.field.ComboBox'
	],

	controller: 'taskpanelc',
	viewModel: {
		type: 'taskpanelvm'
	},
	referenceHolder: true,
	itemId: 'TaskPanel',
	closable: true,
	layout: {
		type: 'border',
		align: 'stretch'
	},
	height: "100%",
	items: [{
		region: "center",
		flex: 1,
		split: true,
		//height: "100%",
		xtype: "tabpanel",
		activeTab: 0,
		plain: true, //True表示tab候选栏上没有背景图片（默认为false）
		enableTabScroll: true, //选项卡过多时，允许滚动
		defaults: {
			autoScroll: true
		},
		items: [{
				xtype: "panel",
				title: "待办",
				layout:{
					type: 'vbox',
					align: 'stretch'
				},
				items: [{
					layout:{
						type: 'vbox',
						align: 'stretch'
					},
						xtype: 'panel',
						flex:1,
						title: '<div align="center">待办事项</div>',
						//autoScroll: true,
						tbar: ["->", {
								xtype: 'button',
								text: '指派',
								margin: "0 100px 0 0",
								border: false,
								listeners: {
									click: 'onAssignClick'
								}
							}, {
								xtype: 'button',
								text: '反签',
								border: false,
								listeners: {
									click: 'onUnclaimClick'
								}
							}

						],
						items: [{
							flex: 1,
							xtype: "gridpanel",
							border: false,
							selModel: {
								selType: 'checkboxmodel',
								mode: 'simple'
							}, 
							bind: '{myActiveTask}',
							listeners : {
								select : 'onActiveTaskSelected'
							},
							reference: 'myActiveTaskGrid',
							itemId:'myActiveTaskGrid',
							plugins: 'gridfilters',
							columns: [{
								xtype: 'gridcolumn',
								dataIndex: 'businessKey',
								align: 'center',
								text: '单据编号',
								filter:'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'businessTypeName',
								align: 'center',
								text: '单据类型',
								filter:'string'
							}, {
								xtype : 'hidden',
								dataIndex:'businessType'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'taskId',
								align: 'center',
								text: '任务ID',
								filter:'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'taskName',
								align: 'center',
								text: '任务名称',
								filter:'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'processInstanceId',
								align: 'center',
								text: '流程编号',
								filter:'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'processInstanceName',
								align: 'center',
								text: '流程名称',
								filter:'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'createTime',
								align: 'center',
								text: '任务发起时间',
								filter:'date',
								width: 200,
								renderer: function(value) {
									if(value == null) {
										return "";
									} else {
										return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
									}
								}
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'createTime',
								align: 'center',
								text: '任务已等待时间',
								filter:'date',
								width: 200,
								renderer: function(value) {
									var curDate = new Date();
									var start = new Date(value);
									var min = (curDate - start) / 1000 / 60;
									if(min < 60)
										return Ext.util.Format.number(min, '0') + '分钟';
									else {
										var hour = min / 60;
										return Ext.util.Format.number(hour, '0') + '小时';
									}
								}
							}, {
								xtype:'gridcolumn',
								dataIndex:'owner',
								align:'center',
								text:'任务所有人',
								filter:'string',
								width:'100'
							}],
							bbar: [{
									xtype: 'pagingtoolbar',
									dock: 'bottom',
									bind: {
										store: '{myActiveTask}'
									},
									displayInfo: true,
									displayMsg: '显示 {0} - {1}条记录，总共 {2}条记录',
									emptyMsg: '暂无数据',
									beforePageText: '页数',
									afterPageText: '总共{0}页',
									firstText: '第一页',
									prevText: '上一页',
									nextText: '下一页',
									lastText: '最后一页',
									width: '100%',
									emptyMsg: '没有记录'
								}

							]

						}]
					},

				]

			}, {
				title: "待分配",
				xtype: 'panel',
				layout: {
					type: 'vbox',
					align: 'stretch'
				},
				items: [{
					layout: {
						type: 'vbox',
						align: 'stretch'
					},
					xtype: 'panel',
					title: '<div align="center">待分配事项</div>',
					flex: 1,
					autoScroll: true,
					tbar: ["->", {
						xtype: 'button',
						text: "签收",
						listeners: {
							click: 'onClaimClick'
						}
					}],
					items: [{
						flex: 1,
						xtype: "gridpanel",
						border: false,
						selModel: {
							selType: 'checkboxmodel',
							mode: 'simple'
						}, //
						bind: '{myActiveGroupTask}',
						reference: 'myActiveGroupTaskGrid',
						listeners : {
							select : 'onGroupTaskSelected'
						},
						plugins: 'gridfilters',
						columns: [{
								xtype: 'gridcolumn',
								dataIndex: 'businessKey',
								align: 'center',
								text: '单据编号',
								filter: 'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'businessTypeName',
								align: 'center',
								text: '单据类型',
								filter:'string'
							}, {
								xtype : 'hidden',
								dataIndex:'businessType'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'taskId',
								align: 'center',
								text: '任务ID',
								filter: 'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'taskName',
								align: 'center',
								text: '任务名称',
								filter: 'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'processInstanceId',
								align: 'center',
								text: '流程编号',
								filter: 'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'processInstanceName',
								align: 'center',
								text: '流程名称',
								filter: 'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'createTime',
								text: '任务发起时间',
								filter: 'date',
								align: "center",
								width: 200,
								renderer: function(value) {
									if(value == null) {
										return "";
									} else {
										return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
									}
								}
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'createTime',
								text: '任务已等待时间',
								filter: 'date',
								align: "center",
								width: 200,
								renderer: function(value) {
									var curDate = new Date();
									var start = new Date(value);
									var min = (curDate - start) / 1000 / 60;
									if(min < 60)
										return Ext.util.Format.number(min, '0') + '分钟';
									else {
										var hour = min / 60;
										return Ext.util.Format.number(hour, '0') + '小时';
									}
								}
							}

						],
						bbar: [{
								xtype: 'pagingtoolbar',
								dock: 'bottom',
								bind: {
									store: '{myActiveGroupTask}'
								},
								displayInfo: true,
								displayMsg: '显示 {0} - {1}条记录，总共 {2}条记录',
								emptyMsg: '暂无数据',
								beforePageText: '页数',
								afterPageText: '总共{0}页',
								firstText: '第一页',
								prevText: '上一页',
								nextText: '下一页',
								lastText: '最后一页',
								width: '100%',
								emptyMsg: '没有记录'
							}

						]
					}]
				}]
			},

			{
				layout: {
					type: 'vbox',
					align: 'stretch'
				},
				title: "已处理",
				xtype: "panel",
				autoScroll: true,
				items: [{
					flex: 1,
					xtype: 'panel',
					layout: {
						type: 'vbox',
						align: 'stretch'
					},
					title: '<div align="center">已处理事项</div>',
					border: false,
					autoScroll: true,
					items: [{
						xtype: 'panel',
						layout: {
							type: 'vbox',
							align: 'stretch'
						},
						border: false,
						flex: 1,
						items: [{
							border: false,
							flex: 1,
							xtype: "gridpanel",
							selModel: {
								selType: 'checkboxmodel',
								mode: 'simple'
							},
							bind: '{myFinishedTask}',
							reference: 'myFinishedTaskGrid',
							listeners : {
								select : 'onFinishedTaskSelected'
							},
							plugins: 'gridfilters',
							columns: [{
								xtype: 'gridcolumn',
								dataIndex: 'businessKey',
								align: 'center',
								text: '单据编号',
								filter: 'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'businessTypeName',
								align: 'center',
								text: '单据类型',
								filter: 'string'
							}, {
								xtype : 'hidden',
								dataIndex:'businessType'
							}, {
								xtype: 'gridcolumn',
								align: 'center',
								dataIndex: 'taskId',
								text: '任务ID',
								filter: 'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'taskName',
								align: 'center',
								text: '任务名称',
								filter: 'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'processInstanceId',
								align: 'center',
								text: '流程编号',
								filter: 'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'processInstanceName',
								align: 'center',
								text: '流程名称',
								filter: 'string'
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'createTime',
								align: 'center',
								text: '开始时间',
								filter: 'date',
								width:200,
								renderer: function(value) {
									if(value == null) {
										return "";
									} else {
										return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
									}
								}
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'claimTime',
								align: 'center',
								text: '签收时间',
								filter: 'date',
								width:200,
								renderer: function(value) {
									if(value == null) {
										return "";
									} else {
										return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
									}
								}
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'endTime',
								align: 'center',
								text: '完成时间',
								filter: 'date',
								width:200,
								renderer: function(value) {
									if(value == null) {
										return "";
									} else {
										return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
									}
								}
							}, {
								xtype: 'gridcolumn',
								dataIndex: 'formKey',
								hidden: true
							}],
							bbar: [{
									xtype: 'pagingtoolbar',
									dock: 'bottom',
									bind: {
										store: '{myFinishedTask}'
									},
									displayInfo: true,
									displayMsg: '显示 {0} - {1}条记录，总共 {2}条记录',
									emptyMsg: '暂无数据',
									beforePageText: '页数',
									afterPageText: '总共{0}页',
									firstText: '第一页',
									prevText: '上一页',
									nextText: '下一页',
									lastText: '最后一页',
									width: '100%',
									emptyMsg: '没有记录'
								}

							]

						}]

					}],

				}],

			}

		]
	}, {
		region: "east",
		xtype: 'panel',
		itemId:'eastPanelId',
		viewConfig: {
			enableTextSelection: true
		},
		flex: 1,
	}]

});