/*
 * File: app/view/person/ActivateCardWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.task.TaskAssignWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.taskAssignWindow',

    requires: [
        'Evcorp.view.task.TaskAssignWindowViewModel',
        'Evcorp.view.task.TaskAssignWindowViewController',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.form.field.ComboBox'
    ],
    controller:'taskAssignWindowc',
    viewModel: {
        type: 'taskAssignWindowvm'
    },
    modal: true,
    closable: true,
    height: 120,
    width: 300,
    autoScroll:true,
    title: '指派',
    items:[{
        xtype: "form",
        border: false,
        bodyPadding: 5,
        fieldDefaults: {
            labelAlign: 'right',
            labelWidth: 60,
            width: 250
        },
        items: [{
                xtype: "combobox",
                fieldLabel: "姓名",
                valueField : 'username',
				displayField : 'realname',
//				multiSelect : true,
				itemId : 'assignComboId',
				store:Ext.create('Ext.data.Store',{
						fields : [
								'username',
								'realname'],
						autoLoad: true,
						proxy : {
							type : 'direct',
							directFn: taskContro.findUsers
						}
					}),
				queryMode:'local',
				triggerAction:'all',
		        editable : true,
		        selectOnFocus : true,
		        forceSelection: true,
            },{
            	xtype:'textareafield',
            	grow      : true,
                name      : 'message',
                itemId : 'messageId',
                fieldLabel: '批注',
                anchor    : '100%'
            }]
	}],
	buttons:[{
		text:'确定',
		listeners : {
			click : 'doAssign'
		}
	}]
});