/*
 * File: app/view/menu/menuPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.AssetMGT.contractCarMGTWinViewController', {
	extend : 'Ext.app.ViewController',
	alias : 'controller.contractCarMGTWin',
	control: {
        '#': {
        	close: 'onPanelClose'
        }
    },
    /**
     * 关闭后清空 查询条件里面的参数
     * **/
    onPanelClose: function (panel){
		var conCarMgtStore = Ext.ComponentQuery.query('#conCarMgtGrid')[0]
		.getStore();
		conCarMgtStore.reload();
    },
	queryCarList : function() {
		var contractCarListWindow = Ext.create({
			xtype : 'carProductsWin',
			closeAction : 'destroy'
		});
		// contractCarListWindow.down('#selectContractCarId').removeListener(
		// 'click', 'onChoiceClick');
		contractCarListWindow.down('#selectContractCarId').on({
			click : 'onContractCarInfoSelectCar'
		})
		contractCarListWindow.show();
	},
	onContraCarInfoSave : function() {
		var form = this.lookupReference('contractCarInfoForm');
		var conCarMgtStore = Ext.ComponentQuery.query('#conCarMgtGrid')[0]
				.getStore();
		var win = this.getView();
		var isValid = form.getForm().isValid();
		if (isValid) {
			form.getForm().submit({
				success : function(form, action) {
					Ext.Msg.alert("提示", "保存成功");
					conCarMgtStore.reload();
					win.close();
				},
				failure : function(form, action) {
					Ext.Msg.alert("提示", "系统错误，保存失败");
					win.close();
				}
			})
		} else {
			Ext.Msg.alert("提示", '请把信息填完整');
		}
	},
	onInsuranceAdd : function() {
		var conIns = Ext.create('Evcorp.model.ContractInsurance');
		var viewModel = Ext.create(
				'Evcorp.view.AssetMGT.ContractInsuranceWinViewModel', {
					data : {
						'conIns' : conIns
					}
				});
		var contractInsurancewin = Ext.create({
			xtype : 'contractinsurancewin',
			width : 400,
			height : 300,
			closeAction : 'destroy',
			viewModel : viewModel
		});
		var carInfoId = this.lookupReference('carInfoIdRef');
		contractInsurancewin.down('#carInfoItemId').setValue(carInfoId.getValue());
		contractInsurancewin.show();
	},
	insuranceCompanyEditor : function(value) {
		if (value != undefined) {
			var insuranceCompanyStore = this.getView().getViewModel().getStore(
					'ContractInsurance');
			return insuranceCompanyStore.findRecord('code', value).data.nameCn;
		}
	},
	ContractInsuranceTypeEditor : function(value) {
		if (value != undefined) {
			var insuranceCompanyStore = this.getView().getViewModel().getStore(
					'ContractInsuranceType');
			return insuranceCompanyStore.findRecord('code', value).data.nameCn;
		}
	},
	delInsurance : function() {
		var insuranceGrid = this.lookupReference('insuranceGridRef');
		var selectModel = insuranceGrid.getSelectionModel().getSelection();
		if (selectModel.length == 0) {
			Ext.Msg.alert("提示", '请选择一条记录');
		}else{
			Ext.Ajax
			.request({
				url : 'carInfo/delInsurance',
				params : {
					id : selectModel[0].data.id
				},
				async : false,
				success : function(response) {
					if (response.responseText == "success") {
						Ext.Msg.alert('提示', '删除成功');
						insuranceGrid.getStore()
								.reload();
					}
				}
			});
		}
	},
	updateInsurance : function() {
		var insuranceGrid = this.lookupReference('insuranceGridRef');
		var selectModel = insuranceGrid.getSelectionModel().getSelection();
		var conIns = Ext.create('Evcorp.model.ContractInsurance');
		if (selectModel.length == 0) {
			Ext.Msg.alert("提示", '请选择一条记录');
		} else {
			Ext.apply(conIns, selectModel[0]);
			var viewModel = Ext.create(
					'Evcorp.view.AssetMGT.ContractInsuranceWinViewModel', {
						data : {
							'conIns' : conIns
						}
					});
			var window = Ext.create({
				xtype : 'contractinsurancewin',
				width : 400,
				height : 300,
				closeAction : 'destroy',
				viewModel : viewModel
			});
			var carInfoId = this.lookupReference('carInfoIdRef');
			window.down('#carInfoItemId').setValue(carInfoId.getValue());
			window.show();
		}
	},
	queryRepaymentPlan : function() {
		var suppleAgreementId = this.lookupReference('suppleAgreementIdRef');
		var window = Ext.create({
			xtype : 'repaymentplanWin',
			width : 600,
			height : '50%',
			closeAction : 'destroy'
		});
		var replaymentPlanListStore = window.getViewModel().getStore(
				'replaymentPlanListStore');
		replaymentPlanListStore.getProxy().extraParams = {
			'olPreSaleOrderNo' : suppleAgreementId.getValue()
		};
		replaymentPlanListStore.load();
		window.show();
	}

});
