/*
 * File: app/view/role/RoleMangerPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext
		.define(
				'Evcorp.view.AssetMGT.contractCarMGTPanelViewController',
				{
					extend : 'Ext.app.ViewController',
					alias : 'controller.contractCarMGTPanel',
					control : {
						'#' : {
							afterrender : 'onViewShow',
						}
					},
					onViewShow:function(){
						var carInfoGridStore = this.getView().getViewModel().getStore(
						'carInfoGridStore');
						carInfoGridStore.getProxy().extraParams = {
						};
						carInfoGridStore.loadPage(1, {
							"start" : 0,
							"limit" : 20
						});
					},
					onMGTadd : function() {
						var conCar = Ext.create('Evcorp.model.ContractCarInfo');
						var viewModel = Ext
								.create(
										'Evcorp.view.AssetMGT.contractCarMGTWinViewModel',
										{
											data : {
												'conCar' : conCar,
												'hiddenUploadPanel' : false
											}
										});
						var contractCarMGTwin = Ext.create({
							xtype : 'contractCarMGTWin',
							width : 1000,
							height : '80%',
							closeAction : 'destroy',
							viewModel : viewModel
						});
						var contractPanel = contractCarMGTwin
								.down('#contractPanelItemId');
						contractPanel.setDisabled(true);
						contractCarMGTwin.getViewModel().getStore(
								'ContractInsuranceGridStore').getProxy().extraParams = {
							carInfoId : -1
						};
						contractCarMGTwin.show();
					},
					onQueryCarInfo : function() {
						var conCarMgtGrid = this
								.lookupReference('conCarMgtGridRef');
						var conCarMgtGridForm = this
								.lookupReference('conCarMgtGridForm');
						var extraParams = conCarMgtGridForm.getForm()
								.getValues();
						var conCarMgtStore = conCarMgtGrid.getStore();
						conCarMgtStore.on("beforeload", function(
								conCarMgtStore, operation, eOpts) {
							Ext.apply(conCarMgtStore.proxy.extraParams,
									extraParams);
						});
						conCarMgtStore.loadPage(1, {
							"start" : 0,
							"limit" : 20
						});
					},
					onMGTupd : function() {
						var conCarMgtGrid = this
								.lookupReference('conCarMgtGridRef');
						var selectModel = conCarMgtGrid.getSelectionModel()
								.getSelection();
						var conCar = Ext.create('Evcorp.model.ContractCarInfo');
						if (selectModel.length == 0) {
							Ext.Msg.alert("提示", '请选择一条记录');
						} else {
							var status = selectModel[0].data.status;
							Ext.apply(conCar, selectModel[0]);
							var viewModel = Ext
									.create(
											'Evcorp.view.AssetMGT.contractCarMGTWinViewModel',
											{
												data : {
													'conCar' : conCar,
													'hiddenUploadPanel' : false
												}
											});
							var businessKey = selectModel[0].data.carInfoCode;
							var businessType = "attachBizEntityType_ZCGL";
							var businessTypeName = "资产管理";
							var window = Ext.create({
								xtype : 'contractCarMGTWin',
								width : 1000,
								height : '80%',
								closeAction : 'destroy',
								viewModel : viewModel
							});
							window.getViewModel().getStore(
									'ContractInsuranceGridStore').getProxy().extraParams = {
								carInfoId : selectModel[0].id
							};
							window.down('#insuranceFieldset').disabled = false;
							window.down('#attachmentFieldset').disabled = false;
							var uploadAttachmentPanel = window
									.down('#insuranceAttachmentPanelId');// 保险附件

							if (uploadAttachmentPanel != null) {
								uploadAttachmentPanel.setTitle('');
								var form = uploadAttachmentPanel.down('form');
								if (form != null) {
									var attachmentStore = uploadAttachmentPanel
											.getViewModel().getStore(
													'attachmentStore');
									if (attachmentStore != null) {
										attachmentStore.load({
											params : {
												bizEntityCode : businessKey
											}
										});
									}
									var typeStore = uploadAttachmentPanel
											.getViewModel().getStore(
													'attachmentTypeStore');
									typeStore.load({
										params : {
											type : businessType
										}
									});
									form.getForm().setValues({
										businessKey : businessKey,
										businessType : businessType,
										businessTypeName : businessTypeName
									});
								}
							}
							var contractPanel = window
									.down('#contractPanelItemId');
							if (status == 3) {
								// 已调配锁定
								window.down('#insuranceFieldset').disabled = true;
								window.down('#conCarInsuranceGrid').disabled = true;
							}
							if (status == 2) {
								var busKey = null;
								var busType = "attachBizEntityType_ZLHT";
								var busName = "合同";
								contractPanel.setDisabled(false);

								// 合同
								var carInfoCode = selectModel[0].data.carInfoCode;
								var contractInfoStore = window.getViewModel()
										.getStore('contractInfoStore');
								if (contractInfoStore != null) {
									contractInfoStore
											.load({
												params : {
													'carInfoCode' : carInfoCode
												},
												callback : function(records,
														operation, success) {
													if (success) {
														busKey = records[0].data.suppleAgreementNo;// 补充协议号
														window
																.down(
																		'#suppleAgreementItemId')
																.setValue(
																		busKey);
														var olPreSaleOrderNo = records[0].data.olPreSaleOrderNo;// 租赁合同号
														var contractuploadAttachmentPanel = window
																.down('#contractAttachmentPanelId');// 合同附件
														if (contractuploadAttachmentPanel != null) {
															contractuploadAttachmentPanel
																	.setTitle(null);
															var attachmentStore = contractuploadAttachmentPanel
																	.getViewModel()
																	.getStore(
																			'attachmentStore');
															if (attachmentStore != null) {
																attachmentStore
																		.load({
																			params : {
																				bizEntityCode : busKey
																			}
																		});
															}
															var typeStore = contractuploadAttachmentPanel
																	.getViewModel()
																	.getStore(
																			'attachmentTypeStore');
															typeStore
																	.load({
																		params : {
																			type : busType
																		}
																	});

															form
																	.getForm()
																	.setValues(
																			{
																				businessKey : busKey,
																				businessType : busType,
																				businessTypeName : busName
																			});
														}
														window
																.down(
																		'#contractPanelItemId')
																.loadRecord(
																		records[0]);

														var repaymentStore = window
																.getViewModel()
																.getStore(
																		'repaymentInfoStroe');
														repaymentStore
																.getProxy().extraParams = {
															'olPreSaleOrderNo' : olPreSaleOrderNo
														};
														repaymentStore.load();
													}
												}
											});
								}

							} else {
								contractPanel.setDisabled(true);
							}
							window.show();
							window.center();
						}

					},
					onMGTdel : function() {
						var conCarMgtGrid = this
								.lookupReference('conCarMgtGridRef');
						var selectModel = conCarMgtGrid.getSelectionModel()
								.getSelection();
						var conCar = Ext.create('Evcorp.model.ContractCarInfo');
						if (selectModel.length == 0) {
							Ext.Msg.alert("提示", '请选择一条记录');
						} else {
							if (selectModel[0].data.status != 1) {
								Ext.Msg.alert("提示", '不能删除已租或调配锁定车辆');
							} else {
								Ext.MessageBox.confirm('提示', '确定删除选择车辆?', function(btn) {
									if (btn != 'yes') {
										return;
									}else{
										Ext.Ajax
										.request({
											url : 'carInfo/delCarInfo',
											params : {
												id : selectModel[0].data.id
											},
											async : false,
											success : function(response) {
												if (response.responseText == "success") {
													Ext.Msg.alert('提示', '删除成功');
													conCarMgtGrid.getStore()
															.reload();
												}
											}
										})
									}
								})
							}
						}
					},
					queryCarList : function() {
						var contractCarListWindow = Ext.create({
							xtype : 'carProductsWin',
							closeAction : 'destroy'
						});
						// contractCarListWindow.down('#selectContractCarId').removeListener(
						// 'click', 'onChoiceClick');
						contractCarListWindow.down('#selectContractCarId').on({
							click : 'onContractCarMGTSelectCar'
						})
						contractCarListWindow.show();
					}
				});