/*
 * File: app/view/role/RoleMangerPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.INV.checkoutPanel', {
	extend : 'Ext.panel.Panel',
	alias : 'widget.checkoutPanel',
	requires : [ 
		        'Evcorp.view.INV.checkoutPanelViewController',
				'Evcorp.view.INV.checkoutPanelViewModel',
				'Ext.grid.Panel', 'Ext.tab.Panel', 'Ext.grid.column.Column',
				'Ext.grid.View', 'Ext.toolbar.Toolbar', 'Ext.button.Button',
				'Ext.toolbar.Fill', 'Ext.form.Panel', 'Ext.form.field.ComboBox',
				'Ext.form.DateField'
				],

	controller : 'checkoutPanel',
	viewModel : {
		type : 'checkoutPanel'
	},
	itemId : 'checkoutPanel',
	closable : true,
	collapsible : true,
	referenceHolder : true,
	layout : {
		type : 'vbox',
		align : 'stretch'
	},
      title: '入库',
	autoScroll: true,
    buttons : [{
        xtype: 'tbfill'
    },{
        xtype: "button",
        //cls:'btn-success',
        iconCls:'common-icon-pencil-add',
        text: "新建",
        listeners:{
        	click:'onMGTadd'
        },
    },{
        xtype: "button",
        iconCls:'common-icon-save',
        text: "保存",
        listeners:{
        	click:'onMGTupd'
        },
    },{
        xtype: "button",
        iconCls:'common-icon-checkout',
        text: "出库",
        listeners:{
        	click:'onMGTdel'
        },
    },{
        xtype: "button",
        iconCls:'common-icon-cancel',
        text: "取消",
        listeners:{
        	click:'asdsa'
        },
    },{
        xtype: 'tbfill'
    }],
	items : [{
        xtype: 'form',
        //autoScroll: true,
        reference : 'conCarMgtGridForm',
        bodyPadding: '10',
		layout : {
			type : 'hbox',
			align : 'stretch'
		},
		dockedItems : [{
			xtype : 'toolbar',
			flex : 1,
			dock : 'bottom',
			items : [{
	        	xtype: 'button',
                scale:'small',
                cls:'btn-success',
                iconCls: 'common-icon-add',
	            text: "新增",
	            listeners:{
	            	click:'onMGTupd'
	            },
	        },{
	        	xtype: 'button',
                scale:'small',
                cls:'btn-danger',
                iconCls: 'common-icon-del',
	            text: "删除",
	            listeners:{
	            	click:'onMGTdel'
	            },
	        },{
	            xtype: 'tbfill'
	        }]
		} ],
        items: [{
      	    xtype:'fieldset',
      	    columnWidth: 1,
      	    padding:'20',
      	    margin:'0',
      	    title: '车辆库存查询',
      	    collapsible: true,
      	    defaultType: 'textfield',
      	    defaults: {anchor: '100%'},
      	    layout: 'vbox',
      	    flex:4,
      	    items :[{
      	            	xtype : 'container',
      	                layout: 'hbox',
      	                margin : '10 0 20 0',
      	                border:false,
      	                items :[
      	                            {
      	                            	 xtype : 'textfield',
                                         fieldLabel : '出库单号',
                                         name : 'stockName',
      	                                 labelWidth : 70,
      	                                 width : 200,
      	                            }, {
      	                              xtype: 'button',
	      	                          text: '查 找',
	      	                          scale:'small',
	      	                          margin:'0 0 0 10',
	      	                          iconCls: 'common-icon-serach',
	      	                          cls:'nu-btn-nobg',
	      	                          handler:'oncarCheckoutAdd',
      	                            },
      	                            {
      	                                xtype : 'textfield',
      	                                fieldLabel : '出库业务类型',
      	                                name : 'stockStatus',
      	                                labelWidth : 100,
      	                                width : 230,
      	                                margin : '0 0 0 20'
      	                            },
      	                            {
      	                                xtype : 'textfield',
      	                                fieldLabel : '创建人',
      	                                name : 'outboundType',
      	                                labelWidth : 70,
      	                                width : 200,
      	                                margin : '0 0 0 20'
      	                            },{

                                          xtype:'datefield',                                        
                                          fieldLabel: '创建日期',
                                          format: 'Y-m-d',
                                          name:'checkinDate',
                                          width : 200,
                                          labelWidth : 70,
                                          margin : '0 0 0 20'
                                          	
                                      
      	                            }
      	                     ]
      	            
      	            }]
      	}]
    },
    {	flex : 4,
		border : false,
		xtype : 'gridpanel',
		viewConfig: { enableTextSelection: true },
		reference : 'conCarMgtGridRef',
		itemId : 'conCarMgtGrid',
		autoScroll : true,
		selModel: {
    	        selType: 'checkboxmodel',
    	        mode: 'SIMPLE'
    	    },
        columns: [
						
  	              	{ xtype: 'gridcolumn',hidden:true,dataIndex:'id'},
  	              	{ xtype: 'gridcolumn',hidden:true,dataIndex:'createBy'},
  	                { xtype: 'gridcolumn', text: '产品代码', dataIndex: 'dealeName' },
  	                { xtype: 'gridcolumn',  text: '仓库', dataIndex: 'stock', width:150},
  	                { xtype: 'gridcolumn',  text: '库位', dataIndex: 'storageLocation', width:150},
  	                { xtype: 'gridcolumn',  text: '品牌', dataIndex: 'brand', width:150},
  	                { xtype: 'gridcolumn',  text: '车系', dataIndex: 'carSeriesCode', width:150},
  	                { xtype: 'gridcolumn',  text: '车型', dataIndex: 'carModelCode', width:150},
  	                { xtype: 'gridcolumn',  text: '产品名称', dataIndex: 'proName', width:150},
  	                { xtype: 'gridcolumn',  text: '颜色', align:'center', dataIndex: '', width:150},
  	                { xtype: 'gridcolumn',  text: '附加成本', align:'center', dataIndex: '', width:150},
  	                { xtype: 'gridcolumn',  text: '库存状态', dataIndex: '', width:150},
  	                { xtype: 'gridcolumn',  text: '配车状态', dataIndex: '', width:150},
  	                { xtype: 'gridcolumn',  text: '车辆价格', dataIndex: '', width:150},
  	                { xtype: 'gridcolumn',  text: '销售订单编号', dataIndex: '', width:150},
  	                { xtype: 'gridcolumn',  text: '质损状态', dataIndex: 'massLoss', width:150},
  	                { xtype: 'gridcolumn',  text: '是否二手车', align:'center', dataIndex: 'usedCar', width:150},
  	                { xtype: 'gridcolumn',  text: '是否试乘试驾', align:'center', dataIndex: 'testCar', width:150 },
  	                { xtype: 'gridcolumn',  text: '是否促销车', align:'center', dataIndex: 'promotionCar', width:150},
  	                { xtype: 'gridcolumn',  text: '是否采购退回', align:'center', dataIndex: 'promotionCar', width:150},
  	                { xtype: 'gridcolumn',  text: '是否调价', dataIndex: '', width:150},
  	                { xtype: 'gridcolumn',  text: '调价原因', dataIndex: '', width:150},
  	                { xtype: 'gridcolumn',  text: '销售指导价', dataIndex: '', width:150},
  	                { xtype: 'gridcolumn',  text: '备注', dataIndex: '', width:150},
  	                ],
					bbar : [ {
						xtype : 'pagingtoolbar',
						bind : {
							store : '{carInfoGridStore}'
						},
						displayMsg : '显示 {0} - {1} 条，共计 {2} 条',
						emptyMsg : "没有数据",
						beforePageText : "当前页",
						afterPageText : "共{0}页",
						displayInfo : true,
						width : '100%'
					} ],
    },{
    	xtype : 'container',
    	flex:3,
        layout: 'vbox',
        border:false,
        autoScroll : true,
    	items:[{
		 border:false,html:'<h2 class="panel-title">客户信息</h2>'
	},{
      	xtype : 'container',
          layout: 'hbox',
          margin : '10 20',
          border:false,
          items :[
                      {
                      	 xtype : 'textfield',
                         fieldLabel : '姓名',
                         readOnly: true,
                         cls:'textfield-noBorder',
                         name : 'stockName',
                         labelWidth : 100,
                         width : 230,
                      },{
                      	 xtype : 'textfield',
                         fieldLabel : '性别',
                         readOnly: true,
                         cls:'textfield-noBorder',
                         name : 'stockName',
                         labelWidth : 100,
                         width : 230,
                      },
                      {
                          xtype : 'textfield',
                          fieldLabel : '手机号码',
                          readOnly: true,
                          cls:'textfield-noBorder',
                          name : 'stockStatus',
                          labelWidth : 100,
                          width : 230,
                          margin : '0 20'
                      },
               ]
	},{
      	xtype : 'container',
        layout: 'hbox',
        margin : '10 20',
        border:false,
        items :[
                    {
                    	 xtype : 'textfield',
                       fieldLabel : '客户类型',
                       readOnly: true,
                       cls:'textfield-noBorder',
                       name : 'stockName',
                       labelWidth : 100,
                       width : 230,
                    },{
                    	 xtype : 'textfield',
                       fieldLabel : '联系人',
                       readOnly: true,
                       cls:'textfield-noBorder',
                       name : 'stockName',
                       labelWidth : 100,
                       width : 230,
                    },
                    {
                        xtype : 'textfield',
                        fieldLabel : '身份证号',
                        readOnly: true,
                        cls:'textfield-noBorder',
                        name : 'stockStatus',
                        labelWidth : 100,
                        width : 230,
                        margin : '0 20'
                    },
             ]
	},{
      	xtype : 'container',
        layout: 'hbox',
        margin : '10 20',
        border:false,
        items :[
                    {
                    	 xtype : 'textfield',
                       fieldLabel : '邮箱',
                       readOnly: true,
                       cls:'textfield-noBorder',
                       name : 'stockName',
                       labelWidth : 100,
                       width : 230,
                    },{
                    	 xtype : 'textfield',
                       fieldLabel : '性别',
                       readOnly: true,
                       cls:'textfield-noBorder',
                       name : 'stockName',
                       labelWidth : 100,
                       width : 230,
                    },
                    {
                        xtype : 'textfield',
                        fieldLabel : '家庭人数',
                        readOnly: true,
                        cls:'textfield-noBorder',
                        name : 'stockStatus',
                        labelWidth : 100,
                        width : 230,
                        margin : '0 20'
                    },
             ]
	},{
      	xtype : 'container',
        layout: 'hbox',
        margin : '10 20',
        border:false,
        items :[
                    {
                    	 xtype : 'textfield',
                       fieldLabel : '姓名',
                       readOnly: true,
                       cls:'textfield-noBorder',
                       name : 'stockName',
                       labelWidth : 100,
                       width : 230,
                    },{
                    	 xtype : 'textfield',
                       fieldLabel : '住宅地址',
                       readOnly: true,
                       cls:'textfield-noBorder',
                       name : 'stockName',
                       labelWidth : 100,
                       width : 230,
                    },
                    {
                        xtype : 'textfield',
                        fieldLabel : '住宅邮编',
                        readOnly: true,
                        cls:'textfield-noBorder',
                        name : 'stockStatus',
                        labelWidth : 100,
                        width : 230,
                        margin : '0 20'
                    },{

                        xtype : 'textfield',
                        fieldLabel : '住宅电话',
                        readOnly: true,
                        cls:'textfield-noBorder',
                        name : 'stockStatus',
                        labelWidth : 100,
                        width : 230,
                        margin : '0 20'
                    
                    }
             ]
	},{
		 border:false,html:'<h2 class="panel-title">车辆信息</h2>'
	},{
      	xtype : 'container',
        layout: 'hbox',
        margin : '10 20',
        border:false,
        items :[
                    {
                    	 xtype : 'textfield',
                       fieldLabel : '产品名称',
                       name : 'stockName',
                       labelWidth : 100,
                       width : 230,
                    },{
                    	 xtype : 'textfield',
                       fieldLabel : '颜色',
                       name : 'stockName',
                       labelWidth : 100,
                       width : 230,
                       margin : '0 20'
                    },
                    {
                        xtype : 'textfield',
                        fieldLabel : 'VIN',
                        name : 'stockStatus',
                        labelWidth : 100,
                        width : 230,
                        margin : '0 20'
                    },{

                        xtype : 'textfield',
                        fieldLabel : '车牌号',
                        name : 'stockStatus',
                        labelWidth : 100,
                        width : 230,
                        margin : '0 20'
                    
                    }
             ]
	},{
      	xtype : 'container',
        layout: 'hbox',
        margin : '10 20',
        border:false,
        items :[
                    {
                    	xtype:'textfield',
                    	labelWidth : 100,
                        width : 230,
                        fieldLabel: '开票日期',
                        name:'createDateString',
                        editable : false
                    },
                    {
                    	xtype:'textfield',
                    	labelWidth : 100,
                        width : 230,
                        margin : '0 20',
                        fieldLabel: '开票日期',
                        name:'createDateString',
                        editable : false

                    },{

                        xtype : 'textfield',
                        fieldLabel : '销售里程数',
                        name : 'stockStatus',
                        labelWidth : 100,
                        width : 230,
                        margin : '0 20'
                    
                    }
             ]
	}]
    }
    
    
    
    
    

]

});