/*
 * File: app/view/role/RoleMangerPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.INV.checkinPanel',
		{
			extend : 'Ext.panel.Panel',
			alias : 'widget.checkinPanel',
			requires : [ 'Evcorp.view.INV.checkinPanelViewController',
					'Evcorp.view.INV.checkinPanelViewModel', 'Ext.grid.Panel',
					'Ext.tab.Panel', 'Ext.grid.column.Column', 'Ext.grid.View',
					'Ext.toolbar.Toolbar', 'Ext.button.Button',
					'Ext.toolbar.Fill', 'Ext.form.Panel',
					'Ext.form.field.ComboBox', 'Ext.form.DateField' ],

			controller : 'checkinPanel',
			viewModel : {
				type : 'checkinPanel'
			},
			itemId : 'checkinPanel',
			closable : true,
			collapsible : true,
			referenceHolder : true,
			layout : {
				type : 'vbox',
				align : 'stretch'
			},
			title : '入库',
			autoScroll : true,
			items : [
					{
						xtype : 'form',
						flex : 1,
						autoScroll : true,
						reference : 'carStockInForm',
						bodyPadding : '10',
						items : [ {
							xtype : 'fieldset',
							columnWidth : 1,
							padding : '20',
							margin : '0',
							title : '入库',
							collapsible : true,
							defaultType : 'textfield',
							defaults : {
								anchor : '100%'
							},
							layout : 'vbox',
							flex : 1,
							items : [ {
								xtype : 'container',
								layout : 'hbox',
								margin : '10 0 20 0',
								border : false,
								items : [ {
									xtype : 'textfield',
									fieldLabel : '入库单号',
									name : 'stockInNo',
									reference : 'stockInNo',
									labelWidth : 80,
									width : 200,
								}, {
									xtype : 'button',
									text : '查找',
									cls:'nu-btn-nobg',
									reference : 'searchCarStockInBtn',
									iconCls : 'common-icon-serach',
									margin : '0 15',
									width : 60,
									listeners : {
										click : 'onSearchCarStockInClick'
									}
								}, {
									xtype : 'combobox',
									fieldLabel : '入库类型',
									name : 'stockInType',
									labelWidth : 80,
									width : 230,
									margin : '0 10 0 0',
									valueField : "code",
									displayField : "nameCn",
									queryModel : 'local',
									bind : {
										store : '{stockInTypeStore}'
									},
									forceSelection : true,
									editable : false,
									allowBlank : false,
								}, {
									xtype : 'combobox',
									fieldLabel : '创建人',
									name : 'drawer',
									labelWidth : 60,
									width : 160,
									margin : '0 10 0 0',
									valueField : "id",
									displayField : "username",
									queryModel : 'local',
									bind : {
										store : '{drawerStore}'
									},
									forceSelection : true,
									editable : false,
									allowBlank : false,
								}, {
									xtype : 'datefield',
									width : 190,
									labelWidth : 80,
//									endDateField : 'etime',
									fieldLabel : '创建日期',
									format : 'Y-m-d',
									name : 'stockInDate'
								}
								]

							}, {
								xtype : 'container',
								layout : 'hbox',
								margin : '10 0 20 0',
								border : false,
								items : [ {
									xtype : "textarea",
									margin : '15 auto',
									padding : '15',
									fieldLabel : "备注",
									name : "remark",
									labelSepartor : "：",
									labelWidth : 80,
									width : '90%',

								}]
							}, {
								xtype : 'container',
								layout : 'hbox',
								margin : '10 0 20 0',
								border : false,
								items : [ {
									xtype : 'button',
									cls:'nu-btn-nobg',
									text : '保存入库单',									
									iconCls: 'nu-save',
									width : 100,
									listeners : {
										click : 'onProviderSearch',
									}
								} ]
							} ]
						} ],
						dockedItems : [ {
							xtype : 'toolbar',
							flex : 1,
							dock : 'bottom',
							items : [ {
								xtype : "button",
								// cls:'btn-success',
								text : "新增",
								cls:'btn-success',
								iconCls : 'common-icon-add',
								listeners : {
									click : 'onStockAdd'
								},
							}, {
								xtype : "button",
								// cls:'btn-success',
								text : "修改",
								cls:'btn-primary', 
								iconCls : 'nu-order_edit',
								listeners : {
									click : 'onMGTadd'
								},
							}, {
								xtype : "button",
								// cls:'btn-success',
								text : "导入",
								cls:'btn-primary', 
								iconCls: 'common_icon_export_excel' ,
								listeners : {
									click : 'onMGTadd'
								},
							}, {
								xtype : "button",
								// cls:'btn-success',
								text : "导出",
								cls:'btn-primary', 
								iconCls : 'nu-export',
								listeners : {
									click : 'onMGTupd'
								},
							}, {
								xtype : "button",
								// cls:'btn-success',
								text : "删除",
								cls:'btn-danger', 
								iconCls: 'common-icon-del',
								listeners : {
									click : 'onMGTdel'
								},
							}, {
								xtype : 'tbfill'
							} ]
						} ]
					},
					{
						border : false,
						flex : 1,
						xtype : 'gridpanel',
						viewConfig: { enableTextSelection: true },
						reference : 'conCarMgtGridRef',
						itemId : 'conCarMgtGrid',
						autoScroll : true,
						columns : [

								{
									xtype : 'gridcolumn',
									text : '是否入账',
									align : 'center',
									dataIndex : 'enterInAccountSattus'
								},
								{
									xtype : 'gridcolumn',
									text : '是否代验收',
									align : 'center',
									dataIndex : 'agentAcceptanceStatus'
								},
								{
									xtype : 'gridcolumn',
									text : '是否直销',
									align : 'center',
									dataIndex : 'directSellingStatus'
								},
								{
									xtype : 'gridcolumn',
									text : '验收结果',
									align : 'center',
									dataIndex : 'acceptanceResult'
								},
								{
									xtype : 'gridcolumn',
									text : 'VIN',
									align : 'center',
									dataIndex : 'carFrameNo',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '产品代码',
									align : 'center',
									dataIndex : 'carProductCode'
								},
								{
									xtype : 'gridcolumn',
									text : '品牌',
									dataIndex : 'carBrandCode',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '车系',
									dataIndex : 'carSeriesCode',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '车型',
									dataIndex : 'carModelCode',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '产品名称',
									dataIndex : 'proName',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '颜色',
									align : 'center',
									dataIndex : 'color',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '仓库',
									dataIndex : 'stock',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '发动机号',
									dataIndex : 'carEngineNo',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '供应商',
									dataIndex : 'supplier',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : 'Call车单号',
									align : 'center',
									dataIndex : 'carCallNo'
								},
								{
									xtype : 'gridcolumn',
									text : '厂家订单号',
									align : 'center',
									dataIndex : 'supplierOrderNo'
								},
								{
									xtype : 'gridcolumn',
									text : '资金来源',
									align : 'center',
									dataIndex : 'sourceOfFund'
								},
								{
									xtype : 'gridcolumn',
									text : '钥匙编号',
									dataIndex : 'carKeyNo',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '合格证号',
									dataIndex : 'carDriveLicenseNo',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '排气量',
									align : 'center',
									dataIndex : 'displacement',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '车辆类型',
									dataIndex : 'carType',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '生产日期',
									align : 'center',
									dataIndex : 'madeDate',
									width : 150,
									renderer : function(value) {
										if (value == null) {
											return "";
										} else {
											return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
										}
									}
								},
								{
									xtype : 'gridcolumn',
									text : '出厂日期',
									align : 'center',
									dataIndex : 'productionDate',
									width : 150,
									renderer : function(value) {
										if (value == null) {
											return "";
										} else {
											return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
										}
									}
								},
								{
									xtype : 'gridcolumn',
									text : '排放标准',
									dataIndex : 'dischargeStandard',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '车辆免息期',
									dataIndex : 'carFreePeriod',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '附加成本',
									dataIndex : 'additionalCost',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '含税采购价',
									align : 'center',
									dataIndex : 'taxPurchasePrice',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '税率',
									align : 'center',
									dataIndex : 'taxRate'
								},
								{
									xtype : 'gridcolumn',
									text : '不含税采购价',
									align : 'center',
									dataIndex : 'taxExcludedPurchasePrice',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '发车日期',
									align : 'center',
									dataIndex : 'sendCarDate',
									width : 150,
									renderer : function(value) {
										if (value == null) {
											return "";
										} else {
											return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
										}
									}
								},
								{
									xtype : 'gridcolumn',
									text : '预计送达日期',
									align : 'center',
									dataIndex : 'expectedDeliveryDate',
									width : 150,
									renderer : function(value) {
										if (value == null) {
											return "";
										} else {
											return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
										}
									}
								},
								{
									xtype : 'gridcolumn',
									text : '发货单号',
									dataIndex : 'invoiceNo',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '实际送到日期',
									align : 'center',
									dataIndex : 'realDeliveryDate',
									width : 150,
									renderer : function(value) {
										if (value == null) {
											return "";
										} else {
											return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
										}
									}
								},
								{
									xtype : 'gridcolumn',
									text : '送车人姓名',
									dataIndex : 'deliveryManName',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '送车人电话',
									dataIndex : 'deliveryManPhone',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '承运车牌号',
									dataIndex : 'deliveryCarPlateNo',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '承运商名称',
									dataIndex : 'deliveryCompanyName',
									width : 150
								},
								{
									xtype : 'gridcolumn',
									text : '采购日期',
									align : 'center',
									dataIndex : 'purchaseDate',
									width : 150,
									renderer : function(value) {
										if (value == null) {
											return "";
										} else {
											return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
										}
									}
								},
								{
									xtype : 'gridcolumn',
									text : '收货人地址',
									dataIndex : 'receiptAddress',
									width : 150
								},],
						buttons : [
						           {
										xtype : 'tbfill'
									}, {
										xtype : 'button',
										text : '新增',
										cale : 'small',
										iconCls : 'common-icon-add',
										margin : '0 10',
										listeners : {
											click : 'onStockInAdd'
										}
									}, {
										xtype : 'button',
										text : '保存',
										cale : 'small',
										iconCls : 'common-icon-save',
										margin : '0 10',
										listeners : {
											click : 'save'
										}
									}, {
										xtype : 'button',
										text : '入库',
										cale : 'small',
										iconCls : 'common-icon-checkin',
										margin : '0 10',
										listeners : {
											click : 'checkin'
										}
									}, {
										xtype : 'button',
										text : '验收',
										cale : 'small',
										iconCls : 'common-icon-acceptance-check',
										margin : '0 10',
										listeners : {
											click : 'onCheckingResult'
										}
									}, {
										xtype : "button",
										text : "取消",
										margin : "0 10",
										iconCls : 'common-icon-cancel',
										handler : function() {
											this.up("window").close();
										}
									}, {
										xtype : "button",
										text : "退出",
										margin : "0 10",
										iconCls : 'common-icon-del',
										handler : function() {
											this.up("window").close();
										}
									}, {
										xtype : 'tbfill'
									} ],
					/*
					 * bbar : [ { xtype : 'pagingtoolbar', bind : { store :
					 * '{carInfoGridStore}' }, displayMsg : '显示 {0} - {1} 条，共计
					 * {2} 条', emptyMsg : "没有数据", beforePageText : "当前页",
					 * afterPageText : "共{0}页", displayInfo : true, width :
					 * '100%' } ],
					 */
					}

			]

		});
