/*
 * File: app/view/role/RoleMangerPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.INV.stockSearchPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.stockSearchPanel',
    yyyyMMddDateEditor:function(value){
    	if(value == null) {
			return "";
		} else {
			return Ext.Date.format(new Date(value), 'Y-m-d');
		}
	},
	yyyyMMddHHMMSSDateEditor:function(value){
    	if(value == null) {
			return "";
		} else {
			return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
		}
	},
	// 入库
    onStockInClick : function() {
    	var stockInListWin = Ext.create({
    		xtype : 'stockInListWin',
    		width : 1000,
    		closeAction : 'destroy'
    	});
    	stockInListWin.show();
    },
    // 出库
    onStockOutClick : function() {
    	var carStockGrid = this.lookupReference('carStockGridRef');
    	var sel = carStockGrid.getSelectionModel().getSelection();
    	if (sel.length<=0) {
    		Ext.Msg.alert("提示",'请选择一条库存信息！');
    		return;
    	}
    	var data = sel[0].data;
    	var stockOutWin = Ext.create({
    		xtype : 'stockOutWin',
    		width : '500px',
    		closeAction : 'destroy'
    	});
    	stockOutWin.down('#stockOutOKItemId').on({
    		click : 'onStockOutOK'
    	})
    	stockOutWin.down('#vinItemId').setValue(data.vin);
    	stockOutWin.show();
    },
    // 修改
    onStockModifyClick : function () {
		var carStockGrid = this.lookupReference('carStockGridRef');
    	var sel = carStockGrid.getSelectionModel().getSelection();
    	if (sel.length<=0) {
    		Ext.Msg.alert("提示",'请选择一条要修改的库存信息！');
    		return;
    	}
    	var data = sel[0].data;
    	var stockInListWin = Ext.create({
    		xtype : 'stockInListWin',
    		width : 1000,
    		closeAction : 'destroy'
    	});
    	stockInListWin.down('#stockInTypeItemId').setDisabled(true);
    	stockInListWin.down('#lastStockInDateItemId').setDisabled(true);
    	stockInListWin.down('#lastStockInRemarkItemId').setDisabled(true);
    	stockInListWin.down('#carStockIdItemId').setValue(data.carStockId);
    	stockInListWin.down('#vinItemId').setValue(data.vin);
    	stockInListWin.down('#stockItemId').setValue(data.stock);
    	stockInListWin.down('#stockPositionNoItemId').setValue(data.stockPositionNo);
    	stockInListWin.down('#carProductCodeItemId').setValue(data.carProductCode);
    	stockInListWin.down('#carProductNameItemId').setValue(data.carProductName);
    	stockInListWin.down('#carTypeItemId').setValue(data.carType);
    	stockInListWin.down('#agencyItemId').setValue(data.agency);
    	stockInListWin.down('#stockInTypeItemId').setValue(data.stockInType);
    	stockInListWin.down('#lastStockInDateItemId').setValue(data.lastStockInDate);
    	stockInListWin.down('#lastStockInRemarkItemId').setValue(data.lastStockInRemark);
    	stockInListWin.down('#carDriveLicenseNoItemId').setValue(data.carDriveLicenseNo);
    	stockInListWin.down('#carEngineNoItemId').setValue(data.carEngineNo);
    	stockInListWin.down('#carKeyNoItemId').setValue(data.carKeyNo);
    	stockInListWin.down('#sourceOfFundItemId').setValue(data.sourceOfFund);
    	stockInListWin.down('#carFreePeriodItemId').setValue(data.carFreePeriod);
    	stockInListWin.down('#additionalCostItemId').setValue(data.additionalCost);
    	stockInListWin.down('#productingAddressItemId').setValue(data.productingAddress);
    	stockInListWin.down('#certificateLocatedItemId').setValue(data.certificateLocated);
    	stockInListWin.down('#isEnterInAccountItemId').setValue(data.isEnterInAccount);
    	stockInListWin.down('#carCallNoItemId').setValue(data.carCallNo);
    	stockInListWin.down('#supplierOrderNoItemId').setValue(data.supplierOrderNo);
    	stockInListWin.down('#saleOrderNoItemId').setValue(data.saleOrderNo);
    	stockInListWin.down('#isBigCustomerItemId').setValue(data.isBigCustomer);
    	stockInListWin.down('#isAgentAcceptanceItemId').setValue(data.isAgentAcceptance);
    	stockInListWin.down('#isDirectSellingItemId').setValue(data.isDirectSelling);
    	stockInListWin.down('#remarkItemId').setValue(data.remark);
    	stockInListWin.down('#realDeliveryDateItemId').setValue(data.realDeliveryDate);
    	stockInListWin.down('#purchaseDateItemId').setValue(data.purchaseDate);
    	stockInListWin.down('#venderCodeItemId').setValue(data.venderCode);
    	stockInListWin.down('#venderNameItemId').setValue(data.venderName);
    	stockInListWin.down('#acceptanceResultItemId').setValue(data.acceptanceResult);
    	stockInListWin.down('#damageStatusItemId').setValue(data.damageStatus);
    	stockInListWin.down('#acceptanceRemarkItemId').setValue(data.acceptanceRemark);
    	stockInListWin.down('#inspectorItemId').setValue(data.inspector);
    	stockInListWin.down('#inspectionDateItemId').setValue(data.inspectionDate);
    	stockInListWin.show();
    },
	onQueryCarStock:function() {
		var queryForm = this.lookupReference('carStockQueryForm');
		var extraParams = queryForm.getForm().getValues();
	    var listGrid = this.lookupReference('carStockGridRef');
	    var dataStore = listGrid.getStore();
        dataStore.on("beforeload", function (dataStore, operation, eOpts) {
					 	Ext.apply(dataStore.proxy.extraParams, extraParams);
					});
        dataStore.loadPage(1,{"start":0,"limit":20});
        listGrid.getSelectionModel().deselectAll();
	},
	// 重置
	onResetQuery:function() {
		var queryForm = this.lookupReference('carStockQueryForm');
		queryForm.reset();
	},
	// 查找供应商
    onProviderSearch : function() {
    	var carStockQueryForm = this.lookupReference('carStockQueryForm');
    	var carProviderListWin = Ext.create({
    		 xtype : 'carProviderListWin',
    		 width : 600,
    		 closeAction : 'destroy'
    	});
    	carProviderListWin.show();
    	carProviderListWin.down('#carProviderOkBtn').on('click', function () {
    		var grid = carProviderListWin.down("#carVenderGridItemId");
        	var sel = grid.getSelectionModel().getSelection();
    		if (sel.length <= 0) {
    			Ext.Msg.alert('提示','请先选择一个供应商！');
    			return;
    		}
    		var vender = sel[0].data;
        	if(carStockQueryForm!=null){
        		carStockQueryForm.getForm().findField('venderCode').setValue(vender.code);
        		carStockQueryForm.getForm().findField('venderName').setValue(vender.fullName);
        	}
        	carProviderListWin.close();
    	});
    },
    
    // 品牌、车系、车型级联
    onCarBrandChange:function(como, newValue, oldValue){
    	var combox = this.lookupReference('carSeriesCodeRef');
    	var store = combox.getStore();
    	store.removeAll();
    	combox.setValue('');
    	if (!newValue || newValue=='all') {
    		return;
    	}
    	var carBrand = newValue;
        var extraParams = {type:carBrand};
        store.on("beforeload", function (store, operation, eOpts) {
			 Ext.apply(store.proxy.extraParams, extraParams);
		});
        store.load();
    },
    
    // 品牌、车系、车型级联
    onCarSeriesChange:function(como, newValue, oldValue){
    	var combox = this.lookupReference('carModelCodeRef');
    	var store = combox.getStore();
    	store.removeAll();
    	combox.setValue('');
    	if (!newValue || newValue=='all') {
    		return;
    	}
    	var carModel = newValue;
        var extraParams = {type:carModel};
        store.on("beforeload", function (store, operation, eOpts) {
			 Ext.apply(store.proxy.extraParams, extraParams);
		});
        store.load();
    },
});
