/*
 * File: app/view/role/RoleMangerPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.process.ProcessRightPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.processrightpanel',

    requires: [
        'Evcorp.view.process.ProcessRightPanelViewController',
        'Evcorp.view.process.ProcessRightPanelViewModel',
        'Ext.grid.Panel',
        'Ext.tab.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox'
    ],
    
    controller:'processRightPanelc',
    viewModel: {
        type: 'processRightPanelvm'
    },
    referenceHolder: true,
    itemId:'ProcessRightPanel',
   // closable: true,  //可以关闭
    layout: {
		type: 'vbox',
		align: 'stretch'
	},
	items: [{
				flex: 1,
				xtype: "panel",
				itemId:'imgPanel',
				reference:'imgPanel',
				//title:"流程",
				autoScroll: true,
				bodyStyle: "width:100%;height:100%;",
				html: '',
				aligin: 'center',
				//border:false
			}, {
				xtype: "tabpanel",
				flex: 1,
				split: true,
				forceFit: true,
				activeTab: 0,
				enableTabScroll: true, //选项卡过多时，允许滚动
				defaults: {
					autoScroll: true
				},
				items:[{
						xtype: "gridpanel",
						flex: 1,
						title: "<div align='center'>流程变量</div>",
						forceFit: true,
						reference:'variableGrid',
						itemId:'variableGridId',
						bind:'{variableStore}',
						columns: [{
							xtype: 'gridcolumn',
							align: 'center',
							dataIndex: 'name',
							text: '变量名'
						}, 
						{
							xtype: 'gridcolumn',
							align:'center',									
							dataIndex: 'value',
							text: '变量值'
						}
						]
				},{
					xtype: "gridpanel",
					flex: 1,
					title: "<div align='center'>流程历史</div>",
					forceFit: true,
					reference:'historicTaskGrid',
					itemId:'historicTaskGridId',
					bind:'{historicTaskStore}',
					columns: [{
						xtype: 'gridcolumn',
						align: 'center',
						dataIndex: 'taskName',
						text: '任务名称'
					}, 
					{
						xtype: 'gridcolumn',
						align:'center',									
						dataIndex: 'assignee',
						text: '任务处理人'
					},
					{
						xtype: 'gridcolumn',
						align:'center',									
						dataIndex: 'createTime',
						text: '任务创建时间',
						renderer: function(value) {
							if(value == null) {
								return "";
							} else {
								return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
							}
						}
					},
					{
						xtype: 'gridcolumn',
						align:'center',									
						dataIndex: 'claimTime',
						text: '任务签收时间',
						renderer: function(value) {
							if(value == null) {
								return "";
							} else {
								return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
							}
						}
					},
					{
						xtype: 'gridcolumn',
						align:'center',									
						dataIndex: 'endTime',
						text: '任务完成时间',
						renderer: function(value) {
							if(value == null) {
								return "";
							} else {
								return Ext.Date.format(new Date(value), 'Y-m-d H:i:s');
							}
						}
					}
					]
				}]
			}
		]
});