/*
 * File: app/view/role/ProcessPanelViewModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Evcorp.view.process.ProcessPanelViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.processpanelvm',
    stores: {
    	myStartedProcess: {
            model: 'Evcorp.model.Process',
            pageSize: 20,
            autoLoad: true,
            proxy: {
                type: 'direct',
                api: {
                    read: processContro.findMyStartedProcessList
                },
                reader: {
                    type: 'json',
                    rootProperty: 'records',
                    totalProperty: 'total'
                }
            }
        },
        myInvovledProcess: {
            model: 'Evcorp.model.Process',
            pageSize: 20,
            autoLoad: true,
            proxy: {
                type: 'direct',
                api: {
                    read: processContro.findMyInvovledProcessList
                },
                reader: {
                    type: 'json',
                    rootProperty: 'records',
                    totalProperty: 'total'
                }
            }
        },
        myFinishedProcess: {
            model: 'Evcorp.model.Process',
            pageSize: 20,
            autoLoad: true,
            proxy: {
                type: 'direct',
                api: {
                    read: processContro.findMyFinishedProcessList
                },
                reader: {
                    type: 'json',
                    rootProperty: 'records',
                    totalProperty: 'total'
                }
            }
        }
    }
});