// JavaScript Document
$(document).ready(function(){
	$("#ball_1").click(function(){
		$("#con_1").fadeIn();
	});	
	$("#ball_2").click(function(){
		$("#con_2").fadeIn();
	});
	$("#ball_3").click(function(){
		$("#con_3").fadeIn();
	});
	$("#ball_4").click(function(){
		$("#con_4").fadeIn();
	});
	$("#ball_5").click(function(){
		$("#con_5").fadeIn();
	});
	$("#reg_close").click(function(){
		$("#con_1").fadeOut();
	});
	$("#reg_close2").click(function(){
		$("#con_2").fadeOut();
	});
	$("#reg_close3").click(function(){
		$("#con_3").fadeOut();
	});
	$("#reg_close4").click(function(){
		$("#con_4").fadeOut();
	});
	$("#reg_close5").click(function(){
		$("#con_5").fadeOut();
	});
	$("#reg_close6").click(function(){
		$("#con_6").fadeOut();
	});
	$("#reg_close7").click(function(){
		$("#con_7").fadeOut();
	});
	$("#btn").click(function(){
			doPost();	
	});
	$("#img1").click(function(){
		for(i=1;i<=7;i++){
			$("#con_"+i).hide();		
		}				  
		$("#con_5").fadeIn();						  
	});
	
		$("#img2").click(function(){
		for(i=1;i<=7;i++){
			$("#con_"+i).hide();		
		}				  
		$("#con_3").fadeIn();						  
	});
		$("#img3").click(function(){
		for(i=1;i<=7;i++){
			$("#con_"+i).hide();		
		}				  
		$("#con_1").fadeIn();						  
	});
		$("#img4").click(function(){
		for(i=1;i<=7;i++){
			$("#con_"+i).hide();		
		}				  
		$("#con_2").fadeIn();						  
	});
		$("#img5").click(function(){
		for(i=1;i<=7;i++){
			$("#con_"+i).hide();		
		}				  
		$("#con_4").fadeIn();						  
	});
		
	$("#img7").click(function(){
		for(i=1;i<=7;i++){
			$("#con_"+i).hide();		
		}				  
		$("#con_6").fadeIn();						  
	});
	$("#img6").click(function(){
		for(i=1;i<=7;i++){
			$("#con_"+i).hide();		
		}				  
		$("#con_7").fadeIn();						  
	});
	$("#img8").click(function(){
		for(i=1;i<=7;i++){
			$("#con_"+i).hide();		
		}				  
							  
	});
});
function doPost(){
	if($("input[name='email']").val()==""){
		$("#result_reg").html("请填写邮箱！");
		$("input[name='email']").focus();
		setTimeout(function(){$("#result_reg").html("&nbsp;");},2000);	
		return;		
	}
	if(!isEmail($("input[name='email']").val())){
		$("#result_reg").html("邮箱格式不正确，请重新填写！");
		$("input[name='email']").focus();
		setTimeout(function(){$("#result_reg").html("&nbsp;");},2000);	
		return;
	}
	if($("input[name='name']").val()==""){
		$("#result_reg").html("请填写真实姓名！");
		$("input[name='name']").focus();
		setTimeout(function(){$("#result_reg").html("&nbsp;");},2000);	
		return;		
	}
	if($("input[name='handset']").val()==""){
		$("#result_reg").html("请填写手机号码！");
		$("input[name='handset']").focus();
		setTimeout(function(){$("#result_reg").html("&nbsp;");},2000);	
		return;		
	}
	if($("input[name='phone']").val()==""){
		$("#result_reg").html("请填写电话号码！");
		$("input[name='phone']").focus();
		setTimeout(function(){$("#result_reg").html("&nbsp;");},2000);	
		return;		
	}
	if($("input[name='company_name']").val()==""){
		$("#result_reg").html("请填写公司名称！");
		$("input[name='company_name']").focus();
		setTimeout(function(){$("#result_reg").html("&nbsp;");},2000);	
		return;		
	}
	if($("input[name='post']").val()==""){
		$("#result_reg").html("请填写职务！");
		$("input[name='post']").focus();
		setTimeout(function(){$("#result_reg").html("&nbsp;");},2000);	
		return;		
	}if($("#company_type").val()==""){
		$("#result_reg").html("请选择公司类型！");
		$("#company_type").focus();
		setTimeout(function(){$("#result_reg").html("&nbsp;");},2000);	
		return;		
	}
	$("#status").show();
	jQuery.post('/webcast/lib/doAjax.jsp',{'email':$("input[name='email']").val(),'name':$("input[name='name']").val(),'handset':$("input[name='handset']").val(),'phone':$("input[name='phone']").val(),'company_name':$("input[name='company_name']").val(),'post':$("input[name='post']").val(),'company_type':$("#company_type").val(),'company_address':$("input[name='company_address']").val(),'post_code':$("input[name='post_code']").val(),'seminar_id':'4','type':'baoming'},function(data){
		//alert(data);
		if(data==1){
			$("#status").hide();
			$("#result_bao").html("此邮件已经注册过，请更换邮箱重新注册！");
			$("input[name='email']").focus();
			setTimeout(function(){$("#result_bao").html("");},3000);
			return;	 
		}else if(data==2){
			$("#status").hide();
			$("#result_bao").html("您已报名成功！");
			return;	 
		}else{
			$("#status").hide();
			$("#result_bao").html("服务器繁忙，请稍后再试。");
			setTimeout(function(){$("#result_bao").html("");},3000);	
			return;
		}					
	});	
}

function isEmail( str ){  
	var myReg = /^[-_A-Za-z0-9]+@([_A-Za-z0-9]+\.)+[A-Za-z0-9]{2,3}$/; 
	if(myReg.test(str)) return true; 
	return false; 
}
